### ISSUE TITLE
load model issues

### ISSUE THREAD

**Issue by cici-tan** [catboost/catboost#1831] opened 2021-09-02 03:07 UTC
Problem: This error came out - Process finished with exit code 139 (interrupted by signal 11: SIGSEGV) when I load a 2G catboost model. 
catboost version: 0.26.1
Operating System: Ubuntu 18.04.3 
CPU:48  Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
GPU:NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0

**Comment by kizill** [comment] 2021-09-23 06:13
Can you attach a gdb debugger to report us a problematic stacktrace?

**Comment by kizill** [comment] 2021-09-24 11:45
Closing as we can't reproduce due to lack of details for reproduction. Please, reopen if you can provide us any information for issue reproduction. Thank you!

**Closed by kizill** 2021-09-24 11:45 UTC
Labels: need info, bug, python
