### ISSUE TITLE
Feature: Be able to load model from stream/blob or file descriptor

### ISSUE THREAD

**Issue by victorbartel** [catboost/catboost#1371] opened 2020-07-31 08:03 UTC
Problem: It's not always handy to load model from a path.
catboost version: 0.23
Operating System: Linux

Greetings,

I'm using CatBoost for prediction within Cloud Functions, where time and resources are of the essence. My models are stored in the GCP buckets. Nowadays I have to convert GCP bucket blob into tmp file, peek the path to such file and finally pass it to the `CatBoostRegressor().load_model` method, and then clean up the tmp file. It would be great to load model directly from a blob or file descriptor without all those dances with bags and pipes around the fire. Something like:

```python
blob = storage.Client().get_bucket(bucket).blob(path)
CatBoostRegressor().load_model(blob)
```

Many thanks.

**Comment by kizill** [comment] 2020-07-31 08:07
We've finished this in master bcb9b505e669fe37e2b66466ea9009dda8f1288a, still need to make some passes over it :) I'd recommend to wait till monday or tuesday,  we are preparing to release 0.24
By the way, we will support loading from path, file-like streams and binary blobs.

**Comment by victorbartel** [comment] 2020-07-31 09:12
Hey @kizill, 
Sounds merely awesome, thanks a lot!

**Comment by kizill** [comment] 2020-08-03 07:27
Closing as partial duplicate of #1149

**Closed by kizill** 2020-08-03 07:27 UTC
