### ISSUE TITLE
The difference ranking result in the python and libcatboost by max_relevance times

### ISSUE THREAD

**Issue by akalend** [catboost/catboost#2612] opened 2024-03-14 05:59 UTC
**Problem**:
The difference  result  of the rank model  in the python and libcatboost
Разные результаты при работе модели в python и си кода с использованием libcatboost.  Отличаются на величину max_relevance

**Steps of problem:**
1) I use the training model from tutorial https://github.com/catboost/tutorials/tree/master/ranking
 
2) The url of my  notebook of the model is https://colab.research.google.com/drive/1IXzicNub6CtzPRW3ZUfFkud48EDgaLhC?usp=sharing

3) The RMSE criterion was used.

4) The model saved as cbm format and use in the C-code. The example of code : https://github.com/cyrusmsk/tutorials/tree/clang_dlang_applier_tutorials/apply_model/clang

5) compare results from Python and C-code (libcatboost) : the results differ by max_relevance times (4 times) . See cell number 29 in the notebook (Itemt 2).

The original  C-code https://github.com/akalend/pg_ml/blob/main/ml.c

**catboost version**:   catboost-1.2.3-cp310-cp310-manylinux2014_x86_64.whl ( Google collab)
**Operating System**: Ubuntu 20.0
**CPU**: iCore i5 local machine

**Comment by andrey-khropov** [comment] 2024-04-18 16:02
I cannot reproduce this.

See [the training code in python and inference code in C++](https://gist.github.com/andrey-khropov/2ea97d8d4fd025f2bb038e49dc8d1986). In my example they produce the same predictions.
I tried both single-object and multi-objects variants.

**Comment by andrey-khropov** [comment] 2024-08-18 17:55
No additional info is provided, so I am closing this issue. Feel free to reopen with more details if necessary.

**Closed by andrey-khropov** 2024-08-18 17:55 UTC
Labels: need info, python, C/C++ applier
