### ISSUE TITLE
Evaluation error in calibration/test bigger than without using the boost_from_average for the same number of iterations

### ISSUE THREAD

**Issue by pvalienteverde** [catboost/catboost#1061] opened 2019-11-04 17:08 UTC
**Problem:** Evaluation error in calibration bigger than without using the boost_from_average for the same number of iterations
**catboost version:** 0.18
**Operating System:** Fedora28
**CPU:** Intel® Core™ i7-6700 CPU @ 3.40GHz × 8 

I thought that using the boost-from-average parameter it was going to need less iterations to get the same error in the calibration however I'm surprise because it happens the opposite. Why could it be happening? Should I have in mind other parameters?

```python
params_1 = {"boosting_type": "Ordered", 
            "depth": 8, 
            "iterations": 4000, 
            "learning_rate": 0.02, 
            "loss_function": "RMSE", 
            "random_seed": 13, 
            "rsm": 1, 
            "thread_count": 6,
            "boost_from_average":False}

model_1 = CatBoostRegressor(**params_1)
model_1.fit(train,verbose_eval=200)
"""
0:	learn: 1.0063058	total: 70.5ms	remaining: 4m 41s
200:	learn: 0.0478413	total: 17.1s	remaining: 5m 22s
400:	learn: 0.0306676	total: 32s	remaining: 4m 47s
600:	learn: 0.0292926	total: 40.6s	remaining: 3m 49s
800:	learn: 0.0273375	total: 47.2s	remaining: 3m 8s
1000:	learn: 0.0252011	total: 56.6s	remaining: 2m 49s
1200:	learn: 0.0235399	total: 1m 4s	remaining: 2m 30s
1400:	learn: 0.0226771	total: 1m 12s	remaining: 2m 14s
1600:	learn: 0.0220625	total: 1m 19s	remaining: 1m 58s
1800:	learn: 0.0214496	total: 1m 25s	remaining: 1m 44s
2000:	learn: 0.0209545	total: 1m 32s	remaining: 1m 32s
2200:	learn: 0.0204591	total: 1m 40s	remaining: 1m 21s
2400:	learn: 0.0200947	total: 1m 46s	remaining: 1m 11s
2600:	learn: 0.0198609	total: 1m 53s	remaining: 1m 1s
2800:	learn: 0.0196329	total: 2m	remaining: 51.6s
3000:	learn: 0.0194235	total: 2m 7s	remaining: 42.4s
3200:	learn: 0.0192086	total: 2m 14s	remaining: 33.5s
3400:	learn: 0.0190321	total: 2m 19s	remaining: 24.6s
3600:	learn: 0.0188889	total: 2m 25s	remaining: 16.1s
3800:	learn: 0.0187505	total: 2m 30s	remaining: 7.86s
3999:	learn: 0.0186423	total: 2m 35s	remaining: 0us
"""
params_2 = params_1.copy()
params_2['boost_from_average'] = True
model_2 = CatBoostRegressor(**params_2)
model_2.fit(train,verbose_eval=200)

"""
0:	learn: 0.2176364	total: 78.4ms	remaining: 5m 13s
200:	learn: 0.0418534	total: 14.6s	remaining: 4m 35s
400:	learn: 0.0290421	total: 28.9s	remaining: 4m 18s
600:	learn: 0.0290307	total: 30.6s	remaining: 2m 53s
800:	learn: 0.0290284	total: 31.6s	remaining: 2m 6s
1000:	learn: 0.0290268	total: 32.5s	remaining: 1m 37s
1200:	learn: 0.0290250	total: 33.4s	remaining: 1m 17s
1400:	learn: 0.0290238	total: 34.3s	remaining: 1m 3s
1600:	learn: 0.0290228	total: 35.2s	remaining: 52.7s
1800:	learn: 0.0290221	total: 36.1s	remaining: 44s
2000:	learn: 0.0290214	total: 37s	remaining: 37s
2200:	learn: 0.0290207	total: 38s	remaining: 31s
2400:	learn: 0.0290202	total: 38.9s	remaining: 25.9s
2600:	learn: 0.0290199	total: 39.8s	remaining: 21.4s
2800:	learn: 0.0290194	total: 40.7s	remaining: 17.4s
3000:	learn: 0.0290190	total: 41.6s	remaining: 13.9s
3200:	learn: 0.0290186	total: 42.6s	remaining: 10.6s
3400:	learn: 0.0290184	total: 43.6s	remaining: 7.68s
3600:	learn: 0.0290180	total: 44.6s	remaining: 4.94s
3800:	learn: 0.0290177	total: 45.6s	remaining: 2.39s
3999:	learn: 0.0290174	total: 46.6s	remaining: 0us
"""


```

**Comment by ek-ak** [comment] 2019-11-08 14:28
Hello! Using boost_from_average option doesn't guarantee better results. Have you try to fit with test or cross-validation and are you sure with chosen number of iterations?
Could you provide more information about pool - maybe it's part?

**Comment by pvalienteverde** [comment] 2019-11-11 16:51
But at least I expected to have less calibration error, and it didn't happen when boosting_type is **Ordered** .

But when _boosting_type=Plain_, it reach less calibration error with the same iterations, moreover, a similar error is obtained if the mean of the variable is eliminated and _boost_from_average=False_

```python
data = read()
pool = Pool(data=data.iloc[:, 1:].values, label=data.iloc[:,0].values,feature_names=data.columns.values[1:].tolist())


params_1 = {"boosting_type": "Ordered", 
            "depth": 8, 
            "iterations": 4000, 
            "learning_rate": 0.02, 
            "loss_function": "RMSE", 
            "random_seed": 13, 
            "rsm": 1, 
            "thread_count": 6,
            "boost_from_average":False}

params_plain = params_1.copy()
params_plain["boosting_type"]="Plain"

model_1 = CatBoostRegressor(**params_plain)
model_1.fit(pool)

"""
0:	learn: 1.0063469	total: 11.5ms	remaining: 46.2s
600:	learn: 0.0201934	total: 6.79s	remaining: 38.4s
1200:	learn: 0.0135340	total: 13.4s	remaining: 31.2s
1800:	learn: 0.0105709	total: 20s	remaining: 24.5s
2400:	learn: 0.0088146	total: 26.7s	remaining: 17.8s
3000:	learn: 0.0076188	total: 33.4s	remaining: 11.1s
3600:	learn: 0.0067742	total: 40.3s	remaining: 4.46s
3999:	learn: 0.0063101	total: 44.7s	remaining: 0us
"""

labels = np.array(pool.get_label())
pool_zero = Pool(data=pool.get_features(), label=labels - np.mean(labels),feature_names=pool.get_feature_names())

params_plain_zero = params_plain.copy()
params_plain_zero["boosting_type"]="Plain"
params_plain_zero['boost_from_average'] = False

model_plain_zero = CatBoostRegressor(**params_plain_zero)
model_plain_zero.fit(pool_zero)

"""
0:	learn: 0.2173923	total: 17.1ms	remaining: 1m 8s
600:	learn: 0.0189936	total: 7.54s	remaining: 42.6s
1200:	learn: 0.0129254	total: 14.1s	remaining: 32.8s
1800:	learn: 0.0101497	total: 21.2s	remaining: 25.9s
2400:	learn: 0.0084503	total: 27.7s	remaining: 18.5s
3000:	learn: 0.0073010	total: 34.4s	remaining: 11.4s
3600:	learn: 0.0064884	total: 40.9s	remaining: 4.53s
3999:	learn: 0.0060396	total: 45.2s	remaining: 0us
"""

params_plain_boost_from_average = params_plain.copy()
params_plain_boost_from_average['boost_from_average'] = True
params_plain_boost_from_average["boosting_type"]="Plain"

model_plain_boost_from_average = CatBoostRegressor(**params_plain_boost_from_average)
model_plain_boost_from_average.fit(pool)

"""
0:	learn: 0.2173923	total: 12.2ms	remaining: 48.7s
600:	learn: 0.0189936	total: 6.68s	remaining: 37.8s
1200:	learn: 0.0129920	total: 13s	remaining: 30.3s
1800:	learn: 0.0101860	total: 19.5s	remaining: 23.8s
2400:	learn: 0.0084872	total: 26s	remaining: 17.3s
3000:	learn: 0.0073142	total: 32.7s	remaining: 10.9s
3600:	learn: 0.0064855	total: 39.2s	remaining: 4.35s
3999:	learn: 0.0060478	total: 43.5s	remaining: 0us
"""

```

But,  it didn't happen when boosting_type is **Ordered**:

```python
model_ordered = CatBoostRegressor(**params_1)
model_ordered.fit(pool,verbose_eval=200)
"""
0:	learn: 1.0063058	total: 70.5ms	remaining: 4m 41s
600:	learn: 0.0292926	total: 40.6s	remaining: 3m 49s
1200:	learn: 0.0235399	total: 1m 4s	remaining: 2m 30s
1800:	learn: 0.0214496	total: 1m 25s	remaining: 1m 44s
2400:	learn: 0.0200947	total: 1m 46s	remaining: 1m 11s
3000:	learn: 0.0194235	total: 2m 7s	remaining: 42.4s
3600:	learn: 0.0188889	total: 2m 25s	remaining: 16.1s
3999:	learn: 0.0186423	total: 2m 35s	remaining: 0us
"""

model_ordered_zero = CatBoostRegressor(**params_1)
model_ordered_zero.fit(pool_zero,verbose_eval=200)

"""
0:	learn: 0.2174596	total: 80.5ms	remaining: 5m 21s
600:	learn: 0.0214528	total: 41.1s	remaining: 3m 52s
1200:	learn: 0.0172865	total: 1m 6s	remaining: 2m 34s
1800:	learn: 0.0154464	total: 1m 30s	remaining: 1m 50s
2400:	learn: 0.0144111	total: 1m 49s	remaining: 1m 12s
3000:	learn: 0.0135679	total: 2m 7s	remaining: 42.6s
3600:	learn: 0.0130850	total: 2m 23s	remaining: 15.9s
3999:	learn: 0.0128323	total: 2m 35s	remaining: 0us
"""

params_ordered_boost_from_average = params_1.copy()
params_ordered_boost_from_average['boost_from_average'] = True
model_ordered_boost_from_average = CatBoostRegressor(**params_ordered_boost_from_average)
model_ordered_boost_from_average.fit(train,verbose_eval=200)

"""
0:	learn: 0.2176364	total: 78.4ms	remaining: 5m 13s
600:	learn: 0.0290307	total: 30.6s	remaining: 2m 53s
1200:	learn: 0.0290250	total: 33.4s	remaining: 1m 17s
1800:	learn: 0.0290221	total: 36.1s	remaining: 44s
2400:	learn: 0.0290202	total: 38.9s	remaining: 25.9s
3000:	learn: 0.0290190	total: 41.6s	remaining: 13.9s
3600:	learn: 0.0290180	total: 44.6s	remaining: 4.94s
3999:	learn: 0.0290174	total: 46.6s	remaining: 0us
"""
```

Why don't I get similar behaviors between ordered and plain? The final error in calibration in _boosting_type=Ordered_ with _boost_from_average=True_ is very different if the average is eliminated (mean=0)

||plain|ordered|
|---|---|---|
|baseline|From 1.0063469 to 0.0063101|From 1.0063058 to 0.0186423|
|boost_from_average=True|From 0.2173923 to 0.0060396|From 0.2174596 to 0.0128323|
|boost_from_average=False and without mean|From 0.2173923 to 0.0060478|From 0.2176364 to 0.0290174|

**Comment by LyzhinIvan** [comment] 2019-11-12 09:15
Hello, @pvalienteverde ! It looks strange that total time of fitting for ordered boosting with boost_from_average is very close to fitting time for plain boosting. I can't reproduce such behavior with random data. Could you provide your dataset, please? You can upload your data to any cloud storage and send me link by email.

**Comment by pvalienteverde** [comment] 2019-11-12 11:35
Hello @LyzhinIvan 

Link send by email,

Thank you

**Comment by LyzhinIvan** [comment] 2019-11-13 10:24
@pvalienteverde , I've experimented with your dataset. Actually, as @ek-ak said above, boost_from_average=True does not guarantee better results. Anyway, here we have another problem. Training is getting stuck. If you specify logging_level=Info, you will see that starting from some iteration the algorithm builds trees with one split only. It is peculiarity of ordered boosting, because it tries not overfit and doesn't see whole dataset. So you can use Plain boosting or play with other params. For example, I've found that setting score_function=L2 helps to manage with this problem for your dataset.

**Comment by pvalienteverde** [comment] 2019-11-13 13:09
@LyzhinIvan , Thank you for the information

But the results are similar in plain boosting in the case you activate boost_from_average or in the case you delete the average(centered in zero) deactivating boost_from_average.

Should the results be similar in the ordered boosting activating boost_from_average and deactivating boost_from_average but centered in zero as in plain ordered?

**Comment by LyzhinIvan** [comment] 2019-11-13 13:32
@pvalienteverde , No, for the ordered boosting results will be different in such cases.

**Comment by annaveronika** [comment] 2019-11-14 08:12
@pvalienteverde Thanks a lot for the issue, I hope we've answered your questions. Closing the issue.

**Closed by annaveronika** 2019-11-14 08:12 UTC
