### ISSUE TITLE
How to make a CPU Training deterministic (without randomness)?

### ISSUE THREAD

**Issue by The-Gupta** [catboost/catboost#1587] opened 2021-02-15 16:13 UTC
I'm using a _CatBoostClassifier_ and _predict_proba()_, see the results vary when I change _thread_count_. I'm using a _random_seed_, and also, _rsm=1_ and _random_strength=0_ as suggested [here](https://github.com/catboost/catboost/issues/334#issuecomment-388044152). 
CatBoost version: 0.24.2
Operating System: Ubuntu 20.04.1
CPU: AMD EPYC 7702P 64-Core Processor

@annaveronika , please help.

**Comment by LyzhinIvan** [comment] 2021-02-16 11:05
Hi, @The-Gupta! 

Please, provide all options specified in model. I can't reproduce such behavior. It will be perfect if you provide a reproducible script with a bunch of your data.

**Comment by kizill** [comment] 2021-03-29 01:13
Closing as details, needed for reproduction is missing. Feel free to reopen this issue if you can give us information, to help us reproduce your issue!

**Closed by kizill** 2021-03-29 01:13 UTC
Labels: does not reproduce, need info
