### ISSUE TITLE
CatBoost sparse features support

### ISSUE THREAD

**Issue by hanky** [catboost/catboost#361] opened 2018-05-25 11:31 UTC
Hello.

According to the #1 issue, currently CatBoost does not support sparse matrices. And until it's ready, what options do I have when working with word features?

An example:
- we have 20k special words and some document category features
- words are special within particular categories
- pairs (word, category) have small coverage in a training set
- each document may contain more than 1 special word, maybe a few

How do we encode those words? One hot encoding for words works not quite well for CatBoost because of low coverage. We could use other model for words, but there are categories and some other features, so we prefer to train a single CatBoost model.

Could it be some hashing trick with generation of some category features based on word hashes? Is there a common approach for CatBoost to deal with that?

Thank you.

**Comment by hugoncosta** [comment] 2018-05-25 17:40
In Kaggle, there's a [challenge](https://www.kaggle.com/c/avito-demand-prediction) where some of the participants are using text features to analyse product descriptions. For CatBoost, they're all doing one hot enconding using tf-idf though.

**Comment by annaveronika** [comment] 2018-10-03 16:30
We are planning to support sparse features, so you need to wait for #1. I suppose it's a duplicate of #1 since there are no other action points. We plan to start working on that in the middle of this month, so I hope this will come out soon.

As for working with sparse features now - I would not recommend to use hashing tricks, they didn't work well according to my experience. One-hot encoding is an option, for catboost you can try one_hot_max_size. Also for working with texts, it usually works well to build some embeddings and pass features on top of them as regular numerical features.

**Closed by annaveronika** 2018-10-03 16:30 UTC
