### ISSUE TITLE
Issue trying to compile with specified gcc version

### ISSUE THREAD

**Issue by ctlaltdefeat** [catboost/catboost#386] opened 2018-06-13 22:16 UTC
I'm trying to compile the catboost python wheel on my system. The default gcc version I have is 8, but I also have 7 installed so I'm trying to use that by setting the CC and CXX environment variables. However, when running:
```
python mk_wheel.py -DCUDA_ROOT="/opt/cuda"
```
I get the message:
```
Info: Attention! Using system user-defined compiler: g++-7 (check CC and CXX env vars).
Cross compilation with system CXX is not supported
```
catboost version: git master
Operating System: Linux
CPU: i7
GPU: GTX 1080

Thanks!

**Comment by dbakshee** [comment] 2018-06-15 02:49
You are right about gcc-8 not supporting that option. 
However, catboost build system is set up to _not use system compilers_, and I wonder how do you manage to get this error. If you add option `-v` it will show more details, and it might help if you posted some.

**Comment by ctlaltdefeat** [comment] 2018-06-15 09:27
Is there some way to specify what compiler to use? I have both gcc-6 and gcc-7 binaries.
I ran it with ```-v``` and got lots of details but I'm not sure what's relevant. This is the line before the failure:

```
command /root/.ya/tools/v3/173608153/python /home/user/catboost/build/scripts/compile_cuda.py /opt/cuda/bin/nvcc -std=c++14 --expt-relaxed-constexpr -gencode arch=compute_30,code=compute_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=compute_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=compute_60 -gencode arch=compute_61,code=compute_61 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_70,code=compute_70 -c /home/user/catboost/catboost/cuda/cuda_util/kernel/partitions.cu -o /root/.ya/build/build_root/vojc/00013b/catboost/cuda/cuda_util/kernel/partitions.cu.obj -I/root/.ya/build/build_root/vojc/00013b -I/home/user/catboost -I/home/user/catboost/contrib/libs/cxxsupp/libcxxrt -I/home/user/catboost/contrib/libs/cxxsupp/libcxx/include -I/home/user/catboost/contrib/libs/double-conversion/include -I/home/user/catboost/contrib/libs/libf2c --cflags --target=x86_64-linux-gnu -B$OS_SDK_ROOT_RESOURCE_GLOBAL/usr/bin -pipe -m64 -msse -msse3 -msse2 -O2 -Wno-inconsistent-missing-override -Wno-c++17-extensions -Wno-exceptions -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DGNU -D_GNU_SOURCE -DSSE_ENABLED=1 -DSSE3_ENABLED=1 -DSSE2_ENABLED=1 -DNDEBUG -D_THREAD_SAFE -D_PTHREADS -D_REENTRANT -D__LONG_LONG_SUPPORTED -Wall -W -Wno-parentheses -Wno-deprecated -fPIC -DCATBOOST_OPENSOURCE=yes -I/opt/cuda/include -nostdinc++ -DFAKEID=3638217 -DARCADIA_ROOT=/home/user/catboost -DARCADIA_BUILD_ROOT=/root/.ya/build/build_root/vojc/00013b 
```

**Comment by yt87** [comment] 2018-06-16 23:13
Same situation here.  

    [gtrojan@asok bin]$ cat /etc/redhat-release 
    Fedora release 28 (Twenty Eight)

I had to install gcc 6.4 to build cuda 9.1. Without setting CC and CXX I get the same error about unrecognised option `--target`. With

    [gtrojan@asok catboost]$ export CC=/usr/local/gcc-6.4.0/bin/gcc
    [gtrojan@asok catboost]$ export CXX=/usr/local/gcc-6.4.0/bin/g++

the error is

    [gtrojan@asok catboost]$ !1312
    ../../../ya make -r -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DPYTHON_CONFIG=/usr/localPython-3.6.5/bin/python3-config -DCUDA_ROOT=/usr/local/cuda-9.1
    Info: Attention! Using system user-defined compiler: /usr/local/gcc-6.4.0/bin/g++ (check CC and CXX env vars).
    Cross compilation with system CXX is not supported.

The I tried

    [gtrojan@asok catboost]$ unset CXX

Few files are compiled successfully, then I get an error:

    [gtrojan@asok catboost]$ ../../../ya make -r -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local DPYTHON_CONFIG=/usr/local/Python-3.6.5/bin/python3-config -DCUDA_ROOT=/usr/local/cuda-9.1
    Info: Attention! Using system user-defined compiler: None (check CC and CXX env vars).
    | 0.0%| [CC] {pic} $(S)/catboost/libs/data/doc_pool_data_provider.cpp +3 more / 
    | 0.4%| [CC] {pic} $(S)/catboost/cuda/cuda_lib/tasks_impl/memory_state_func.cpp
    | 0.3%| [CC] {pic} $(S)/catboost/cuda/cuda_lib/tasks_impl/memory_state_func.cpp     
    | 0.2%| [CC] {pic} $(S)/catboost/cuda/cuda_lib/tasks_impl/memory_state_func.cpp 
    | 0.1%| [CC] {pic} $(S)/catboost/cuda/cuda_lib/tasks_impl/memory_state_func.cpp 
     ------- [CC] {pic, FAILED} $(S)/catboost/cuda/cuda_lib/tasks_impl/request_stream_task.cpp

    command /usr/local/gcc-6.4.0/bin/gcc -c -o /home/gtrojan/.ya/build/build_root/0v12/000007/catboost/cuda/cuda_lib/tasks_impl/request_stream_task.cpp.pic.o /mnt/sdc1/home/gtrojan/Downloads/catboost/catboost/cuda/cuda_lib/tasks_impl/request_stream_task.cpp -I/home/gtrojan/.ya/build/build_root/0v12/000007 -I/mnt/sdc1/home/gtrojan/Downloads/catboost -I/mnt/sdc1/home/gtrojan/Downloads/catboost/contrib/libs/cxxsupp/libcxx/include -I/mnt/sdc1/home/gtrojan/Downloads/catboost/contrib/libs/double-conversion/include -I/mnt/sdc1/home/gtrojan/Downloads/catboost/contrib/libs/libf2c -Woverloaded-virtual -Wno-invalid-offsetof -Wno-attributes -std=c++14 -pipe -m64 -msse -msse3 -msse2 -O2 -fno-delete-null-pointer-checks -fabi-version=8 -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DGNU -D_GNU_SOURCE -DSSE_ENABLED=1 -DSSE3_ENABLED=1 -DSSE2_ENABLED=1 -DNDEBUG -D_THREAD_SAFE -D_PTHREADS -D_REENTRANT -D__LONG_LONG_SUPPORTED -Wall -W -Wno-parentheses -Wno-deprecated -fPIC -DCATBOOST_OPENSOURCE=yes -I/usr/local/cuda-9.1/include -DFAKEID=3638217 -DARCADIA_ROOT=/mnt/sdc1/home/gtrojan/Downloads/catboost -DARCADIA_BUILD_ROOT=/home/gtrojan/.ya/build/build_root/0v12/000007 -nostdinc++ failed with exit code 1
    In file included from /mnt/sdc1/home/gtrojan/Downloads/catboost/catboost/cuda/cuda_lib/task.h:3:0,
                 from /mnt/sdc1/home/gtrojan/Downloads/catboost/catboost/cuda/cuda_lib/tasks_impl/request_stream_task.h:4,
                 from /mnt/sdc1/home/gtrojan/Downloads/catboost/catboost/cuda/cuda_lib/tasks_impl/request_stream_task.cpp:1:
      /mnt/sdc1/home/gtrojan/Downloads/catboost/catboost/cuda/cuda_lib/cuda_base.h: In destructor 'NCudaLib::TCudaStreamsProvider::~TCudaStreamsProvider()':
     /mnt/sdc1/home/gtrojan/Downloads/catboost/catboost/cuda/cuda_lib/cuda_base.h:24:107: warning: throw will always call terminate() [-Wterminate]
             ythrow TCatboostException() << "CUDA error: " << cudaGetErrorString(errorCode) << " " << (int)errorCode; \
                                                                                                           ^
     /mnt/sdc1/home/gtrojan/Downloads/catboost/catboost/cuda/cuda_lib/cuda_base.h:73:17: note: in expansion of macro 'CUDA_SAFE_CALL'
                 CUDA_SAFE_CALL(cudaStreamDestroy(stream));
                 ^~~~~~~~~~~~~~
     /mnt/sdc1/home/gtrojan/Downloads/catboost/catboost/cuda/cuda_lib/cuda_base.h:24:107: note: in C++11 destructors default to noexcept
             ythrow TCatboostException() << "CUDA error: " << cudaGetErrorString(errorCode) << " " << (int)errorCode; \
                                                                                                           ^
    /mnt/sdc1/home/gtrojan/Downloads/catboost/catboost/cuda/cuda_lib/cuda_base.h:73:17: note: in expansion of macro 'CUDA_SAFE_CALL'
                 CUDA_SAFE_CALL(cudaStreamDestroy(stream));
                 ^~~~~~~~~~~~~~
    In file included from /mnt/sdc1/home/gtrojan/Downloads/catboost/catboost/cuda/cuda_lib/task.h:4:0,
                 from /mnt/sdc1/home/gtrojan/Downloads/catboost/catboost/cuda/cuda_lib/tasks_impl/request_stream_task.h:4,
                 from /mnt/sdc1/home/gtrojan/Downloads/catboost/catboost/cuda/cuda_lib/tasks_impl/request_stream_task.cpp:1:
    /mnt/sdc1/home/gtrojan/Downloads/catboost/catboost/cuda/cuda_lib/remote_objects.h: In member function 'void* NCudaLib::THandleBasedMemoryPointer<T, Type>::GetRawPtr()':
     /mnt/sdc1/home/gtrojan/Downloads/catboost/catboost/cuda/cuda_lib/remote_objects.h:168:66: error: there are no arguments to 'THandleRawPtr' that depend on a template parameter, so a declaration of 'THandleRawPtr' must be available [-fpermissive]
             return THandleRawPtr(Type, Handle, sizeof(T) * Offset);
                                                                  ^
     /mnt/sdc1/home/gtrojan/Downloads/catboost/catboost/cuda/cuda_lib/remote_objects.h:168:66: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
    Failed

Under `~/.ya` I found directory `gcc/x86_64-linux-gnu/4.6`. Should I try to install yet another version of gcc?

**Comment by dbakshee** [comment] 2018-06-18 12:08
@yt87 , your situation is not the same. 
Could you try adding this flag to your 'ya make ...' command:
`-DCUDA_NVCC_FLAGS="-Xcompiler -fpermissive"`  ?

**Comment by yt87** [comment] 2018-06-19 04:17
No luck with *permissive* flag either. With the default Fedora gcc 8.01 the error is

    [gtrojan@asok catboost]$ ../../../ya make -r -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DCUDA_NVCC_FLAGS="-Xcompiler -fpermissive" -DPYTHON_CONFIG=/usr/local/Python-3.6.5/bin/python3-config -DCUDA_ROOT=/usr/local/cuda-9.0
    | 0.1%| [CC] {pic} $(S)/catboost/cuda/cuda_util/kernel/operators.cu +8 more / 13------- [CC] {pic, FAILED} $(S)/catboost/cuda/cuda_lib/kernel/reduce.cu
     command /home/gtrojan/.ya/tools/v3/173608153/python /mnt/sdc1/home/gtrojan/Downloads/catboost-8.0.1/build/scripts/compile_cuda.py /usr/local/cuda-9.0/bin/nvcc -std=c++14 -Xcompiler -fpermissive -gencode arch=compute_30,code=compute_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=compute_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=compute_60 -gencode arch=compute_61,code=compute_61 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_70,code=compute_70 -c /mnt/sdc1/home/gtrojan/Downloads/catboost-8.0.1/catboost/cuda/cuda_lib/kernel/reduce.cu -o /home/gtrojan/.ya/build/build_root/tm83/000cce/catboost/cuda/cuda_lib/kernel/reduce.cu.obj -I/home/gtrojan/.ya/build/build_root/tm83/000cce -I/mnt/sdc1/home/gtrojan/Downloads/catboost-8.0.1 -I/mnt/sdc1/home/gtrojan/Downloads/catboost-8.0.1/contrib/libs/cxxsupp/libcxxrt -I/mnt/sdc1/home/gtrojan/Downloads/catboost-8.0.1/contrib/libs/cxxsupp/libcxx/include -I/mnt/sdc1/home/gtrojan/Downloads/catboost-8.0.1/contrib/libs/double-conversion/include -I/mnt/sdc1/home/gtrojan/Downloads/catboost-8.0.1/contrib/libs/libf2c --cflags --target=x86_64-linux-gnu -B$OS_SDK_ROOT_RESOURCE_GLOBAL/usr/bin -pipe -m64 -msse -msse3 -msse2 -O2 -Wno-inconsistent-missing-override -Wno-c++17-extensions -Wno-exceptions -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DGNU -D_GNU_SOURCE -DSSE_ENABLED=1 -DSSE3_ENABLED=1 -DSSE2_ENABLED=1 -DNDEBUG -D_THREAD_SAFE -D_PTHREADS -D_REENTRANT -D__LONG_LONG_SUPPORTED -Wall -W -Wno-parentheses -Wno-deprecated -fPIC -DCATBOOST_OPENSOURCE=yes -I/usr/local/cuda-9.0/include -nostdinc++ -DFAKEID=3638217 -DARCADIA_ROOT=/mnt/sdc1/home/gtrojan/Downloads/catboost-8.0.1 -DARCADIA_BUILD_ROOT=/home/gtrojan/.ya/build/build_root/tm83/000cce failed with exit code 1
     gcc: error: unrecognized command line option '--target=x86_64-linux-gnu'

Then I prepended */usr/local/gcc-6.4.0/bin* to *PATH*, without setting CC and CXX (that's how I built CUDA 9.X). Compilation started, I got 97.5% done, but failed on .cu files with tons of errors:

    command /home/gtrojan/.ya/tools/v3/173608153/python /mnt/sdc1/home/gtrojan/Downloads/catboost-6.4.0/build/scripts/compile_cuda.py /usr/local/cuda-9.0/bin/nvcc -std=c++14 -Xcompiler -fpermissive -gencode arch=compute_30,code=compute_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=compute_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=compute_60 -gencode arch=compute_61,code=compute_61 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_70,code=compute_70 -c /mnt/sdc1/home/gtrojan/Downloads/catboost-6.4.0/catboost/cuda/cuda_lib/kernel/arch.cu -o /home/gtrojan/.ya/build/build_root/t70t/000cd0/catboost/cuda/cuda_lib/kernel/arch.cu.obj -I/home/gtrojan/.ya/build/build_root/t70t/000cd0 -I/mnt/sdc1/home/gtrojan/Downloads/catboost-6.4.0 -I/mnt/sdc1/home/gtrojan/Downloads/catboost-6.4.0/contrib/libs/cxxsupp/libcxxrt -I/mnt/sdc1/home/gtrojan/Downloads/catboost-6.4.0/contrib/libs/cxxsupp/libcxx/include -I/mnt/sdc1/home/gtrojan/Downloads/catboost-6.4.0/contrib/libs/double-conversion/include -I/mnt/sdc1/home/gtrojan/Downloads/catboost-6.4.0/contrib/libs/libf2c --cflags --target=x86_64-linux-gnu -B$OS_SDK_ROOT_RESOURCE_GLOBAL/usr/bin -pipe -m64 -msse -msse3 -msse2 -O2 -Wno-inconsistent-missing-override -Wno-c++17-extensions -Wno-exceptions -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DGNU -D_GNU_SOURCE -DSSE_ENABLED=1 -DSSE3_ENABLED=1 -DSSE2_ENABLED=1 -DNDEBUG -D_THREAD_SAFE -D_PTHREADS -D_REENTRANT -D__LONG_LONG_SUPPORTED -Wall -W -Wno-parentheses -Wno-deprecated -fPIC -DCATBOOST_OPENSOURCE=yes -I/usr/local/cuda-9.0/include -nostdinc++ -DFAKEID=3638217 -DARCADIA_ROOT=/mnt/sdc1/home/gtrojan/Downloads/catboost-6.4.0 -DARCADIA_BUILD_ROOT=/home/gtrojan/.ya/build/build_root/t70t/000cd0 failed with exit code 1
    cc1plus: warning: command line option '-ftarget=x86_64-linux-gnu' is valid for Java but not for C++
    cc1plus: warning: unrecognized command line option '-Wno-exceptions'
    cc1plus: warning: unrecognized command line option '-Wno-inconsistent-missing-override'
    /mnt/sdc1/local/gcc-6.4.0/include/c++/6.4.0/stdlib.h(38): error: namespace "std" has no member "abort"

    /mnt/sdc1/local/gcc-6.4.0/include/c++/6.4.0/stdlib.h(39): error: namespace "std" has no member "atexit"

    /mnt/sdc1/local/gcc-6.4.0/include/c++/6.4.0/stdlib.h(40): error: namespace "std" has no member "exit"

    /mnt/sdc1/home/gtrojan/Downloads/catboost-6.4.0/contrib/libs/cxxsupp/libcxx/include/stdlib.h(119): error: identifier "labs" is undefined
    ...
    100 more lines.

Note that the argument *--target=x86_64-linux-gnu* is not valid for gcc 6.4 either, the compiler issues warning (both gcc and g++), but compiles successfully:

    [gtrojan@asok catboost]$ g++ --target=x86_64-linux-gnu foo.cc
    cc1plus: warning: command line option ‘-ftarget=x86_64-linux-gnu’ is valid for Java but not for C++

**Comment by dbakshee** [comment] 2018-06-19 16:33
@yt87, could you try if applying this patch helps:
```diff --git a/build/scripts/compile_cuda.py b/build/scripts/compile_cuda.py
index 239f19a..1689db9 100644
--- a/build/scripts/compile_cuda.py
+++ b/build/scripts/compile_cuda.py
@@ -53,6 +53,7 @@ def main():
         '-fsanitize-coverage=',
         '-fsanitize-blacklist=',
         '--system-header-prefix',
+        '--target',
     ]
     for prefix in skip_prefix_list:
         cflags = [i for i in cflags if not i.startswith(prefix)]```

**Comment by dbakshee** [comment] 2018-06-19 16:42
@ctlaltdefeat, you can specify the host compiler for nvcc using option `-DCUDA_NVCC_FLAGS`, like this:
```
python mk_wheel.py -DCUDA_ROOT=/usr/local/cuda-9.1 -DCUDA_NVCC_FLAGS='--compiler-bindir /home/dbakshee/gcc-8.1.0-install/bin'
```

**Comment by yt87** [comment] 2018-06-19 17:01
I did try your patch just after sending my previous message. It did help, but then *nvcc* balked: gcc versions above 6.x are not supported. I will try a work-around as described in   https://davidwpearson.wordpress.com/2017/12/21/installing-nvidias-cuda-9-1-on-fedora-27/
By the way, which cuda library should I use? There are conflicting answers by @noxoomo on  #372 (9.0) and #353 (9.1).

**Comment by Noxoomo** [comment] 2018-06-19 17:04
Hi!

1) You could use any version of CUDA >= 9.0 if you are building from source (9.0, 9.1, 9.2 currently)
2) Maybe it'll be simpler to use clang to build CatBoost

**Comment by yt87** [comment] 2018-06-19 17:11
9.2 supports gcc 7.3.1 for Fedora 27. Maybe it will accept 8.0 after header change.
I have no idea how to start with clang.

**Comment by Noxoomo** [comment] 2018-06-19 17:17
Try to  add --target-platform=CLANG50-LINUX-X86_64 args (compiler will be downloaded automatically)

**Comment by dbakshee** [comment] 2018-06-19 17:53
NVCC does  not support clang, afaik

**Comment by yt87** [comment] 2018-06-19 22:32
I just finished building _catboost.so without cuda. The logs and standard output shows clang was used for compilation. However, as you said, compile-cuda.py uses gcc (which fails on RH7.5, because compiler does not support  c++14). I think the problem is that the arguments passed to the script do not contain *--compiler-bindir* directive.

**Comment by dbakshee** [comment] 2018-06-20 10:45
It turned out that nvcc supports clang, e.g. cuda-9.2 [supports](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#system-requirements) clang 5. 
To tell nvcc what compiler to employ, give its full path using the same `--compiler-bindir` option, see [here](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#file-and-path-specifications). 
For example:
```
python mk_wheel.py -DCUDA_ROOT=/usr/local/cuda-9.1 -DCUDA_NVCC_FLAGS='--compiler-bindir clang++'
```

**Comment by yt87** [comment] 2018-06-20 14:55
But what is the path? @Noxoomo wrote that the compiler would be downloaded automatically. I do see clang50 in the build output:
    
    |99.9%| [LD] {clang50-linux-x86_64, pic} $(B)/catboost/python-package/catboost/Ok

however I could not find clang++ in ~/.ya. The log file has an entry:

    "name": "clang50", 
    "params": {
        "c_compiler": "$(DEFAULT_LINUX_X86_64)/bin/clang", 
        "cxx_compiler": "$(DEFAULT_LINUX_X86_64)/bin/clang++", 
        "gcc_version": "5.0", 
        "llvm-symbolizer": "$(DEFAULT_LINUX_X86_64)/bin/llvm-symbolizer", 
        "match_root": "DEFAULT_LINUX_X86_64", 
        "type": "clang", 
        "werror_mode": "all"
    },

**Comment by ctlaltdefeat** [comment] 2018-06-21 18:55
Compiling with clang 5 gives the same errors as using gcc 6.4.1 does.

**Comment by Paperone80** [comment] 2018-08-02 12:32
Hi, 
I had the same challenges in the beginning as well. I am on RHEL 7.5 with CUDA nvcc --version 9.0, V9.0.176 installed. I was able to build, wheel and run it in Python3.5 with the following steps below:

1. Build LLVM 3.8.0 (I tried 5.0.2 and 3.9.0 which didn't work for me).
2. Build Clang++ 3.8.0 (requires llvm-config built)
3. Build Catboost with GPU support
4. Build Catboost Wheel 
5. pip install *.whl
6.  in python: 
`import os`
`os.environ['CUDA_VISIBLE_DEVICES'] = '0'`
`import catboost.gpu._catboost`
`from catboost import CatBoost, CatBoostClassifier, CatBoostRegressor`
`catboost_params = {`
    `'devices': '0',`
    `'task_type': 'GPU',`
`... }`

NB: CUDA 9.0.176 supports Clang 3.9.0 as described here under 2.2.1 

> "CUDA now supports the Clang 3.9 LLVM-based C and C++ compilers as host compilers on Linux operating systems."

but I found in some other discussions that Yandex/Catboost actually seems to use Clang 3.8.0 internally. Hence, some of the errors which appear to be nvcc related are actually Catboost related, imho.

Here the steps in detail. Hope it helps to adapt them to individual environments:
**Build LLVM 3.8.0**
`$ sudo mkdir -p /opt/llvm/LLVM_3.8.0`
`$ cd /opt/llvm/LLVM_3.8.0`
`$ sudo wget http://releases.llvm.org/3.8.0/llvm-3.8.0.src.tar.xz`
`$ sudo tar -xf llvm-3.8.0.src.tar.xz`
`$ sudo mkdir build_llvm; cd build_llvm`
`$ sudo cmake3 -G "Unix Makefiles" ../llvm-3.8.0.src`
`$ sudo make -j32`
`$ cd ..`

**Build Clang 3.8.0**
`$ sudo wget http://releases.llvm.org/3.8.0/cfe-3.8.0.src.tar.xz  `
`$ sudo tar -xf cfe-3.8.0.src.tar.xz`
`$ sudo mkdir build_clang; cd build_clang`
`$ sudo cmake3 -G "Unix Makefiles" ../cfe-3.8.0.src -DLLVM_CONFIG=/opt/llvm/LLVM_3.8.0/buil_llvm/bin/llvm-config`
`$ sudo make -j32`

**Git Clone Catboost**
`$ su`
`$ mkdir -p /opt/catboost; cd /opt/catboost`
`$ git clone https://github.com/catboost/catboost.git`
`$ cd catboost/python-package/catboost`

**IMPORTANT** From here use root user instead of sudo, otherwise some env variables are not picked up correctly
`$ su` 
In the next step, notice -I (capital i) in -DPYTHON_INCLUDE=“-I/opt/intel/intelpython35/include/python3.5m”, without "-I/.../.." ya make might not find “Python.h”. Check that the folder contains **Python.h**.
Also set -DCUDA_NVCC_FLAGS="/../..." to your just built /../bin/clang++ path:
`$ ../../../ya make -r -v -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DPYTHON_CONFIG=/opt/intel/intelpython35/bin/python3-config -DCUDA_ROOT=/usr/local/cuda -DPYTHON_INCLUDE=“-I/opt/intel/intelpython35/include/python3.5m” -DPYTHON_LIBRARIES=/opt/intel/intelpython35/lib -DPYTHON_BIN=/opt/intel/intelpython35/bin -DCUDA_NVCC_FLAGS="--compiler-bindir /opt/llvm/LLVM_3.8.0/build_clang/bin/clang++"`
[…]
OK

In the meantime… when you see **PREPARING** wait for .ya-toolchain to load. You can check progress here: (v3 folder is quite big)
`$ cd /root/.ya/tools`
`$ du -chkh --max-depth=1`
102M	./a0495ce404_d
**1.8G	        ./v3**
2.0G	.
2.0G	total

**Build Wheel Package**
`$ cd /opt/catboost/catboost/python-package`
'$ ls'
you should see here 'mk_wheel.py'
`$ /opt/intel/intelpython35/bin/python3.5 mk_wheel.py -DPYTHON_INCLUDE="-I/opt/intel/intelpython35/include/python3.5m" -DPYTHON_LIBRARIES="/opt/intel/intelpython35/lib" -DCUDA_ROOT=/usr/local/cuda -DCUDA_NVCC_FLAGS="--compiler-bindir /opt/llvm/LLVM_3.8.0/build_clang/bin/clang++"`
Trying to build GPU version
[…]
Build GPU version: OK
Trying to build CPU version
[…]
Build CPU version: OK
`/opt/catboost/catboost/python-package/catboost-0.9.1.1-cp35-none-manylinux1_x86_64.whl`

**Install .whl into your python**
`$ cd /opt/catboost/catboost/python-package`
`$ /opt/intel/intelpython35/bin/pip install catboost-0.9.1.1-cp35-none-manylinux1_x86_64.whl`

Good luck and hope it works out for whoever sees with thread :) 

I've seen some 10x-20x speed-up with a TITAN X GPU compared to 32 CPU threads. 

@Yandex: Nice work and thanks to make Catboost open source. Hope you can use some of these steps to make your instructions easier for others :)

**Comment by annaveronika** [comment] 2018-08-13 17:02
This should be solved, please try pulling the latest version from github and building again.
I'm closing the issue, feel free to reopen, if something doesn't work for you.

**Closed by annaveronika** 2018-08-13 17:02 UTC
Labels: build issues

**Comment by lutel** [comment] 2018-09-30 14:46
Could you reopen this issue, as the catboost is not compiling with GCC, neither for 0.9.1.1 or 0.10.1,2.

**Comment by dbakshee** [comment] 2018-09-30 16:07
Hi @lutel 
Feel free to open a new issue, describing what you are trying to accomplish and what fails.
