### ISSUE TITLE
R catboost.train error: library/json/writer/json_value.cpp:499: Not a map

### ISSUE THREAD

**Issue by talegari** [catboost/catboost#1162] opened 2020-01-27 04:28 UTC
----

Problem: Calling `catboost.train` results in error: `library/json/writer/json_value.cpp:499: Not a map`
catboost version: 0.20.2
Operating System: macOS mojave
CPU: Yes
GPU: No

----

Here is a simple reproducible example:

``` r
library("tidyverse")
library("modeldata")
library("catboost")
packageVersion("catboost")
#> [1] '0.20.2'
data("attrition", package = "modeldata")
attrition = as_tibble(attrition)
glimpse(attrition)
#> Observations: 1,470
#> Variables: 31
#> $ Age                      <int> 41, 49, 37, 33, 27, 32, 59, 30, 38, 36, 35, …
#> $ Attrition                <fct> Yes, No, Yes, No, No, No, No, No, No, No, No…
#> $ BusinessTravel           <fct> Travel_Rarely, Travel_Frequently, Travel_Rar…
#> $ DailyRate                <int> 1102, 279, 1373, 1392, 591, 1005, 1324, 1358…
#> $ Department               <fct> Sales, Research_Development, Research_Develo…
#> $ DistanceFromHome         <int> 1, 8, 2, 3, 2, 2, 3, 24, 23, 27, 16, 15, 26,…
#> $ Education                <ord> College, Below_College, College, Master, Bel…
#> $ EducationField           <fct> Life_Sciences, Life_Sciences, Other, Life_Sc…
#> $ EnvironmentSatisfaction  <ord> Medium, High, Very_High, Very_High, Low, Ver…
#> $ Gender                   <fct> Female, Male, Male, Female, Male, Male, Fema…
#> $ HourlyRate               <int> 94, 61, 92, 56, 40, 79, 81, 67, 44, 94, 84, …
#> $ JobInvolvement           <ord> High, Medium, Medium, High, High, High, Very…
#> $ JobLevel                 <int> 2, 2, 1, 1, 1, 1, 1, 1, 3, 2, 1, 2, 1, 1, 1,…
#> $ JobRole                  <fct> Sales_Executive, Research_Scientist, Laborat…
#> $ JobSatisfaction          <ord> Very_High, Medium, High, High, Medium, Very_…
#> $ MaritalStatus            <fct> Single, Married, Single, Married, Married, S…
#> $ MonthlyIncome            <int> 5993, 5130, 2090, 2909, 3468, 3068, 2670, 26…
#> $ MonthlyRate              <int> 19479, 24907, 2396, 23159, 16632, 11864, 996…
#> $ NumCompaniesWorked       <int> 8, 1, 6, 1, 9, 0, 4, 1, 0, 6, 0, 0, 1, 0, 5,…
#> $ OverTime                 <fct> Yes, No, Yes, Yes, No, No, Yes, No, No, No, …
#> $ PercentSalaryHike        <int> 11, 23, 15, 11, 12, 13, 20, 22, 21, 13, 13, …
#> $ PerformanceRating        <ord> Excellent, Outstanding, Excellent, Excellent…
#> $ RelationshipSatisfaction <ord> Low, Very_High, Medium, High, Very_High, Hig…
#> $ StockOptionLevel         <int> 0, 1, 0, 0, 1, 0, 3, 1, 0, 2, 1, 0, 1, 1, 0,…
#> $ TotalWorkingYears        <int> 8, 10, 7, 8, 6, 8, 12, 1, 10, 17, 6, 10, 5, …
#> $ TrainingTimesLastYear    <int> 0, 3, 3, 3, 3, 2, 3, 2, 2, 3, 5, 3, 1, 2, 4,…
#> $ WorkLifeBalance          <ord> Bad, Better, Better, Better, Better, Good, G…
#> $ YearsAtCompany           <int> 6, 10, 0, 8, 2, 7, 1, 1, 9, 7, 5, 9, 5, 2, 4…
#> $ YearsInCurrentRole       <int> 4, 7, 0, 7, 2, 7, 0, 0, 7, 7, 4, 5, 2, 2, 2,…
#> $ YearsSinceLastPromotion  <int> 0, 1, 0, 3, 2, 3, 0, 0, 1, 7, 0, 0, 4, 1, 0,…
#> $ YearsWithCurrManager     <int> 5, 7, 0, 0, 2, 6, 0, 0, 8, 7, 3, 8, 3, 2, 3,…

catpool = catboost.load_pool(data = attrition %>% select(-Attrition)
                             , label = as.integer(unclass(attrition$Attrition) - 1L)
                             )
catboost.train(catpool)
#> Training catboost with default parameters! See help(catboost.train).
#> Error in catboost.train(catpool): library/json/writer/json_value.cpp:499: Not a map
```

**Comment by annaveronika** [comment] 2020-01-27 10:26
Thanks for the issue, we'll look into this.

**Comment by stasaki** [comment] 2020-01-30 19:00
The same issue on Ubuntu 18.04 LTS without GPUs.

**Comment by grag90** [comment] 2020-01-31 13:59
The problem was fixed by this [commit](https://github.com/catboost/catboost/commit/af432f04ac2af926dc9d1729cf99c5f98caf8ec6). Next release 0.21 will include it. Thank you very much for reporting the bug.

**Comment by saianil58** [comment] 2020-04-25 21:25
same issue reproduced on python,

   3104                 param_grid, train_params["train_pool"], params, n_iter,
   3105                 fold_count, partition_random_seed, shuffle, stratified, train_size,
-> 3106                 search_by_train_test_split, calc_cv_statistics, custom_folds, verbose
   3107             )
   3108 

_catboost.pyx in _catboost._CatBoost._tune_hyperparams()

_catboost.pyx in _catboost._CatBoost._tune_hyperparams()

CatBoostError: library/json/writer/json_value.cpp:499: Not a map

**Comment by BeomyoungKim** [comment] 2020-05-28 01:34
same here on python too

**Comment by rubzk** [comment] 2020-06-05 19:20
same problem using gpu

`Estimating final quality...

---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
<ipython-input-82-d7523abe13a8> in <module>
----> 1 gs= model.grid_search(grid, X=pool_train,plot=False, cv=3)

~/anaconda3/lib/python3.7/site-packages/catboost/core.py in grid_search(self, param_grid, X, y, cv, partition_random_seed, calc_cv_statistics, search_by_train_test_split, refit, shuffle, stratified, train_size, verbose, plot)
   3203             partition_random_seed=partition_random_seed, calc_cv_statistics=calc_cv_statistics,
   3204             search_by_train_test_split=search_by_train_test_split, refit=refit, shuffle=shuffle,
-> 3205             stratified=stratified, train_size=train_size, verbose=verbose, plot=plot
   3206         )
   3207 

~/anaconda3/lib/python3.7/site-packages/catboost/core.py in _tune_hyperparams(self, param_grid, X, y, cv, n_iter, partition_random_seed, calc_cv_statistics, search_by_train_test_split, refit, shuffle, stratified, train_size, verbose, plot)
   3104                 param_grid, train_params["train_pool"], params, n_iter,
   3105                 fold_count, partition_random_seed, shuffle, stratified, train_size,
-> 3106                 search_by_train_test_split, calc_cv_statistics, custom_folds, verbose
   3107             )
   3108 

_catboost.pyx in _catboost._CatBoost._tune_hyperparams()

_catboost.pyx in _catboost._CatBoost._tune_hyperparams()

CatBoostError: library/json/writer/json_value.cpp:499: Not a map

`

**Comment by kaanbayraktar** [comment] 2020-07-02 12:19
I had the same issue in grid search, in my case I tried more depth than 16. So setting it as upper boundary solved the problem.

**Comment by isaacgg** [comment] 2021-02-10 21:08
Hi, sorry for reopening this, but I still have this issue in version 0.24.3.

This is what I'm trying:
`grid_search_params = {'depth':[1,2,3,6,4,5,7,8,9,10],
          'iterations':[250,100,500,1000],
          'learning_rate':[0.03,0.001,0.01,0.1,0.2,0.3], 
          'l2_leaf_reg':[3,1,5,10,100],
          'border_count':[32,5,10,20,50,100,200],
          'ctr_border_count':[50,5,10,20,100,200]}`

`model_train = CatBoostRegressor()
grid_search_results = model_train.grid_search(grid_search_params, X=pd.concat([X_train, X_val]), y=pd.concat([y_train, y_val]))`

**Comment by brunocous** [comment] 2021-04-29 07:08
This issue should be re-opened. This is still an issue in 0.24.4.

My code that failed:
````python
model = CatBoostRegressor(
        iterations=500,
        early_stopping_rounds=4,
        objective="Quantile:alpha=0.7",
        nan_mode="Min",
    )

    grid = {
        "learning_rate": [
            0.1,
            0.15,
            0.2,
            0.3,
            0.4,
            0.6,
        ],
        "depth": [4, 6, 10],
        "l2_leaf_reg": [0.5, 1, 3, 5, 7, 9],
        "random_strength": [0.8, 1.2, 2.0, 3.0, 5.0, 6.0],
        "grow_policy": ["SymmetricTree", "Depthwise", "Lossguide"],
        "border_count": [16, 32, 64, 128],
        "ctr_border_count": [16, 32, 64, 128, 255],
    }

    randomized_search_result = model.randomized_search(
        grid,
        X=all_pool,
        refit=True,
        shuffle=False,
        n_iter=30,
    )
````

**Comment by kizill** [comment] 2021-07-12 11:48
We've tried to reproduce this problem in `R 4.0.5` and `CatBoost 0.26` and now this code returns proper error message:
```
_catboost.CatBoostError: catboost/private/libs/hyperparameter_tuning/hyperparameter_tuning.cpp:1145:
All params in grid were invalid, last error message:
catboost/private/libs/options/plain_options_helper.cpp:501:
Unknown option {ctr_border_count} with value "255"
```
Now CatBoost uses two different parameters for setting CTR parameters: `simple_ctr` and `combinations_ctr` and you should set up `CtrBorderCount` for each CTR type. For example `simple_ctr=['Borders:CtrBorderCount=50']`

Look at python training options description https://catboost.ai/docs/concepts/python-reference_parameters-list.html

**Closed by kizill** 2021-07-12 11:48 UTC
Labels: R, in progress
