### ISSUE TITLE
Custom metrics in GPU training

### ISSUE THREAD

**Issue by annaveronika** [catboost/catboost#736] opened 2019-03-21 10:52 UTC

**Comment by StatMixedML** [comment] 2020-01-02 15:49
Any update on this? Would be great to have GPU support for custom evaluation metric

**Comment by annaveronika** [comment] 2020-01-14 09:03
No progress on that. But I suggest to use eval_metrics method or staged_predict method to calculate the custom loss after the training has finished.

**Comment by andrey-khropov** [comment] 2024-03-03 16:34
Duplicate of #1792 (closing this issue because that issue has more activity).

**Closed by andrey-khropov** 2024-03-03 16:34 UTC
Labels: GPU, feature request

**Comment by andrey-khropov** [comment] 2025-04-19 10:50
#1792 is about callbacks. User-defined objectives and losses have been implemented in https://github.com/catboost/catboost/commit/14ef09c08cddbf72c1d3e121239140c36eaffe4d.
