### ISSUE TITLE
do you have tutorial with code and video what works on Windows?

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#746] opened 2019-03-26 20:57 UTC
Problem: {
do you have tutorial with code and video what works on Windows?
tutorial is not working on windows
I try to run tutorial 
https://github.com/catboost/tutorials/blob/master/classification/classification_tutorial.ipynb

but get error
![image](https://user-images.githubusercontent.com/11426119/55032745-fa7c4a80-4fe7-11e9-9a68-31294e85b4e2.png)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-5b7641cca5ad> in <module>()
     20         cat_feature_names=list(X)
     21     ),
---> 22     label=y.values
     23 )
     24 

~\Anaconda3\lib\site-packages\catboost\core.py in __init__(self, data, label, cat_features, column_description, pairs, delimiter, has_header, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    293                         )
    294 
--> 295                 self._init(data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
    296         super(Pool, self).__init__()
    297 

~\Anaconda3\lib\site-packages\catboost\core.py in _init(self, data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
    637         if feature_names is not None:
    638             self._check_feature_names(feature_names, features_count)
--> 639         self._init_pool(data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
    640 
    641 

_catboost.pyx in _catboost._PoolBase._init_pool()

_catboost.pyx in _catboost._PoolBase._init_pool()

_catboost.pyx in _catboost._PoolBase._set_data_and_feature_names()

_catboost.pyx in _catboost._PoolBase._set_data_np()

TypeError: Expected bytes, got str

}
catboost version: {version}
Operating System: {windows}
CPU: {CPU}
# GPU: {GPU}

**Comment by Sandy4321** [comment] 2019-03-26 21:05
import catboost
print(catboost.__version__)
!python --version
0.9.1.1
Python 3.6.7

**Comment by Sandy4321** [comment] 2019-03-26 21:06
I commented pool4 related code , but now have anther error
![image](https://user-images.githubusercontent.com/11426119/55033397-77f48a80-4fe9-11e9-92f4-9839b4eae98a.png)

**Comment by Sandy4321** [comment] 2019-03-26 21:08
but there is such a method
![image](https://user-images.githubusercontent.com/11426119/55033552-d15cb980-4fe9-11e9-9309-14055987e71a.png)

**Comment by Sandy4321** [comment] 2019-03-26 21:10
commented this line and all works
![image](https://user-images.githubusercontent.com/11426119/55033665-09fc9300-4fea-11e9-9450-7fdd5810fbfb.png)

**Comment by Sandy4321** [comment] 2019-03-26 21:24
another error
![image](https://user-images.githubusercontent.com/11426119/55034411-cdca3200-4feb-11e9-8e70-00ef9bece2a2.png)
though get_roc_curve is valid 
![image](https://user-images.githubusercontent.com/11426119/55034462-e1759880-4feb-11e9-823d-5562669f058b.png)

**Comment by Sandy4321** [comment] 2019-03-26 21:26
catboost was installed by
conda install catboost
per
![image](https://user-images.githubusercontent.com/11426119/55034630-4204d580-4fec-11e9-9172-6f0b2c49ba5c.png)

**Comment by Sandy4321** [comment] 2019-03-26 21:41
one more error
ImportError: cannot import name 'get_fpr_curve'
![image](https://user-images.githubusercontent.com/11426119/55035428-5518a500-4fee-11e9-91c9-83fc2afff7b1.png)

**Comment by Sandy4321** [comment] 2019-03-26 21:43
one more error
![image](https://user-images.githubusercontent.com/11426119/55035538-990baa00-4fee-11e9-93d5-167075a74122.png)
ImportError: cannot import name 'select_threshold'

**Comment by Sandy4321** [comment] 2019-03-26 21:45
another error
TypeError: __init__() got an unexpected keyword argument 'snapshot_interval'
![image](https://user-images.githubusercontent.com/11426119/55035653-dcfeaf00-4fee-11e9-8ff2-302745592a9a.png)

**Comment by Sandy4321** [comment] 2019-03-26 21:48
another error
![image](https://user-images.githubusercontent.com/11426119/55035788-3cf55580-4fef-11e9-9f1d-4e36454e4ff8.png)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-48-f6e51075722f> in <module>()
      5     data=FeaturesData(
      6         cat_feature_data=X_prepared,
----> 7         cat_feature_names=list(X_validation)
      8     )
      9 )

~\Anaconda3\lib\site-packages\catboost\core.py in predict_proba(self, data, ntree_start, ntree_end, thread_count, verbose)
   2123         prediction : numpy.array
   2124         """
-> 2125         return self._predict(data, 'Probability', ntree_start, ntree_end, thread_count, verbose)
   2126 
   2127     def staged_predict(self, data, prediction_type='Class', ntree_start=0, ntree_end=0, eval_period=1, thread_count=-1, verbose=None):

~\Anaconda3\lib\site-packages\catboost\core.py in _predict(self, data, prediction_type, ntree_start, ntree_end, thread_count, verbose)
   1192             data = Pool(
   1193                 data=data,
-> 1194                 cat_features=self._get_cat_feature_indices() if not isinstance(data, FeaturesData) else None
   1195             )
   1196         elif not np.all(set(self._get_cat_feature_indices()).issubset(data.get_cat_feature_indices())):

~\Anaconda3\lib\site-packages\catboost\core.py in __init__(self, data, label, cat_features, column_description, pairs, delimiter, has_header, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    293                         )
    294 
--> 295                 self._init(data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
    296         super(Pool, self).__init__()
    297 

~\Anaconda3\lib\site-packages\catboost\core.py in _init(self, data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
    637         if feature_names is not None:
    638             self._check_feature_names(feature_names, features_count)
--> 639         self._init_pool(data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
    640 
    641 

_catboost.pyx in _catboost._PoolBase._init_pool()

_catboost.pyx in _catboost._PoolBase._init_pool()

_catboost.pyx in _catboost._PoolBase._set_data_and_feature_names()

_catboost.pyx in _catboost._PoolBase._set_data_np()

TypeError: Expected bytes, got str

**Comment by Sandy4321** [comment] 2019-03-26 21:58
one more error
CatboostError: Unknown model type json.
in ----> 9 my_best_model.save_model('catboost_model.json', format='json')

![image](https://user-images.githubusercontent.com/11426119/55036327-aaee4c80-4ff0-11e9-85ac-3e334360907d.png)

**Comment by annaveronika** [comment] 2019-03-26 22:11
Please update to the latest version of catboost

**Comment by david-waterworth** [comment] 2019-03-26 23:49
@Sandy4321 I think the issue is you're using conda and it's not installing the latest version for whatever reason. I don't actually use conda, I prefer to use ``pyenv`` and ``pyenv-virtualenv``, with pip.

I would suggest reading https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html

Then maybe try

`conda update catboost`

or

`conda install catboost==0.13.1`

**Comment by Sandy4321** [comment] 2019-03-26 23:52
but if pip stable better to use pip
as you wrote 
pip install --upgrade catboost
but how in proper way to uninstall catboost installed by conda?

**Comment by Sandy4321** [comment] 2019-03-26 23:55
is 
conda remove catboost
good enough as written in 
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#removing-packages

**Comment by david-waterworth** [comment] 2019-03-27 00:00
I'm not sure sorry, I'm not really familiar with conda. That should work.

I wonder if conda thinks 0.9.1.1 > 0.13.1, it shouldn't but I don't really know how it works.

**Comment by Sandy4321** [comment] 2019-03-27 00:04
done
but features selection will not work as written in issue before?

**Comment by david-waterworth** [comment] 2019-03-27 00:09
yes it appears so, if you need that feature I'd recommend rolling back to say 0.12.2?

**Comment by annaveronika** [comment] 2019-04-04 18:46
This particular issue should be resolved by updating the version - I don't think there is any problem on catboost side. As for feature importances - there is another issue about that. Thus closing the issue.

**Closed by annaveronika** 2019-04-04 18:46 UTC
