### ISSUE TITLE
Python Kernel crash with custom eval metrics

### ISSUE THREAD

**Issue by Joe-Khawand** [catboost/catboost#2492] opened 2023-09-11 13:24 UTC
Problem: The kernel crashes while using custom eval metrics. It happens with all eval metrics even already implemented ones if you use the `eval_metric` in the `CatBoostRegressor`.

catboost version: 1.2.1
Operating System: Apple M1 pro Ventura 13.5.2
CPU: yes
GPU: no gpu

```python
import numpy as np
import pandas as pd

from scipy.stats import spearmanr
import matplotlib.pyplot as plt

from catboost import CatBoostRegressor

from sklearn.model_selection import train_test_split

class CatBoostEvalMetricPearson(object):
    def is_max_optimal(self):
        return True

    def evaluate(self, approxes, target, weight):
        assert len(approxes) == 1
        assert len(target) == len(approxes[0])
        preds = np.array(approxes[0])
        target = np.array(target)
        return pearson_correlation_metric(preds,target), 0

    def get_final_error(self, error, weight):
        # Returns final value of metric based on error and weight
        return error

def pearson_correlation_metric(preds, true_labels):
    return spearmanr(preds, true_labels).correlation

####Train functions####

cat_fr= CatBoostRegressor(learning_rate=0.025,eval_metric=CatBoostEvalMetricPearson())

X_train_final_FR, X_validation_final_FR, y_train_final_FR, y_validation_final_FR = train_test_split(X_train_FR, Y_train_FR_clean, train_size=0.75, random_state=42)

cat_fr.fit(X_train_final_FR, y_train_final_FR,eval_set=(X_validation_final_FR,y_validation_final_FR),plot=True)
```

With this setup the kernel crashes directly on running and gives out a **Segmentation Fault**.

---
**NOTE**

Downgrading to catboost=1.2.0 fixed the problem.

---

**Comment by andrey-khropov** [comment] 2023-09-11 21:10
Duplicate of #2486

**Closed by andrey-khropov** 2023-09-11 21:10 UTC
Labels: duplicate
