### ISSUE TITLE
configure looks for EOLed Python2

### ISSUE THREAD

**Issue by yurivict** [catboost/catboost#2326] opened 2023-03-16 17:49 UTC
```
CMake Error at /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python2 (missing: Python2_EXECUTABLE Interpreter)
Call Stack (most recent call first):
  /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake/Modules/FindPython/Support.cmake:3245 (find_package_handle_standard_args)
  /usr/local/share/cmake/Modules/FindPython2.cmake:427 (include)
  cmake/yandex_common.cmake:3 (find_package)
  CMakeLists.txt:32 (include)
```

**Comment by andrey-khropov** [comment] 2023-03-16 20:54
What revision do you try to build from? 

There were some bugs that led to erroneous Python2 dependency but they have been fixed in commit https://github.com/catboost/catboost/commit/7d17950e3fc3b9bd8df1f7618cf26c84f8645732. Do you try to build from some commit after that?

**Comment by yurivict** [comment] 2023-03-16 21:21
[v1.1.1](https://github.com/catboost/catboost/releases/tag/v1.1.1)

**Comment by andrey-khropov** [comment] 2023-03-16 21:38
> [v1.1.1](https://github.com/catboost/catboost/releases/tag/v1.1.1)

CMake build on v1.1.1 had been in the preliminary stage and had many issues, release artifacts for v1.1.1 were build using `ya make`. Please wait for release 1.2 for stable CMake build. Issues with CMake-based build are the primary reason of its delay.

**Comment by andrey-khropov** [comment] 2023-03-16 21:39
Duplicate of #2297

**Closed by andrey-khropov** 2023-03-16 21:39 UTC
Labels: build issues
