### ISSUE TITLE
Catboost is unable to get features importance when shap explainer is used

### ISSUE THREAD

**Issue by victorbartel** [catboost/catboost#1216] opened 2020-03-11 16:46 UTC
Problem: CatBoostError: catboost/libs/fstr/shap_values.cpp:810: Cannot calc shap values, model contains non zero approx for zero-weight leaf
catboost version: 0.22
Operating System: Ubuntu 19.10
CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz

Greetings,

I get above described error when I'm trying to visualize model features importance per prediction request(I'm using `CatBootRegressor`) with shap. I'm doing nothing spectacular, my code is strongly inspired by your notebooks.
```python
test_df = pd.read_csv(_TEST_PATH)
y_test = test_df.price
x_test = test_df.drop('price', axis=1)
model = CatBoostRegressor().load_model(_MODEL_PATH)

explainer = shap.TreeExplainer(model)

test_pool = Pool(x_test, y_test, cat_features=my_cat_features)

shap_values = explainer.shap_values(test_pool) #<-- this line throws the exception 
```

Here is the stack trace:

```
---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
<ipython-input-24-417533ac49d4> in <module>
----> 1 shap_values = explainer.shap_values(test_pool)
      2 # shap.summary_plot(shap_values, x_test)

~/anaconda3/lib/python3.7/site-packages/shap/explainers/tree.py in shap_values(self, X, y, tree_limit, approximate, check_additivity)
    245                 if type(X) != catboost.Pool:
    246                     X = catboost.Pool(X)
--> 247                 phi = self.model.original_model.get_feature_importance(data=X, fstr_type='ShapValues')
    248 
    249             # note we pull off the last column and keep it as our expected_value

~/anaconda3/lib/python3.7/site-packages/catboost/core.py in get_feature_importance(self, data, type, prettified, thread_count, verbose, fstr_type, shap_mode)
   2363 
   2364         with log_fixup():
-> 2365             fstr, feature_names = self._calc_fstr(type, data, thread_count, verbose, shap_mode)
   2366         if type in (EFstrType.PredictionValuesChange, EFstrType.LossFunctionChange, EFstrType.PredictionDiff):
   2367             feature_importances = [value[0] for value in fstr]

~/anaconda3/lib/python3.7/site-packages/catboost/core.py in _calc_fstr(self, type, pool, thread_count, verbose, shap_mode)
   1315 
   1316     def _calc_fstr(self, type, pool, thread_count, verbose, shap_mode):
-> 1317         return self._object._calc_fstr(type.name, pool, thread_count, verbose, shap_mode)
   1318 
   1319     def _calc_ostr(self, train_pool, test_pool, top_size, ostr_type, update_method, importance_values_sign, thread_count, verbose):

_catboost.pyx in _catboost._CatBoost._calc_fstr()

_catboost.pyx in _catboost._CatBoost._calc_fstr()

CatBoostError: catboost/libs/fstr/shap_values.cpp:810: Cannot calc shap values, model contains non zero approx for zero-weight leaf
```

Many thanks for your help.

**Comment by ek-ak** [comment] 2020-03-12 07:48
Hi! Could you provide params of this model?

**Comment by victorbartel** [comment] 2020-03-12 08:23
Hi, 

Sure. I forgot to say that model(and its training configuration) worked well with shap before. I've split the dataset in order to reduce the size of obtained model. Maybe it's just a coincidence, but now model ends up with the overfit (it's the only changing I've noticed compared to the previous cases).

Here is my configuration:
```python
CatBoostRegressor(iterations=40_000,
                             learning_rate=.1,
                             eval_metric='RMSE',
                             custom_metric=['MAE', 'RMSE', 'R2'],
                             random_seed=seed,
                             bagging_temperature=0.2,
                             od_type='Iter',
                             od_wait=100,
                             )
```
It provides an output as followed:
```
5800:	learn: 16304.8641043	test: 21757.9941404	best: 21755.9861662 (5711)	total: 5m 37s	remaining: 33m 12s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 21755.98617
bestIteration = 5711

Shrink model to first 5712 iterations.
Best score {'learn': {'MAE': 12725.101064829838, 'R2': 0.9439067100274073, 'RMSE': 16299.789300500823}, 'validation': {'MAE': 16585.54240834275, 'R2': 0.9006343801636487, 'RMSE': 21755.98616620314}}
```

**Comment by victorbartel** [comment] 2020-03-13 08:23
Hi,

I've sorted out my issue by removing `bagging_temperature=0.2` parameters, I think the default one should be around 1.0. I'm not sure to figure out(completely) what the true origin of this issue was.

**Comment by Lomdjaria1** [comment] 2020-04-10 11:54
Hi! I received the same error for such model:

{'nan_mode': 'Min',
 'eval_metric': 'MAE',
 'combinations_ctr': ['Borders:CtrBorderCount=15:CtrBorderType=Uniform:TargetBorderCount=1:TargetBorderType=MinEntropy:Prior=0/1:Prior=0.5/1:Prior=1/1',
  'Counter:CtrBorderCount=15:CtrBorderType=Uniform:Prior=0/1'],
 'iterations': 1000,
 'sampling_frequency': 'PerTree',
 'fold_permutation_block': 0,
 'leaf_estimation_method': 'Exact',
 'counter_calc_method': 'SkipTest',
 'grow_policy': 'SymmetricTree',
 'boosting_type': 'Plain',
 'model_shrink_mode': 'Constant',
 'feature_border_type': 'GreedyLogSum',
 'ctr_leaf_count_limit': 18446744073709551615,
 'bayesian_matrix_reg': 0.10000000149011612,
 'one_hot_max_size': 2,
 'l2_leaf_reg': 300,
 'random_strength': 9.999999747378752e-05,
 'rsm': 1,
 'boost_from_average': True,
 'max_ctr_complexity': 4,
 'model_size_reg': 0.5,
 'simple_ctr': ['Borders:CtrBorderCount=15:CtrBorderType=Uniform:TargetBorderCount=1:TargetBorderType=MinEntropy:Prior=0/1:Prior=0.5/1:Prior=1/1',
  'Counter:CtrBorderCount=15:CtrBorderType=Uniform:Prior=0/1'],
 'subsample': 0.800000011920929,
 'use_best_model': True,
 'random_seed': 17,
 'depth': 12,
 'ctr_target_border_count': 1,
 'has_time': False,
 'store_all_simple_ctr': False,
 'border_count': 254,
 'classes_count': 0,
 'sparse_features_conflict_fraction': 0,
 'leaf_estimation_backtracking': 'AnyImprovement',
 'best_model_min_trees': 1,
 'model_shrink_rate': 0,
 'min_data_in_leaf': 1,
 'loss_function': 'MAE',
 'learning_rate': 0.2540000081062317,
 'score_function': 'Cosine',
 'task_type': 'CPU',
 'leaf_estimation_iterations': 1,
 'bootstrap_type': 'MVS',
 'max_leaves': 4096,
 'permutation_count': 4}

**Comment by pplonski** [comment] 2020-04-29 16:24
I'm working on [AutoML package](https://github.com/mljar/mljar-supervised) and have the same issue.

The problem is when `loss_function` is `MAE`. 

The code to reproduce the problem:

```python
import numpy as np
import shap
from catboost import CatBoostRegressor
X = np.random.rand(100,10) 
y = np.random.randint(0,10, 100)
model = CatBoostRegressor(loss_function="MAE")
model.fit(X, y)
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X)
```

Error:
```python
---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
<ipython-input-40-f764a88bbadf> in <module>
----> 1 shap_values = explainer.shap_values(X)

~/Downloads/numerai_datasets/venv/lib/python3.6/site-packages/shap/explainers/tree.py in shap_values(self, X, y, tree_limit, approximate, check_additivity)
    262                 if type(X) != catboost.Pool:
    263                     X = catboost.Pool(X, cat_features=self.model.cat_feature_indices)
--> 264                 phi = self.model.original_model.get_feature_importance(data=X, fstr_type='ShapValues')
    265 
    266             # note we pull off the last column and keep it as our expected_value

~/Downloads/numerai_datasets/venv/lib/python3.6/site-packages/catboost/core.py in get_feature_importance(self, data, type, prettified, thread_count, verbose, fstr_type, shap_mode, interaction_indices, shap_calc_type)
   2364         with log_fixup():
   2365             fstr, feature_names = self._calc_fstr(type, data, thread_count, verbose, shap_mode, interaction_indices,
-> 2366                                                   shap_calc_type)
   2367         if type in (EFstrType.PredictionValuesChange, EFstrType.LossFunctionChange, EFstrType.PredictionDiff):
   2368             feature_importances = [value[0] for value in fstr]

~/Downloads/numerai_datasets/venv/lib/python3.6/site-packages/catboost/core.py in _calc_fstr(self, type, pool, thread_count, verbose, shap_mode, interaction_indices, shap_calc_type)
   1290     def _calc_fstr(self, type, pool, thread_count, verbose, shap_mode, interaction_indices, shap_calc_type):
   1291         return self._object._calc_fstr(type.name, pool, thread_count, verbose, shap_mode, interaction_indices,
-> 1292                                        shap_calc_type)
   1293 
   1294     def _calc_ostr(self, train_pool, test_pool, top_size, ostr_type, update_method, importance_values_sign, thread_count, verbose):

_catboost.pyx in _catboost._CatBoost._calc_fstr()

_catboost.pyx in _catboost._CatBoost._calc_fstr()

CatBoostError: catboost/libs/fstr/util.cpp:102: Cannot calc shap values, model contains non zero approx for zero-weight leaf
```

The problem is in version `0.23`. I tested on older version(`0.15.1`) and it was working.

**Comment by annaveronika** [comment] 2020-04-29 16:27
We are working on the fix right now, it'll be out in the next minor release.

**Comment by ek-ak** [comment] 2020-04-30 13:38
Hello! Thank your for reporting a bug! There was a problem with shap calculation for models with  ranking objectives, Quantile and MAE  loss_functions. In older version there was no error, but was a bug in shap values results. The fix is in code and will be out in the next release. For now you could build from source to overcome the problem. Thanks again for reporting it!

**Closed** 2020-04-30 13:53 UTC
