### ISSUE TITLE
Cannot convert to float

### ISSUE THREAD

**Issue by anthonymakela** [catboost/catboost#934] opened 2019-08-01 12:44 UTC
Hi! There seems to be a problem with converting to strings. Im getting the following error when trying to create a Pool.

`CatBoostError: Bad value for num_feature[0,0]="Vantaa": Cannot convert 'b'Vantaa'' to float
`

What might be the cause of this?

catboost version: 0.16.1
Operating System: Ubuntu 16.04

**Comment by annaveronika** [comment] 2019-08-01 14:11
By default all features are considered numerical. You need to specify categorical features in cat_features parameter.

**Comment by anthonymakela** [comment] 2019-08-01 15:43
Apologies @annaveronika  for bad communication, i was in a bit of a hurry. Im passing the correct categorical features to cat_features.

`categorical_features_indices = np.where(X.dtypes != np.float)[0]`
`train_pool = Pool(X_train, y_train, cat_features=categorical_features_indices)`

I've tried this several different ways passing the indices and the column names without luck. All the categorical feats are of an dtype "object".

**Comment by annaveronika** [comment] 2019-08-02 13:57
Maybe your X and X_train matrices have different column types.
Could you please provide a minimal reproducing example? And I suggest looking on the first line of your X_train, find the column with value 'Vantaa' and check that this column is declared as categorical.

**Comment by anthonymakela** [comment] 2019-08-06 09:55
@annaveronika  The dtypes of both X and X_train are the same. The column with value 'Vantaa' is also of an dtype 'object'. The same problem persists even when dropping the column that had value 'Vantaa' outputting this:

`CatBoostError: Bad value for num_feature[0,6]="Oma": Cannot convert 'b'Oma'' to float`

This seems to be happening only for columns that are strings and dtype of an 'object'.

**Comment by annaveronika** [comment] 2019-08-06 10:07
Could you please check that categorical_features_indices contains columns that you want to make categorical? In particular that it contains 0 and 6, which have string values.

**Comment by anthonymakela** [comment] 2019-08-06 10:11
Here are the indices:

`array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14])`

And here is the dtypes (i removed colnames for privacy reasons):

```
X_train.dtypes

object
object
object
float64
object
object
object
object
object
object
float64
object
object
object
object

dtype: object
```

**Comment by shubham-samant** [comment] 2019-08-29 12:56
hi, i am also facing the exact same issue, where in even removing that particular column, results in some value from other leading to the same error

**Comment by BackDraft647** [comment] 2019-09-02 12:34
Exact same problem here as well. It seems the auto-encoding is not working anymore. The same problem was corrected in the past and could be solved by downgrading pandas. Could this be a related issue ?

**Comment by annaveronika** [comment] 2019-10-18 14:04
Could you please provide a minimal reproducing example?

**Comment by annaveronika** [comment] 2019-10-18 14:06
Actually I think it should be the same as https://github.com/catboost/catboost/issues/958
In this case it should be fixed now.

Please check that it works with the latest catboost version!

**Comment by annaveronika** [comment] 2019-10-18 14:07
I'm closing the issue as fixed. If you still have a problem, let us know, I'll reopen it back.

**Closed by annaveronika** 2019-10-18 14:07 UTC
Labels: need info

**Comment by gitclem** [comment] 2020-08-05 21:07
I got this (same?) error:
CatBoostError: Bad value for num_feature[non_default_doc_idx=0,feature_idx=4]="meanScore": Cannot convert 'b'meanScore'' to float

I'm wondering if the problem is due to a meanScore having the value of NaN?  (I do have a lot of NaN values which are in place where the data is missing.)

I do see in FAQ https://catboost.ai/docs/concepts/input-data_custom-borders.html that there is a choice of Min,Max,Forbidden.  In my case, it's really the data is missing.

**Comment by khaled-2020** [comment] 2020-11-15 05:54
<class 'pandas.core.frame.DataFrame'>
Int64Index: 34 entries, 0 to 33
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   antecedents         34 non-null     object 
 1   consequents         34 non-null     object 
 2   antecedent support  34 non-null     float64
 3   consequent support  34 non-null     float64
 4   support             34 non-null     float64
 5   confidence          34 non-null     float64
 6   lift                34 non-null     float64
 7   leverage            34 non-null     float64
 8   conviction          34 non-null     float64
dtypes: float64(7), object(2)
memory usage: 2.7+ KB

**Comment by khaled-2020** [comment] 2020-11-15 05:54
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
_catboost.pyx in _catboost.get_float_feature()

_catboost.pyx in _catboost._FloatOrNan()

_catboost.pyx in _catboost._FloatOrNanFromString()

TypeError: Cannot convert 'b'baby'' to float

During handling of the above exception, another exception occurred:

CatBoostError                             Traceback (most recent call last)
<ipython-input-724-3fd5409586d7> in <module>
      1 #clf.fit(X_train, y_train,cat_features=categorical_features_indices)
----> 2 clf.fit(X_train, y_train)

~\anaconda3\lib\site-packages\catboost\core.py in fit(self, X, y, cat_features, text_features, embedding_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   4296         self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
   4297                   eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period,
-> 4298                   silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   4299         return self
   4300 

~\anaconda3\lib\site-packages\catboost\core.py in _fit(self, X, y, cat_features, text_features, embedding_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   1795             use_best_model, eval_set, verbose, logging_level, plot,
   1796             column_description, verbose_eval, metric_period, silent, early_stopping_rounds,
-> 1797             save_snapshot, snapshot_file, snapshot_interval, init_model
   1798         )
   1799         params = train_params["params"]

~\anaconda3\lib\site-packages\catboost\core.py in _prepare_train_params(self, X, y, cat_features, text_features, embedding_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   1682         train_pool = _build_train_pool(X, y, cat_features, text_features, embedding_features, pairs,
   1683                                        sample_weight, group_id, group_weight, subgroup_id, pairs_weight,
-> 1684                                        baseline, column_description)
   1685         if train_pool.is_empty_:
   1686             raise CatBoostError("X is empty.")

~\anaconda3\lib\site-packages\catboost\core.py in _build_train_pool(X, y, cat_features, text_features, embedding_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, column_description)
    983             raise CatBoostError("y has not initialized in fit(): X is not catboost.Pool object, y must be not None in fit().")
    984         train_pool = Pool(X, y, cat_features=cat_features, text_features=text_features, embedding_features=embedding_features, pairs=pairs, weight=sample_weight, group_id=group_id,
--> 985                           group_weight=group_weight, subgroup_id=subgroup_id, pairs_weight=pairs_weight, baseline=baseline)
    986     return train_pool
    987 

~\anaconda3\lib\site-packages\catboost\core.py in __init__(self, data, label, cat_features, text_features, embedding_features, column_description, pairs, delimiter, has_header, ignore_csv_quoting, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    453                     )
    454 
--> 455                 self._init(data, label, cat_features, text_features, embedding_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    456         super(Pool, self).__init__()
    457 

~\anaconda3\lib\site-packages\catboost\core.py in _init(self, data, label, cat_features, text_features, embedding_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    964             baseline = np.reshape(baseline, (samples_count, -1))
    965             self._check_baseline_shape(baseline, samples_count)
--> 966         self._init_pool(data, label, cat_features, text_features, embedding_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    967 
    968 

_catboost.pyx in _catboost._PoolBase._init_pool()

_catboost.pyx in _catboost._PoolBase._init_pool()

_catboost.pyx in _catboost._PoolBase._init_features_order_layout_pool()

_catboost.pyx in _catboost._set_features_order_data_pd_data_frame()

_catboost.pyx in _catboost.create_num_factor_data()

_catboost.pyx in _catboost.get_float_feature()

CatBoostError: Bad value for num_feature[non_default_doc_idx=0,feature_idx=0]="baby": Cannot convert 'b'baby'' to float

**Comment by LyzhinIvan** [comment] 2020-11-16 07:42
Hi, @khaled-2020! Could you provide the minimal reproducing example with first row from your dataset?

**Comment by Nataliya224** [comment] 2021-01-01 17:50
reorder columns in X_test as in X_train

**Comment by ul611** [comment] 2021-06-10 09:34
check your data for NA values. It works for me when I remove NAs

**Comment by beebearha** [comment] 2022-08-29 09:04
I encountered similar issue - the key to resolving this for me is to pass a 'dataframe' to train instead array.

**Comment by ddofer** [comment] 2024-06-25 11:11
Same issue, latest catboost, pandas version, even after imputing NaNs as "None".

```
numerical_cols = X.select_dtypes(include=['number',"boolean"]).columns.difference(categorical_cols + text_cols).to_list()

for c in text_cols:
    X[c] = X[c].fillna("None")
X[categorical_cols] = X[categorical_cols].astype(str).fillna("Empty").astype("category")

clf_model2 = CatBoostClassifier(
                           cat_features=X.select_dtypes(["O","string","category","object"]).columns.to_list(),
    text_features=text_cols
                            )

CatBoostError: Bad value for num_feature[non_default_doc_idx=11,feature_idx=104]="Uganda": Cannot convert 'b'Uganda'' to float
```

(The relevant feature is one of the text_cols)
