### ISSUE TITLE
average models: yes Or no?

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#712] opened 2019-03-01 19:19 UTC
Problem: {in issue with name Support StratifiedKFold cross-validation in CatBoost's cv I asked  is it possible to somehow average models, when each model is created for each split?
for example
split#1 -> model#1
split#2 -> model#2
split#3 -> model#3
split#4 -> model#4
split#5 -> model#5
it is clear that all models will be different

so models averaging/combining/joining would be useful 
and got this answer 
khrisanfov commented a day ago
@Sandy4321 by the way you can open issue about it, the developers can implement it in future ;)
so I try to open this issue as suggested below 
from another hand in this link 
https://towardsdatascience.com/https-medium-com-talperetz24-mastering-the-new-generation-of-gradient-boosting-db04062a7ea2

Mastering The New Generation of Gradient Boosting
it is written 
In Ordered mode boosting we perform a random permutation of the training examples - σ2, and maintain n different supporting models - M1, . . . , Mn such that the model Mi is trained using only the first i samples in the permutation. 
At each step, in order to obtain the residual for j-th sample, we use the model Mj−1.
So do you have models averaging ot not?
if not lets do it?
}
catboost version: {latest}
Operating System: {Windows}
CPU: {i7}
# GPU: {GPU}

**Comment by Sandy4321** [comment] 2019-03-01 19:21
and where to read about this Ordered vs Plain modes
as described in mentioned link

CatBoost has two modes for choosing the tree structure, Ordered and Plain. Plain mode corresponds to a combination of the standard GBDT algorithm with an ordered Target Statistic. 
In Ordered mode boosting we perform a random permutation of the training examples

**Comment by annaveronika** [comment] 2019-03-01 20:46
We have very detailed documentation that includes links to relevant papers and also explanation of the algorithm, it also has info how to tune parameters. And we also have a bunch of tutorials. If you study them carefully, it will solve many of your questions!

**Comment by annaveronika** [comment] 2019-03-01 20:47
https://tech.yandex.com/catboost/doc/dg/concepts/about-docpage/ - I would start from here.

**Comment by annaveronika** [comment] 2019-03-01 20:52
As for averaging the models - this is supported, you can use sum_models for that.

**Comment by annaveronika** [comment] 2019-03-04 09:02
Closing the issue - this functionality is already supported.

**Closed by annaveronika** 2019-03-04 09:02 UTC

**Comment by Enggarin** [comment] 2019-04-16 08:47
// from off example 
...
models_avrg = sum_models(models, weights=[1.0/len(models)] * len(models))
...

It goes to error, if you applying pridict_proba() for models_avrg , pridict() works well. Bug or ficha?;]

**Comment by annaveronika** [comment] 2019-04-16 09:52
sum_models return value is CatBoost, not CatBoostClassifier, so there is no predict_proba method, this is not a bug, but not a feature as well, it's just a different interface.

**Comment by Enggarin** [comment] 2019-04-16 11:06
models_avrg = sum_models(models, weights=[1.0/len(models)] * len(models))
preds = models_avrg .predict(X) - Ok
preds = models_avrg .predict_proba(X) -  not Ok
So, thats (sum of models) cant be used for classification problems with probability output?

**Comment by annaveronika** [comment] 2019-04-16 12:44
You can get probabilities, to do that you need to specify prediction type Probability.

**Comment by hoanglam-novobi** [comment] 2020-08-11 05:05
> models_avrg = sum_models(models, weights=[1.0/len(models)] * len(models))
> preds = models_avrg .predict(X) - Ok
> preds = models_avrg .predict_proba(X) - not Ok
> So, thats (sum of models) cant be used for classification problems with probability output?
Hi @annaveronika 
You can cast models_avrg to classifier model using the method to_classifier() in this document https://catboost.ai/docs/concepts/python-reference_to_classifier.html
After that, you can call function predict_proba

**Comment by Sandy4321** [comment] 2020-08-14 11:54
Can you share full example?
