### ISSUE TITLE
catboost.cv with YetiRank fails with "CatBoostError: /src/catboost/catboost/libs/train_lib/options_helper.cpp:88: Targets are required for YetiRank loss function."

### ISSUE THREAD

**Issue by I-Ves** [catboost/catboost#2588] opened 2024-02-03 10:50 UTC
Problem:
`cv` method fails with `YetiRank` loss_function, while CatBoost with the same parameters works.

Error: `CatBoostError: /src/catboost/catboost/libs/train_lib/options_helper.cpp:88: Targets are required for YetiRank loss function.`

Example (based on [ranking tutorial](https://github.com/catboost/catboost/blob/master/catboost/tutorials/ranking/ranking_tutorial.ipynb?ysclid=ls5xvynan4119266908)):
[Open In Colab](https://colab.research.google.com/drive/1NHAhUCnfoe7D5IfggtC5lsYr6nBs7xhw?usp=sharing)

```Python3
import numpy as np
import catboost as cb
from catboost.datasets import msrank_10k


train_df, test_df = msrank_10k()

X_train = train_df.drop([0, 1], axis=1).values
y_train = train_df[0].values
queries_train = train_df[1].values

X_test = test_df.drop([0, 1], axis=1).values
y_test = test_df[0].values
queries_test = test_df[1].values

max_relevance = np.max(y_train)
y_train /= max_relevance
y_test /= max_relevance

train_pool = cb.Pool(
    data=X_train,
    label=y_train,
    group_id=queries_train
)

test_pool = cb.Pool(
    data=X_test,
    label=y_test,
    group_id=queries_test
)

cb_params = {
    'loss_function': 'YetiRank',
    'iterations': 100,
    'custom_metric': ['NDCG', 'PFound', 'AverageGain:top=10'],
    'metric_period': 20,
    'random_seed': 0,
}

# Fails
cv_results, cv_models = cb.cv(
    train_pool,
    cb_params,
    fold_count=5,
    partition_random_seed=0,
    seed=0,
)

# Works
model = cb.CatBoost(cb_params)
model.fit(train_pool, eval_set=test_pool)
```

catboost version: 1.2.2
Operating System: Linux [google colab]
CPU: Intel(R) Xeon(R) CPU @ 2.20GHz [google colab]
GPU: No

**Comment by andrey-khropov** [comment] 2024-02-03 10:56
Duplicate of #2083

**Closed by andrey-khropov** 2024-02-03 10:56 UTC
Labels: objectives and metrics
