### ISSUE TITLE
Rocm support request

### ISSUE THREAD

**Issue by Wintoplay** [catboost/catboost#2558] opened 2023-12-24 05:54 UTC
Please add rocm support for AMD GPU.

Currently, Catboost only support cuda.

CatBoostError: [/src/catboost/catboost/cuda/cuda_lib/cuda_base.h:281](https://file+.vscode-resource.vscode-cdn.net/src/catboost/catboost/cuda/cuda_lib/cuda_base.h:281): CUDA error 35: CUDA driver version is insufficient for CUDA runtime version

**Comment by andrey-khropov** [comment] 2023-12-27 01:57
Duplicate of #1928

**Closed by andrey-khropov** 2023-12-27 01:57 UTC
