### ISSUE TITLE
Sparse input for fit

### ISSUE THREAD

**Issue by mohaksaxena** [catboost/catboost#425] opened 2018-07-26 14:01 UTC
Does CatBoost support using sparse input (e.g scipy csr or csc) for the sklearn style estimators or for the initializing the `Pool`?

**Comment by annaveronika** [comment] 2018-07-26 19:56
We don't support it jet, but we plan to add sparse features support.

**Comment by annaveronika** [comment] 2018-07-26 19:57
Actually it's the duplicate of our #1 issue, so I'm closing as a duplicate.

**Closed by annaveronika** 2018-07-26 19:57 UTC
