### ISSUE TITLE
Error while trying to build

### ISSUE THREAD

**Issue by egorrridze** [catboost/catboost#2184] opened 2022-10-07 07:29 UTC
Problem:
When I try to run the command
 `ya make -r catboost/libs/model_interface`
I got the error:

```
Traceback (most recent call last):
  File "devtools/ya/app/init.py", line 657, in configure_exit_interceptor
    yield
  File "devtools/ya/app/init.py", line 78, in helper
    return action(args, **kwargs)
  File "devtools/ya/entry/entry.py", line 63, in do_main
    res = handler.handle(handler, args, prefix=['ya'])
  File "devtools/ya/core/yarg/handler.py", line 222, in handle
    return handler.handle(self, args[1:], prefix + [name])
  File "devtools/ya/core/yarg/dispatch.py", line 38, in handle
    return self.command().handle(root_handler, args, prefix)
  File "devtools/ya/core/yarg/handler.py", line 407, in handle
    return self._action(params)
  File "devtools/ya/app/init.py", line 110, in helper
    return action(ctx.params)
  File "devtools/ya/build/build_handler.py", line 85, in do_ya_make
    builder = ya_make.YaMake(params, app_ctx)
  File "devtools/ya/build/ya_make.py", line 924, in init
    self.ctx = Context(self.opts, app_ctx=app_ctx, graph=graph, tests=tests, stripped_tests=stripped_tests, configure_errors=configure_errors, make_files=make_files, lite_graph=lite_graph)
  File "devtools/ya/build/ya_make.py", line 594, in init
    self.graph, self.tests, self.stripped_tests, self.configure_errors, self.make_files = _build_graph_and_tests(self.opts, app_ctx)
  File "devtools/ya/build/ya_make.py", line 261, in _build_graph_and_tests
    graph, tests, stripped_tests, gh, make_files = lg.build_graph_and_tests(opts, check=True, ev_listener=ev_listener, display=display)
  File "devtools/ya/build/graph.py", line 1705, in build_graph_and_tests
    return _build_graph_and_tests(opts, check, ev_listener, exit_stack, display)
  File "devtools/ya/build/graph.py", line 2076, in _build_graph_and_tests
    real_ymake_bin = tools.tool('ymake')
  File "devtools/ya/yalibrary/tools/init.py", line 220, in tool
    return toolchain.find(name, with_params, for_platform, cache=cache)
  File "devtools/ya/yalibrary/tools/init.py", line 155, in find
    cur_bottle = _bottle(location['bottle'], for_platform)
  File "devtools/ya/yalibrary/tools/init.py", line 93, in _bottle
    return _bottler().get(name, for_platform)
  File "devtools/ya/yalibrary/tools/init.py", line 82, in get
    return _Bottle(value['formula'], value.get('executable'), for_platform)
  File "devtools/ya/yalibrary/tools/init.py", line 40, in init
    self.fetcher = yalibrary.fetcher.ToolChainFetcher(core.config.tool_root(toolscache_version()), self.formula, for_platform)
  File "devtools/ya/yalibrary/fetcher/init.py", line 586, in ToolChainFetcher
    impl = _ToolChainSandboxFetcher(root, formula["sandbox_id"], for_platform)
TypeError: string indices must be integers, not str
```

catboost version: latest (07.10.22)
Operating System: Windows 10 x64
CPU: Intel Core i3-1125G4

**Comment by EdvardD** [comment] 2022-10-10 16:49
The same issue occurs for me:
setup1: clean ubuntu 22.04 in aws with python being python3.10
setup2: personal desktop with ubuntu 22.04 and python being python2.7
https://pastebin.com/HGbNLCtc

gnu make seems to be also broken:
https://pastebin.com/HVthnTfF

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2022-10-10 17:02
the issue is root-caused, the fix is in progress

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2022-10-12 04:24
fixed

**Closed by Evgueni-Petrov-aka-espetrov** 2022-10-12 04:24 UTC
Labels: build issues

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2022-10-14 09:05
@egorrridze 
yep, it is broken again
internal open source build succeeded last time for this commit
af23468f837d488c1f5765e3ebba027357c19088

**Comment by egorrridze** [comment] 2022-10-25 14:43
I have problems with version you mentioned on 2 PCs:
```
Config was not generated due to errors in C:\Users\123\Documents\cb-wr\catboost\build\ymake_conf.py
Traceback (most recent call last):
  File "C:\Users\123\Documents\cb-wr\catboost\build\ymake_conf.py", line 2556, in <module>
    main()
  File "C:\Users\123\Documents\cb-wr\catboost\build\ymake_conf.py", line 2549, in main
    build = Build(arcadia, options.build_type, options.toolchain_params, force_ignore_local_files=not options.local_distbuild)
  File "C:\Users\123\Documents\cb-wr\catboost\build\ymake_conf.py", line 480, in __init__
    self.tc = self._get_toolchain_options()
  File "C:\Users\123\Documents\cb-wr\catboost\build\ymake_conf.py", line 646, in _get_toolchain_options
    return MSVCToolchainOptions(self, detector)
  File "C:\Users\123\Documents\cb-wr\catboost\build\ymake_conf.py", line 1777, in __init__
    self.sdk_version = os.environ.get('WindowsSDKVersion').replace('\\', '')
AttributeError: 'NoneType' object has no attribute 'replace'
```

```
Config was not generated due to errors in C:\Users\user\catboost\build\ymake_conf.py
Traceback (most recent call last):
  File "C:\Users\user\catboost\build\ymake_conf.py", line 2556, in <module>
    main()
  File "C:\Users\user\catboost\build\ymake_conf.py", line 2549, in main
    build = Build(arcadia, options.build_type, options.toolchain_params, force_ignore_local_files=not options.local_distbuild)
  File "C:\Users\user\catboost\build\ymake_conf.py", line 480, in __init__
    self.tc = self._get_toolchain_options()
  File "C:\Users\user\catboost\build\ymake_conf.py", line 640, in _get_toolchain_options
    detector.detect(self.params['params'].get('c_compiler'), self.params['params'].get('cxx_compiler'))
  File "C:\Users\user\catboost\build\ymake_conf.py", line 894, in detect
    raise ConfigureError('Could not deteruserne custom compiler version: {}'.format(c_compiler))
ConfigureError: Could not deteruserne custom compiler version: cl.exe
```
Is this a problem on my side?

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2022-10-26 04:45
hi @egorrridze 
might that be that you did not setup the compiler environment properly?
what does `cl.exe /?` print?

**Comment by egorrridze** [comment] 2022-10-26 09:03
on first PC:
```
Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.25.28614 для x64
(C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
```

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2022-10-26 10:15
could you please kindly check whether some windows sdk is installed?

you might use the visual studio installer to check this 

launch the installer
![image](https://user-images.githubusercontent.com/7053671/198000611-920961cb-e2cb-43f5-97d7-3c0b8c20419e.png)

press the modify button, and check that windows sdk is installed
![image](https://user-images.githubusercontent.com/7053671/198000857-024ae782-7165-426e-b259-8f9b932adfc6.png)

if it is not installed, then please install

**Comment by cconw** [comment] 2023-02-01 22:04
- **- Windows 11, Cuda (3060), Visual Studio 2022.
- 
- Is catboost not compatible with Visual Studio 2022 ?   I know 2019 is recommended...  any ideas?  Thx**

C:\Users\cc\catboost>ya make -r -DCUDA_ROOT=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin
Config was not generated due to errors in C:\Users\cc\catboost\build\ymake_conf.py
Traceback (most recent call last):
  File "C:\Users\cc\catboost\build\ymake_conf.py", line 2560, in <module>
    main()
  File "C:\Users\cc\catboost\build\ymake_conf.py", line 2553, in main
    build = Build(arcadia, options.build_type, options.toolchain_params, force_ignore_local_files=not options.local_distbuild)
  File "C:\Users\cc\catboost\build\ymake_conf.py", line 485, in __init__
    self.tc = self._get_toolchain_options()
  File "C:\Users\cc\catboost\build\ymake_conf.py", line 651, in _get_toolchain_options
    return MSVCToolchainOptions(self, detector)
  File "C:\Users\cc\catboost\build\ymake_conf.py", line 1783, in __init__
    self.sdk_version = os.environ.get('WindowsSDKVersion').replace('\\', '')
AttributeError: 'NoneType' object has no attribute 'replace'
