### ISSUE TITLE
TimeDelta error when fitting CatBoostClassifier in catboost_spark

### ISSUE THREAD

**Issue by Rhys-Thompson** [catboost/catboost#2223] opened 2022-11-11 15:39 UTC
Problem:TimeDelta cannot be cast to java.time.Duration error
catboost version: ai.catboost:catboost-spark_3.1_2.12:1.0.4
Operating System: DataBricks 10.4 LTS ML (includes Apache Spark 3.1.2, Scala 2.12)

Data: 100m rows, 26 categorical features
sparkconf:
driver: 128 GB Memory, 16 Cores
20 workers: 2,560 GB Memory 640 Cores

Hi, I'm running into the following error when trying to fit CatBoostClassifier and I'm unsure why. 

I saw this was raised as a previous issue but there was no solution provided.

<img width="897" alt="Screenshot 2022-11-11 at 15 38 07" src="https://user-images.githubusercontent.com/106081883/201374001-b6d55120-649e-47d5-97f9-eb42dbc8c850.png">

**Comment by andrey-khropov** [comment] 2022-11-17 19:31
First of all, please try CatBoost version 1.1.1. And also make sure PySpark python package version is also 3.1.x.

If it still fails please provide a reproducing code example (preferably as small as possible).

**Comment by lovakap** [comment] 2023-02-08 14:42
same issue from Spark 3.3.0, Scala 2.12, CatBoost 1.1.1

**Comment by ek-ak** [comment] 2023-02-09 08:36
> same issue from Spark 3.3.0, Scala 2.12, CatBoost 1.1.1, and with much less data

Hello!  Please provide a reproducer if it is possible.

**Comment by ceciliasr** [comment] 2023-02-22 16:08
Here you have a reproducible example:
`
from pyspark.sql import Row,SparkSession
from pyspark.ml.linalg import Vectors, VectorUDT
from pyspark.sql.types import *

spark = (SparkSession.builder
  .master("local[*]")
  .config(
          "spark.jars.packages", 
          "ai.catboost:catboost-spark_3.3_2.12:1.1.1")
    .config("spark.executor.cores", "2")
    .config("spark.task.cpus", "2")
    .config("spark.driver.memory", "2g")
    .config("spark.driver.memoryOverhead", "2g")
    .config("spark.executor.memory", "2g")
    .config("spark.executor.memoryOverhead", "2g")
    .getOrCreate()
)

import catboost_spark
    
srcDataSchema = [
    StructField("features", VectorUDT()),
    StructField("label", StringType())
]

trainData = [
    Row(Vectors.dense(0.1, 0.2, 0.11), "0"),
    Row(Vectors.dense(0.97, 0.82, 0.33), "1"),
    Row(Vectors.dense(0.13, 0.22, 0.23), "1"),
    Row(Vectors.dense(0.8, 0.62, 0.0), "0")
]
    
trainDf = spark.createDataFrame(spark.sparkContext.parallelize(trainData), StructType(srcDataSchema))
trainPool = catboost_spark.Pool(trainDf)
    
evalData = [
    Row(Vectors.dense(0.22, 0.33, 0.9), "1"),
    Row(Vectors.dense(0.11, 0.1, 0.21), "0"),
    Row(Vectors.dense(0.77, 0.0, 0.0), "1")
]
    
evalDf = spark.createDataFrame(spark.sparkContext.parallelize(evalData), StructType(srcDataSchema))
evalPool = catboost_spark.Pool(evalDf)
    
classifier = catboost_spark.CatBoostClassifier()
    
# train a model
model = classifier.fit(trainPool)
`

**Comment by sjoshi-antuit** [comment] 2024-08-28 09:07
Hello, any update on this? Facing a similar issue on DataBricks 13.3 LTS ML (includes Apache Spark 3.4.1, Scala 2.12) with ai.catboost:catboost-spark_3.4_2.12:1.2.5

**Comment by andrey-khropov** [comment] 2024-12-03 02:31
Duplicate of #2051

**Closed by andrey-khropov** 2024-12-03 02:31 UTC
Labels: bug, Spark
