### ISSUE TITLE
Raises "TypeError: No matching signature found" when creating Pool() object

### ISSUE THREAD

**Issue by llorenzo62** [catboost/catboost#1233] opened 2020-03-26 02:47 UTC
Problem:Raises "TypeError: No matching signature found" when creating Pool() object
catboost version: 0.22
Operating System: Linux
CPU: Intel(R) Core(TM) i7-7700
GPU: None

I' m sorry for reopen this issue, but I get this error when downcast a  target (label) from float64 to float32. Amazingly, downcast the whole dataset with all columns int64 and float64 to int32 and float32 (data) works well .

I didn't try a downcasted  integer label

**Comment by annaveronika** [comment] 2020-04-23 15:28
Could you please provide a reproducing example?

**Comment by daimoriwaki** [comment] 2020-05-05 10:30
I got a same problem but once I cast my label data float like `y.astype(float)` the model worked.

**Comment by llorenzo62** [comment] 2020-05-11 13:55
Sure. A toy example reproducing all steps which I took

import numpy as np
import pandas as pd
import catboost

#Function used to downcast
def downcast_dtypes(df):
    '''
        Changes column types in the dataframe: 
                
                `float64` type to `float32`
                `int64`   type to `int32`
    '''
    
        # Select columns to downcast
        float_cols = [c for c in df if df[c].dtype == "float64"]
        int_cols =   [c for c in df if df[c].dtype == "int64"]
    
        # Downcast
        df[float_cols] = df[float_cols].astype(np.float16)
        df[int_cols]   = df[int_cols].astype(np.int16)
    
        return df


#Example code


toyExample=np.array([np.random.random(300),np.random.random(300),np.random.random(300),np.random.random(300)])
te=pd.DataFrame(toyExample.transpose(),columns=['x','y','z','target'])
target=te['target']
te.drop(['target'],axis=1,inplace=True)

#This works
model=catboost.CatBoostRegressor(od_type='Iter',od_wait=20,verbose=100)
model.fit(te,target)

#This works too
model=catboost.CatBoostRegressor(od_type='Iter',od_wait=20,verbose=100)
model.fit(downcast_dtypes(te),target)

#This  does not work
model=catboost.CatBoostRegressor(od_type='Iter',od_wait=20,verbose=100)
model.fit(te,downcast_dtypes(['target']))

**Comment by llorenzo62** [comment] 2020-05-11 14:26
I realized just now that the problem is with float16, no float32

**Comment by sephib** [comment] 2020-09-24 09:55
We had a similar issue  when running with int64.
After converting to `astype('int')` the issue was resolved.  
please advice if a PR is relevant

**Comment by chanansh** [comment] 2021-02-16 17:01
Pool does not receive pandas Categorical data albeit the documentation suggests using it. 
https://catboost.ai/docs/concepts/speed-up-training.html

> Using pandas.Categorical type instead of object
> Use the pandas.Categorical type instead of the object type to speed up the preprocessing for datasets with categorical features up to 200 times.

**Comment by andrey-khropov** [comment] 2023-08-28 03:05
Duplicate of #1508

**Closed by andrey-khropov** 2023-08-28 03:05 UTC
Labels: duplicate, bug, python
