### ISSUE TITLE
Large Multi-Label Dimension: All train targets are equal Error

### ISSUE THREAD

**Issue by somyamohanty** [catboost/catboost#2322] opened 2023-03-09 15:59 UTC
Problem: CatBoost classifier for multi-label classification throws an error of 
`CatBoostError: catboost/libs/metrics/metric.cpp:6376: All train targets are equal`. 

catboost version: 1.1.1
Operating System: Linux (Ubuntu)
CPU: Intel Xenon
GPU: V100

**Code for replication:**

```
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier, Pool

X_t, Y_t = make_multilabel_classification(n_samples=50000, n_features=200, n_classes=1000, random_state=0)
X_train_t, X_test_t, Y_train_t, Y_test_t = train_test_split(X_t, Y_t)
train_pool = Pool(X_train_t, Y_train_t)
test_pool = Pool(X_test_t, Y_test_t)

clf = CatBoostClassifier(
    loss_function='MultiLogloss',
    eval_metric='HammingLoss',
    iterations=500,
)
clf.fit(train_pool, eval_set=test_pool, metric_period=10, plot=True, verbose=50)
```

**Error:**
```
---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
Cell In[133], line 6
      1 clf = CatBoostClassifier(
      2     loss_function='MultiLogloss',
      3     eval_metric='HammingLoss',
      4     iterations=500,
      5 )
----> 6 clf.fit(train_pool, eval_set=test_pool, metric_period=10, plot=True, verbose=50)

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/catboost/core.py:5128, in CatBoostClassifier.fit(self, X, y, cat_features, text_features, embedding_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, plot_file, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   5125 if 'loss_function' in params:
   5126     CatBoostClassifier._check_is_compatible_loss(params['loss_function'])
-> 5128 self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
   5129           eval_set, verbose, logging_level, plot, plot_file, column_description, verbose_eval, metric_period,
   5130           silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   5131 return self

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/catboost/core.py:2355, in CatBoost._fit(self, X, y, cat_features, text_features, embedding_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, plot_file, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   2351 allow_clear_pool = train_params["allow_clear_pool"]
   2353 with log_fixup(log_cout, log_cerr), \
   2354     plot_wrapper(plot, plot_file, 'Training plots', [_get_train_dir(self.get_params())]):
-> 2355     self._train(
   2356         train_pool,
   2357         train_params["eval_sets"],
   2358         params,
   2359         allow_clear_pool,
   2360         train_params["init_model"]
   2361     )
   2363 # Have property feature_importance possibly set
   2364 loss = self._object._get_loss_function_name()

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/catboost/core.py:1759, in _CatBoostBase._train(self, train_pool, test_pool, params, allow_clear_pool, init_model)
   1758 def _train(self, train_pool, test_pool, params, allow_clear_pool, init_model):
-> 1759     self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
   1760     self._set_trained_model_attributes()

File _catboost.pyx:4623, in _catboost._CatBoost._train()

File _catboost.pyx:4672, in _catboost._CatBoost._train()

CatBoostError: catboost/libs/metrics/metric.cpp:6376: All train targets are equal
```

**Comment by andrey-khropov** [comment] 2024-03-06 19:43
Duplicate of #1970. See https://github.com/catboost/catboost/issues/1970#issuecomment-1361713855

**Closed by andrey-khropov** 2024-03-06 19:43 UTC
