### ISSUE TITLE
C++ api gives different predictions to python api

### ISSUE THREAD

**Issue by antipisa** [catboost/catboost#1145] opened 2020-01-15 02:57 UTC
Problem:

Hi,
it is straightforward to verify that the C++ api gives different prediction results to the python api when the CatboostRegressor model is trained in python, on any m float features and n>0 categorical features, saved in cpp format and executed. This is not the case with n=0 categorical features. Can you please investigate?

```
params = {"boosting_type":"Ordered", 
"num_boost_round":500,
"loss_function":"RMSE",
"eval_metric":"RMSE"}

model = CatBoostRegressor(**params)
pool = Pool(X,label=y, cat_features=["A","B"])
model.fit(pool)
model.save_model(filename, format="cpp")
preds = model.predict(pool)

// main.C
std::vector<float> floatFeatures(100);
std::vector<std::string> catFeatures = {"a", "b"};
std::cout << double pred = ApplyCatboostModel(floatFeatures, catFeatures) << std::endl;


```
catboost version: 0.17.5
Operating System: Unix

**Comment by kizill** [comment] 2020-01-15 12:01
There is something strange in your code - model format exports model as compilable C++ code, wich could be statically compiled in target application, then you load some file as catboost binary model.

**Comment by kizill** [comment] 2020-01-20 14:24
Hello! We need more details here.

**Comment by antipisa** [comment] 2020-01-20 19:55
Please see edited code -- I save the model in cpp and compile in gcc 7.3.1. The cpp binary applied to any rows of X gives a different prediction than in python.

**Comment by annaveronika** [comment] 2020-01-23 11:42
Could you please provide a full reproducible example?

**Comment by annaveronika** [comment] 2020-02-04 10:53
closing because of inactivity

**Comment by antipisa** [comment] 2020-02-09 12:00
Here is the repro:

```
from catboost import CatBoostRegressor, Pool
N = 1000
X = pd.DataFrame("A":np.random.permutation(['a','b','c','d','e']*250),
"B":np.random.randn(N))
y = np.random.randn(N)

simple_ctr = ["Borders:TargetBorderCount=15", "Buckets:TargetBorderCount=15", "Borders:TargetBorderType=MinEntropy", "Counter:CtrBorderCount=20"]

params = {"boosting_type":"Ordered", 
"num_boost_round":100,
 "simple_ctr":simple_ctr}

pool = Pool(X,label=y, cat_features=["A"]) 
model = CatBoostRegressor(**params)
model.fit(pool)
preds = model.predict(pool)

model.save_model("cppmodel", format="cpp")
```

Now call

```
// main.C
std::vector<float> floatFeatures = {-0.42};
std::vector<std::string> catFeatures = {"a"};
std::cout << double pred = ApplyCatboostModel(floatFeatures, catFeatures) << std::endl;


```

**Comment by ek-ak** [comment] 2020-02-12 08:55
Hello! Thank you for your issue. The problem was that we had not accurate verification, that pool is provided  when catboost cpp model with categorical features is saved.  We fixed verification. Correct code in your example will be the next one:
`model.save_model("cppmodel", format="cpp", pool=pool)`

**Comment by annaveronika** [comment] 2020-02-12 08:59
The input parameters check is now fixed in code, in the next version this code will fail. Thanks for pointing out this error! Closing the issue, verification fix will be out in the next version.

**Closed by annaveronika** 2020-02-12 08:59 UTC
Labels: in progress

**Comment by antipisa** [comment] 2020-02-12 09:20
> The input parameters check is now fixed in code, in the next version this code will fail. Thanks for pointing out this error! Closing the issue, verification fix will be out in the next version.

In the next version you will require that the pool which model was trained on is passed into save_model when format="cpp"? Wouldn't it be easier to save the catFeatures hashmap to the exported model file whenever save_model is called?

**Comment by annaveronika** [comment] 2020-02-12 10:04
It is required for this version also, just the check is missing.
The model contains hash values, not the string values. And in the cpp model you don't know the hash function, so you need the string values.
