### ISSUE TITLE
Single Label Classification Model: Target contains only one unique value

### ISSUE THREAD

**Issue by KuzonFyre** [catboost/catboost#2418] opened 2023-06-27 22:13 UTC
Problem: **Target contains only one unique value**
catboost version: 1.2
Operating System: Mac 13.4.1
CPU: Apple M1 Chip
GPU: N/A

I am using [this](https://github.com/bmi-labmedinfo/araucana-xai) library to create local rule based explanations for a classification model. The library creates a neighborhood of similar data, trains that data on a tree model and that tree has rules that correspond to the og model's predictions. The tree model they are using is in Scikit-learn and it does not support categorical features. I am working on modifying the code to use CatBoost instead.
`    df_X = DataFrame(X, columns=X_features)
    print(df_X.head())
    print(cat_list)
    
    # df_X[cat_list] = df_X[cat_list].astype('int64')
    if cat_list is not None:
        for i in range(0,len(X_features)):
            if cat_list[i]:
                df_X[X_features[i]] = df_X[X_features[i]].astype('int64')

    clf_tree_0 = CatBoostClassifier(max_depth=max_depth, min_child_samples=min_samples_leaf, cat_features=cat_list,allow_const_label=True)
    clf_tree_0.fit(df_X, y)
    return clf_tree_0`

I specify `allow_const_label=True` so that CatBoost does not break when it notices that I only have one label in my dataset. Even after adding this line, I still see this error. 

```File ~/anaconda3/lib/python3.10/site-packages/catboost/core.py:1761, in _CatBoostBase._train(self, train_pool, test_pool, params, allow_clear_pool, init_model)
   1760 def _train(self, train_pool, test_pool, params, allow_clear_pool, init_model):
-> 1761     self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
   1762     self._set_trained_model_attributes()

File _catboost.pyx:4625, in _catboost._CatBoost._train()

File _catboost.pyx:4674, in _catboost._CatBoost._train()

CatBoostError: /Users/zomb-ml-platform-msk/go-agent-21.2.0/pipelines/BuildMaster/catboost.git/catboost/private/libs/target/target_converter.cpp:375: Target contains only one unique value
```

**Target contains only one unique value**

My use case requires a single label model.

**Comment by andrey-khropov** [comment] 2024-02-10 02:15
Duplicate of #1933

**Closed by andrey-khropov** 2024-02-10 02:15 UTC
