### ISSUE TITLE
[catboost-spark] Error while executing master

### ISSUE THREAD

**Issue by kma-25** [catboost/catboost#1943] opened 2021-12-02 08:14 UTC
Problem: catboost-spark: Error while executing master

I am training a catboost multiclass classification model on spark:
```
model = catboost_spark.CatBoostClassifier(
    featuresCol='features', labelCol='label', randomSeed=42
).setLossFunction("MultiClass")

cb_clf = model.fit(train)
```
When I use 2 million rows of data the model works well and there are no issues. However, when I increase the amount of data by 2 times, then the following error occurs:

```
Py4JJavaError: An error occurred while calling o663.fit.
: java.util.concurrent.ExecutionException: Error while executing master
	at ai.catboost.spark.impl.Helpers$.checkOneFutureAndWaitForOther(Helpers.scala:43)
	at ai.catboost.spark.impl.Helpers$.waitForTwoFutures(Helpers.scala:61)
	at ai.catboost.spark.CatBoostPredictorTrait.$anonfun$fit$12(CatBoostPredictor.scala:256)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at ai.catboost.spark.CatBoostPredictorTrait.fit(CatBoostPredictor.scala:226)
	at ai.catboost.spark.CatBoostPredictorTrait.fit$(CatBoostPredictor.scala:125)
	at ai.catboost.spark.CatBoostClassifier.fit(CatBoostClassifier.scala:366)
	at ai.catboost.spark.CatBoostPredictorTrait.train(CatBoostPredictor.scala:111)
	at ai.catboost.spark.CatBoostPredictorTrait.train$(CatBoostPredictor.scala:108)
	at ai.catboost.spark.CatBoostClassifier.train(CatBoostClassifier.scala:366)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
Caused by: ai.catboost.CatBoostError: CatBoost Master process failed: exited with code 137
	at ai.catboost.spark.impl.CatBoostMasterWrapper.trainCallback(Master.scala:206)
	at ai.catboost.spark.CatBoostPredictorTrait.$anonfun$fit$13(CatBoostPredictor.scala:230)
	at ai.catboost.spark.CatBoostPredictorTrait.$anonfun$fit$13$adapted(CatBoostPredictor.scala:230)
	at ai.catboost.spark.TrainingDriver.run(TrainingDriver.scala:271)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```
I use a Databricks cluster.

How can I go around this issue to train?

catboost version: ai.catboost:catboost-spark_3.1_2.12:1.0.3

**Comment by kma-25** [comment] 2021-12-02 13:03
@andrey-khropov 

I use a cluster with the following configuration:
Databricks Runtime Version: 9.1 LTS ML (includes Apache Spark 3.1.2, Scala 2.12)
Driver and Worker types are the same: i3.xlarge (30.5 GB Memory, 4 Cores)
Min workers: 1, Max workers: 32



the full traceback of the error:

```
Py4JJavaError                             Traceback (most recent call last)
<command-2133018466756590> in <module>
----> 1 cb_clf = model.fit(train)

/local_disk0/spark-0a55dc5c-cbaf-412e-bba1-b10df57117c3/userFiles-128eab08-f837-43fa-891c-9e1ba58d0c24/addedFile8984390132141871691catboost_spark_3_1_2_12_1_0_3-e84c2.jar/catboost_spark/core.py in fit(self, trainDataset, evalDatasets)
   5108             if evalDatasets is not None:
   5109                 raise RuntimeError("if trainDataset has type DataFrame no evalDatasets are supported")
-> 5110             return JavaEstimator.fit(self, trainDataset)
   5111         else:
   5112             sc = SparkContext._active_spark_context

/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_pyspark.py in patched_method(self, *args, **kwargs)
     28             call_succeeded = False
     29             try:
---> 30                 result = original_method(self, *args, **kwargs)
     31                 call_succeeded = True
     32                 return result

/databricks/spark/python/pyspark/ml/base.py in fit(self, dataset, params)
    159                 return self.copy(params)._fit(dataset)
    160             else:
--> 161                 return self._fit(dataset)
    162         else:
    163             raise ValueError("Params must be either a param map or a list/tuple of param maps, "

/databricks/spark/python/pyspark/ml/wrapper.py in _fit(self, dataset)
    333 
    334     def _fit(self, dataset):
--> 335         java_model = self._fit_java(dataset)
    336         model = self._create_model(java_model)
    337         return self._copyValues(model)

/databricks/spark/python/pyspark/ml/wrapper.py in _fit_java(self, dataset)
    330         """
    331         self._transfer_params_to_java()
--> 332         return self._java_obj.fit(dataset._jdf)
    333 
    334     def _fit(self, dataset):

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    115     def deco(*a, **kw):
    116         try:
--> 117             return f(*a, **kw)
    118         except py4j.protocol.Py4JJavaError as e:
    119             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o682.fit.
: java.util.concurrent.ExecutionException: Error while executing master
	at ai.catboost.spark.impl.Helpers$.checkOneFutureAndWaitForOther(Helpers.scala:43)
	at ai.catboost.spark.impl.Helpers$.waitForTwoFutures(Helpers.scala:61)
	at ai.catboost.spark.CatBoostPredictorTrait.$anonfun$fit$12(CatBoostPredictor.scala:256)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at ai.catboost.spark.CatBoostPredictorTrait.fit(CatBoostPredictor.scala:226)
	at ai.catboost.spark.CatBoostPredictorTrait.fit$(CatBoostPredictor.scala:125)
	at ai.catboost.spark.CatBoostClassifier.fit(CatBoostClassifier.scala:366)
	at ai.catboost.spark.CatBoostPredictorTrait.train(CatBoostPredictor.scala:111)
	at ai.catboost.spark.CatBoostPredictorTrait.train$(CatBoostPredictor.scala:108)
	at ai.catboost.spark.CatBoostClassifier.train(CatBoostClassifier.scala:366)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
Caused by: ai.catboost.CatBoostError: CatBoost Master process failed: exited with code 137
	at ai.catboost.spark.impl.CatBoostMasterWrapper.trainCallback(Master.scala:206)
	at ai.catboost.spark.CatBoostPredictorTrait.$anonfun$fit$13(CatBoostPredictor.scala:230)
	at ai.catboost.spark.CatBoostPredictorTrait.$anonfun$fit$13$adapted(CatBoostPredictor.scala:230)
	at ai.catboost.spark.TrainingDriver.run(TrainingDriver.scala:271)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

```

**Comment by andrey-khropov** [comment] 2021-12-03 01:46
CatBoost for Apache Spark runs a separate CatBoost Master process. 
An error message `CatBoost Master process failed: exited with code 137` means that this process has been killed (a SIGKILL signal has been sent to it).
It is likely that it happened because Linux OOM killer killed it because all the RAM on the host has been exhausted.
It can be checked [like this](https://stackoverflow.com/a/20672691) if you have an access to the machine.
You can also check memory usage using some resource diagnostic tools.

Excessive memory usage for the CatBoost Master can possibly be caused by a lot of classes that are present in the dataset. How many classes does your dataset contain?

**Comment by kma-25** [comment] 2021-12-07 12:38
@andrey-khropov thank you! the number of classes was higher for the bigger dataset, I tried to decrease the number of classes (to have relatively the same number as was in the smaller dataset) and was able to train the model. 

what parameters can be changed to be able to work with a high number of classes (let's say thousands instead of hundreds)?

**Comment by andrey-khropov** [comment] 2021-12-08 00:50
> what parameters can be changed to be able to work with a high number of classes (let's say thousands instead of hundreds)?

You have to increase RAM size on a driver node (and possibly on worker nodes). 

CatBoost Master needs `dataset_size x classes_count x 3 x 4` bytes in RAM only to store approxes during training.
The same amount of RAM is cumulatively required on workers but the dataset data is distributed, so each worker needs approximately `(dataset_size / worker_count)  x classes_count x 3 x 4`.

**Comment by kma-25** [comment] 2021-12-08 04:40
thank you!

**Comment by andrey-khropov** [comment] 2021-12-08 08:25
@kma-25 If your problem is solved please close this issue.

**Closed** 2021-12-08 08:50 UTC
Labels: need info, Spark

**Comment by arturopineda92** [comment] 2022-02-18 16:23
Hi @kma-25 I have the same issue but I using a simple test, with very small dataset (4 rows) and whrn I tried to uset .fit I get the same error.
Could you share me your spark session setup? jars included
Thanks
