### ISSUE TITLE
Core dump on running catboost4j with object counts>7

### ISSUE THREAD

**Issue by pawasa1** [catboost/catboost#569] opened 2018-12-04 19:26 UTC
Problem: {problem description}
catboost version: {0.11.1}
Operating System: {Mac and Linux}
CPU: {CPU}
# GPU: {GPU}

I have model with 2 Categorial features and 6 numeric features.
When providing up to 7 object counts prediction works perfect, for 8 and more it's crashes.

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1649ffcf47, pid=14364, tid=0x00007f164b784700
#
# JRE version: OpenJDK Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.191-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x699f47]
#

Stack: [0x00007f164b685000,0x00007f164b785000],  sp=0x00007f164b782b30,  free space=1014k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x699f47]
C  [libcatboost4j-prediction5763417380311344224.so+0x4fe129]  Java_ai_catboost_CatBoostJNIImpl_catBoostModelPredict__J_3_3F_3_3Ljava_lang_String_2_3D+0x669

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  ai.catboost.CatBoostJNIImpl.catBoostModelPredict(J[[F[[Ljava/lang/String;[D)Ljava/lang/String;+0
j  ai.catboost.CatBoostJNI.catBoostModelPredict(J[[F[[Ljava/lang/String;[D)V+6
j  ai.catboost.CatBoostModel.predict([[F[[Ljava/lang/String;Lai/catboost/CatBoostPredictions;)V+13
j  ai.catboost.CatBoostModel.predict([[F[[Ljava/lang/String;)Lai/catboost/CatBoostPredictions;+45
....
v  ~StubRoutines::call_stub

What information to provide to help you to reproduce this issue?
Happened on both Mac and Linux from Java.
Running in command line using  "catboost calc .." - no problem.

Thanks,
Pavel

**Comment by annaveronika** [comment] 2018-12-11 19:50
Sorry for a long response! We'll look into this soon.

**Comment by annaveronika** [comment] 2018-12-11 19:51
If you could provide the dataset and code to reproduce, it would be very helpful. Maybe a subset of your dataset or a sintetic one if it reproduces on it.

**Comment by yazevnul** [comment] 2018-12-12 07:08
@pawasa1 what's the version of `catboost4j-prediction` that you use? Try 0.2.4, earlier versions had a bug that caused segfault in some cases.

**Comment by yazevnul** [comment] 2018-12-12 07:10
If it won't solve your problem, can you show a code snippet where you apply model? Or better, give a minimal reproducer.

**Comment by pawasa1** [comment] 2018-12-12 18:32
Here we go.
See attached code and model.




Just run it to reproduce.
If you will reduce size of elements in values array to less than 7 it will work.

Thanks,

**Comment by pawasa1** [comment] 2018-12-12 18:38
[Archive.zip](https://github.com/catboost/catboost/files/2673102/Archive.zip)

archive contains code and model

**Comment by yazevnul** [comment] 2018-12-13 13:00
Hey, I've tried your example and it works perfectly at least with 0.2.4 version of `catboost-prediction`, can you show your file with dependencies description? (e.g. `pom.xml`)

**Comment by pawasa1** [comment] 2018-12-14 11:58
Attaching you jar I’ve compiled.
Hope that it will help to explain the problem…
Contains libs for MAC or Linux (no Windows...)

[catboost-prediction-0.2.4-SNAPSHOT.jar.zip](https://github.com/catboost/catboost/files/2679968/catboost-prediction-0.2.4-SNAPSHOT.jar.zip)

**Comment by annaveronika** [comment] 2018-12-17 07:56
Please download the applier from Maven Central and try again. It looks like you are still using an old version.

**Comment by pawasa1** [comment] 2018-12-17 17:42
I've downloaded latest version and it is still fails. Can you please recheck and let me know. Attaching jar that I compiled right now on Linux.
[catboost-prediction-0.2.4-SNAPSHOT.jar.zip](https://github.com/catboost/catboost/files/2687219/catboost-prediction-0.2.4-SNAPSHOT.jar.zip)

**Comment by annaveronika** [comment] 2018-12-17 18:11
Do you use the compiled version or the one from Maven? Can you try one from Maven? If you are using one from Maven, could you send file with dependencies description?

**Comment by annaveronika** [comment] 2018-12-17 18:12
https://mvnrepository.com/artifact/ai.catboost/catboost-prediction/0.2.4 - you can download it here

**Comment by annaveronika** [comment] 2018-12-17 22:20
Ok, great that it worked for you! I suggest using released versions. Closing the issue then. Let us know if you have more problems.

**Closed by annaveronika** 2018-12-17 22:20 UTC
Labels: Java, bug, need info
