### ISSUE TITLE
GPU via python error

### ISSUE THREAD

**Issue by alexionby** [catboost/catboost#161] opened 2017-11-01 20:38 UTC
Your example:

```
import numpy
from catboost import CatBoostRegressor

dataset = numpy.array([[1,4,5,6],[4,5,6,7],[30,40,50,60],[20,15,85,60]])
train_labels = [1.2,3.4,9.5,24.5]
model = CatBoostRegressor(verbose=True, device_type='GPU')
fit_model = model.fit(dataset, train_labels)

print(fit_model.get_params())
```

> ---------------------------------------------------------------------------
> CatboostError                             Traceback (most recent call last)
> <ipython-input-25-3e54dc567647> in <module>()
>       5 train_labels = [1.2,3.4,9.5,24.5]
>       6 model = CatBoostRegressor(verbose=True, device_type='GPU')
> ----> 7 fit_model = model.fit(dataset, train_labels)
>       8 
>       9 print(fit_model.get_params())
> 
> /home/alex/catboost/catboost/python-package/catboost/core.py in fit(self, X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, plot)
>     500         model : CatBoost
>     501         """
> --> 502         return self._fit(X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, plot)
>     503 
>     504     def _predict(self, data, prediction_type, ntree_start, ntree_end, thread_count, verbose):
> 
> /home/alex/catboost/catboost/python-package/catboost/core.py in _fit(self, X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, plot)
>     454                 raise ImportError(str(e))
>     455         with log_fixup():
> --> 456             self._train(X, eval_set, params)
>     457         if calc_feature_importance:
>     458             setattr(self, "_feature_importance", self.get_feature_importance(X))
> 
> _catboost.pyx in _catboost._CatBoostBase._train (/home/alex/.ya/build/build_root/nzps/0003ca/catboost/python-package/catboost/_catboost.pyx.cpp:15678)()
> 
> _catboost.pyx in _catboost._CatBoost._train (/home/alex/.ya/build/build_root/nzps/0003ca/catboost/python-package/catboost/_catboost.pyx.cpp:10531)()
> 
> _catboost.pyx in _catboost._CatBoost._train (/home/alex/.ya/build/build_root/nzps/0003ca/catboost/python-package/catboost/_catboost.pyx.cpp:10329)()
> 
> CatboostError: catboost/cuda/train_lib/json_options.h:415: Unknown param: rsm

And i have no idea what to do next.

I've just installed cuda-9-0-local.

**Comment by annaveronika** [comment] 2017-11-01 21:24
gpu version does not yet support all the parameters. The full list of supported parameters you can see here:
https://tech.yandex.com/catboost/doc/dg/concepts/cli-on-gpu-reference-docpage/#cli-on-gpu-reference

rsm is not supported.

**Comment by alexionby** [comment] 2017-11-01 21:44
But how can i turn it off?

**Comment by annaveronika** [comment] 2017-11-01 22:52
for now please set it to nan, we'll fix it shortly.

**Comment by cooltyn** [comment] 2017-11-09 14:51
Are you support all CUDA devices? On GTX1050 with installed CUDA 9.0 on catboost 0.3.1 with code from first comment I'm getting error:

> Traceback (most recent call last):
  File "C:/Users/cooltyn/Desktop/2.py", line 7, in <module>
    fit_model = model.fit(dataset, train_labels)
  File "C:\Users\cooltyn\AppData\Local\Programs\Python\Python36\lib\site-packages\catboost\core.py", line 502, in fit
    return self._fit(X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, plot)
  File "C:\Users\cooltyn\AppData\Local\Programs\Python\Python36\lib\site-packages\catboost\core.py", line 456, in _fit
    self._train(X, eval_set, params)
  File "_catboost.pyx", line 839, in _catboost._CatBoostBase._train (c:\users\kizill\.ya\build\build_root\2b8u\0001f9\catboost\python-package\catboost\_catboost.pyx.cpp:15678)
  File "_catboost.pyx", line 662, in _catboost._CatBoost._train (c:\users\kizill\.ya\build\build_root\2b8u\0001f9\catboost\python-package\catboost\_catboost.pyx.cpp:10531)
  File "_catboost.pyx", line 667, in _catboost._CatBoost._train (c:\users\kizill\.ya\build\build_root\2b8u\0001f9\catboost\python-package\catboost\_catboost.pyx.cpp:10329)
_catboost.CatboostError: st/catboost/libs/algo/train_model.cpp:381: GPU Device not found.

**Comment by annaveronika** [comment] 2017-11-09 14:54
Could you please try running commandline version, is there the same bug?

**Comment by annaveronika** [comment] 2017-11-09 14:58
We support only 8.0 version, so you should eather build the package from source, or install 8.0

**Comment by kizill** [comment] 2017-11-09 15:07
Could you try to execute this in python shell:
`import catboost.gpu._catboost`
For example, on linux machine without cuda installed it outputs: 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory`

**Comment by gamers5a** [comment] 2017-11-09 15:32
Same problem `GPU Device not found` on 1080ti, `import catboost.gpu._catboost` imports without any problem.

**Comment by annaveronika** [comment] 2017-11-09 15:49
You should either build from source or install cuda 8.0

**Comment by annaveronika** [comment] 2017-11-09 15:52
@gamers5a what os are you using?

**Comment by gamers5a** [comment] 2017-11-09 15:57
@annaveronika Arch Linux x86_64 build from source with kernel 4.13.11-1. Another GPU based frameworks such as TensorFlow, Theano, Pytorch works without any problem.

**Comment by cooltyn** [comment] 2017-11-09 17:07
`import catboost.gpu._catboost` works for me without any errors too. Installed CUDA 8.0, python lib on Windows not working. Can someone upload working example with all need files for command-line version?

**Comment by annaveronika** [comment] 2017-11-09 18:05
https://github.com/catboost/catboost/blob/master/catboost/tutorials/catboost_cmdline_tutorial.md - the first part of the tutorial should work on gpu binary also.

**Comment by kizill** [comment] 2017-11-09 19:14
I've reproduced your bug - it occurs on python 3, we will publish fix soon.
Hotfix patch https://pastebin.com/W5jeQHD6

**Comment by cooltyn** [comment] 2017-11-10 09:31
@annaveronika examples here has some errors, like "train.tsv" instead "train.csv", and maybe some else. And there is no input files, maybe it's good idea to place them here to give to peoples full examples?

**Comment by annaveronika** [comment] 2017-11-10 09:56
@cooltyn If you see any problems or improvements for the tutorial, please consider contributing, we are very happy if you make a pool request.

Also here
https://github.com/catboost/catboost/tree/master/catboost/pytest/data/adult
you can find an example of data files.

Plus formats are described in documentation here:
https://tech.yandex.com/catboost/doc/dg/concepts/input-data-docpage/
Examples are provided there.

**Comment by cooltyn** [comment] 2017-11-10 10:17
try to used compiled versions from here: [https://github.com/catboost/catboost/releases](url)
Win10 x64
`catboost-0.3 fit --learn-set train.csv --test-set test.csv --column-description train.cd` works fine
`catboost-cuda-0.3 fit --learn-set train.csv --test-set test.csv --column-description train.cd` gives error:
> (class TFileError) (╤шёЄхьх эх єфрхЄё  эрщЄш єърчрээ√щ яєЄ№.) st/util/system/file.cpp:613: can't open "/tmp/cat_feature_index.80757456-e083f953-24561154-2.tmp" with mode CreateAlways|WrOnly|Seq (0x00000034)

**Comment by kizill** [comment] 2017-11-10 10:25
@cooltyn You found another bug, thank you 👍  We will fix it in new release.

**Comment by kizill** [comment] 2017-11-23 16:29
We fixed  this bug in version 0.4, you can try it.

**Comment by cooltyn** [comment] 2017-11-24 14:05
Win10 x64,  Python 3.6.2 x64, catboost 0.4.1

At python trying to set `device_type = 'GPU'` at CatBoostClassifier gives error:

> Traceback (most recent call last):
  File "D:\share\cloud\git\net\net.py", line 136, in <module>
    device_type = 'CPU'
  File "C:\Users\cooltyn\AppData\Local\Programs\Python\Python36\lib\site-packages\catboost\core.py", line 1180, in __init__
    super(CatBoostClassifier, self).__init__(params)
  File "C:\Users\cooltyn\AppData\Local\Programs\Python\Python36\lib\site-packages\catboost\core.py", line 483, in __init__
    self._check_params(params)
  File "C:\Users\cooltyn\AppData\Local\Programs\Python\Python36\lib\site-packages\catboost\core.py", line 510, in _check_params
    raise CatboostError("Invalid param `{}`.".format(param))
_catboost.CatboostError: Invalid param `device_type`.

.get_params() gives  me:

> {'allow_writing_files': False, 'name': 'experiment', 'random_strength': 1, 'has_time': False, 'logging_level': 'Silent', 'feature_border_type': 'MinEntropy', 'loss_function': 'Logloss', 'l2_leaf_reg': 3, 'depth': 2, 'learning_rate': 0.15, 'iterations': 300}

Then try command line:

> C:\Users\cooltyn>catboost-0.4.1 fit --learn-set train.csv --test-set test.csv --column-description train.cd
Skipping test eval output
0.1426013846 min passed

> C:\Users\cooltyn>catboost-cuda-0.4.1 fit --learn-set train.csv --test-set test.csv --column-description train.cd
(?AVTUsageException@NLastGetopt@@) atboost/library/getopt/small/last_getopt_support.h:168: failed to parse opt --random-seed value "-599780829": (?AUTFromStringException@@) atboost/util/string/cast.cc:338: Unexpected symbol "-" at pos 0 in string "-599780829".
Try 'catboost-cuda-0.4.1 fit --help' for more information.

> C:\Users\cooltyn>catboost-cuda-0.4 fit --learn-set train.csv --test-set test.csv --column-description train.cd
(?AVTUsageException@NLastGetopt@@) atboost/library/getopt/small/last_getopt_support.h:168: failed to parse opt --random-seed value "-275107413": (?AUTFromStringException@@) atboost/util/string/cast.cc:338: Unexpected symbol "-" at pos 0 in string "-275107413".
Try 'catboost-cuda-0.4 fit --help' for more information.

GPU still not working for me :(

**Comment by kizill** [comment] 2017-11-24 14:12
I'm so sorry, i forget to say that `device_type` became `task_type`.

**Comment by annaveronika** [comment] 2017-11-25 15:35
it's fixed now

**Closed by annaveronika** 2017-11-25 15:35 UTC
Labels: in progress
