### ISSUE TITLE
TypeError: Cannot convert IntegerArray to numpy.ndarray

### ISSUE THREAD

**Issue by tanujdhiman** [catboost/catboost#2473] opened 2023-08-10 09:38 UTC
catboost version: 0.26.1
Operating System: Mac

I am facing this issue for a long time. Can you help me in this?

<img width="858" alt="Screenshot 2023-08-10 at 3 08 13 PM" src="https://github.com/catboost/catboost/assets/56601466/3c9eab56-a1c3-4cd7-b708-32f105415d2f">

**Comment by andrey-khropov** [comment] 2023-08-16 08:45
Duplicate of #2096

**Closed by andrey-khropov** 2023-08-16 08:45 UTC
Labels: duplicate
