### ISSUE TITLE
catboost raise  error when classification

### ISSUE THREAD

**Issue by liningbo** [catboost/catboost#2251] opened 2022-12-20 03:11 UTC
Problem:raise error when classification
catboost version:1.1.1
Operating System:windows 10
CPU:amd 5950x
GPU:nvidia 3090

the erroe as follows:
0:      learn: 0.5330845        test: 0.6196420 best: 0.6196420 (0)     total: 12.5ms   remaining: 1m 13s
Application terminated with error: PyInit__catboost+1833388 (0x7FFE4BFACEBC)
??+0 (0x7FFE4BA4781E)
??+0 (0x7FFE4BBA9104)
PyInit__catboost+9679619 (0x7FFE4C728813)
PyInit__catboost+9655305 (0x7FFE4C722919)
PyInit__catboost+9656493 (0x7FFE4C722DBD)
??+0 (0x7FFE4BC46CA9)
PyInit__catboost+13185172 (0x7FFE4CA805A4)
BaseThreadInitThunk+20 (0x7FFFFC177034)
RtlUserThreadStart+33 (0x7FFFFD9C2651)

(class TCatBoostException) C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/cuda/cuda_util/sort.cpp:166: CUDA error 9: invalid configuration argument

but regression is ok.

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2023-02-03 11:42
this is duplicate of #2003

**Closed by Evgueni-Petrov-aka-espetrov** 2023-02-03 11:42 UTC
Labels: bug, GPU
