### ISSUE TITLE
Got lot of times «Floating point exception (core dumped)» on model.predict

### ISSUE THREAD

**Issue by belonesox** [catboost/catboost#971] opened 2019-08-26 19:38 UTC
Problem: Got lot of times «Floating point exception (core dumped)» on model.predict. 
catboost version:  0.16.5
Operating System: Linux 64

Demo for the bug  — Full Python3 VirtualEnv with pickled data and demo script 
(run wtf.sh)  →  https://cloud.mail.ru/public/5jZr/zZWMU2Qgh

**Comment by david-waterworth** [comment] 2019-10-06 10:35
I'm seeing this a lot as well - I'm not sure if it's fit or predict though. It's only on 1 of my 2 machines (dual 20180Ti GPU), the single 2080Ti doesn't have a problem.

**Comment by sswetank-CS** [comment] 2020-03-26 07:40
Any resolution on this ? or do we know what's the root cause issue here?

**Comment by vectosaurus** [comment] 2020-07-21 19:18
I too am facing this same issue on calling `predict`.

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2020-07-22 06:09
Could you please provide a reproducer, and let us know the CPU model name where you get FPE?
CatBoost 0.23.2 works just fine on Intel(R) Xeon(R) CPU E5-2650 v2.

**Comment by kizill** [comment] 2020-08-06 18:02
I've just found that this bug was fixed exactly in 0.17.5 release. Closing as fixed.

**Closed by kizill** 2020-08-06 18:02 UTC
Labels: eval_formula
