### ISSUE TITLE
Cannot build catboost without 'ya' script

### ISSUE THREAD

**Issue by mxfm** [catboost/catboost#2312] opened 2023-03-03 16:13 UTC
Problem: cannot build catboost
catboost version: 1.1.1
Operating System: Linux

I cannot build catboost following project instructions (https://catboost.ai/en/docs/installation/python-installation-method-build-from-source-linux-macos) because there is no 'ya' script in downloaded archive. According to old issues this file was distributed for some time (or at least there was a way to get it from other sources) but currently this script is missing from archive.

EDIT: Also, there is no information how to get the script from build instructions. If the script is not officially distributed for some reason, then documentation should be updated.

**Comment by andrey-khropov** [comment] 2023-05-11 02:55
Duplicate of #2349. See https://github.com/catboost/catboost/issues/2349#issuecomment-1543254937

**Closed by andrey-khropov** 2023-05-11 02:55 UTC
Labels: build
