### ISSUE TITLE
"The kernel appears to have died. It will restart automatically." When using GPU

### ISSUE THREAD

**Issue by DanEllen** [catboost/catboost#1753] opened 2021-06-26 16:18 UTC
Problem: Got this error message on Jupyter Notebook when using GPU on the toy example given in the Catboost website.
catboost version: 0.26
Operating System: Windows 10 Pro 64 bits
CPU: Intel Core i7-6700
# GPU: NVDIA GeForce  GTX 1660 Ti

Hello when trying to run the toy example for GPU in https://catboost.ai/docs/search/?query=gpu on my Jupyter Notebook I get a popup with the error "The kernel appears to have died. It will restart automatically." The terminal says "[I 11:10:01.969 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel a02196d1-b9d6-4107-95fa-9a1f8c03de22 restarted"

My NVDIA drivers are 471.11. Not sure what could be causing this, please advice.

Thank you,

**Comment by kizill** [comment] 2021-07-05 21:39
Closing as duplicate of #1735 , more info here 😺

**Closed by kizill** 2021-07-05 21:39 UTC
