### ISSUE TITLE
 Installation failed in RStudio - file(url, path Failed

### ISSUE THREAD

**Issue by kamaulindhardt** [catboost/catboost#1834] opened 2021-09-02 10:32 UTC
**Hi CatBoost,** 

Hope you coun help, please. 

Problem: Installation failed in RStudio
catboost version: irrelevant 
Operating System: macOS Big Sur 
CPU: irreverent 
GPU: irreverent 

Running `devtools::install_github('catboost/catboost', subdir = 'catboost/R-package')` for installing catboost resulted in error as the path failed? How come? Are there other ways of installing the catboost R package?

```
devtools::install_github('catboost/catboost', subdir = 'catboost/R-package')
Downloading GitHub repo catboost/catboost@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/catboost/catboost/tarball/HEAD' failed
```

Thank you,

All the best,
Kamau Lindhardt

**Comment by Glemhel** [comment] 2021-09-02 14:17
Hello, Kamau! Thanks for reporting!

We reproduced this bug on the same setup and will start working on it soon. However, some quick workarounds which may help exist.

Instructions on how to install CatBoost in R: https://catboost.ai/docs/concepts/r-installation.html
The easiest way is to install the released version. For latest version (assuming you already have 'devtools'), do this:
`devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.26.1/catboost-R-Darwin-0.26.1.tgz', INSTALL_opts = c("--no-multiarch", "--no-test-load"))`
You can also try Conda install as well, the second way in the link above.

For `devtools::install_github` the following might do:
1. Inside R: `devtools::install_github("r-lib/remotes")`
2. Restart R
3. Try inside R again: `devtools::install_github('catboost/catboost',  subdir = 'catboost/R-package')`.
However, as for me, another error `shared object ‘libcatboostr.dylib’ not found` appeared, which also will be investigated.

**Comment by kamaulindhardt** [comment] 2021-09-20 20:52
Hi @Glemhel 

Have you had time to look into this issue? Indeed I still get the error: ```shared object ‘libcatboostr.dylib’ not found``` 

When I use this installation: 

```devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.16.5/catboost-R-Windows-0.16.5.tgz', INSTALL_opts = c("--no-multiarch", "--no-test-load"))``` 

I get this error:  

```
Downloading package from url: https://github.com/catboost/catboost/releases/download/v0.16.5/catboost-R-Windows-0.16.5.tgz
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://github.com/catboost/catboost/releases/download/v0.16.5/catboost-R-Windows-0.16.5.tgz' failed
Warning message:
1 components of `...` were not used.

We detected these problematic arguments:
* `INSTALL_opts`

Did you misspecify an argument? 
```

Thank you!
All the best,
Kamau

**Comment by Glemhel** [comment] 2021-09-20 23:44
Hello, @kamaulindhardt! Glad you succeed!
>Indeed I still get the error: `shared object ‘libcatboostr.dylib’ not found`

This error should be fixed in next release. The reason for that was incorrect type of dynamic library for MacOS. 


I will also reply about the issue with downloading from github soon.

**Comment by andrey-khropov** [comment] 2021-11-04 04:29
Deployed in release 1.0.2.

**Closed by andrey-khropov** 2021-11-04 04:29 UTC
Labels: R
