### ISSUE TITLE
windows build problems

### ISSUE THREAD

**Issue by dmvoro** [catboost/catboost#1418] opened 2020-09-10 14:51 UTC
Problem: error when reaching 41% of build
catboost version: 0.24.1
Operating System: Win7
CPU: i7 3.7 Ghz

Firstly I run Developer Command Prompt for MSVS 2017
vcvars64.bat
cd C:\devel\catboost
ya make -r catboost\libs\model_interface -o -DHAVE_CUDA=no

After build started I have this error
|41.5%| [CC] $(S)/contrib/libs/clapack/ssbevd.c
|41.5%| [R6] $(B)/library/cpp/json/fast_sax/parser.rl6.cpp
------- [R6] {FAILED} $(B)/library/cpp/json/fast_sax/parser.rl6.cpp
command C:\Users\Dmitry\.ya\build\build_root\s57r\000a14/contrib/tools/ragel6/ra
gel6.exe -CT0 -L -IC:\devel\catboost -o C:\Users\Dmitry\.ya\build\build_root\s57
r\000a14/library/cpp/json/fast_sax/parser.rl6.cpp C:\devel\catboost/library/cpp/
json/fast_sax/parser.rl6 failed with exit code -1073741819 in C:\Users\Dmitry\.y
a\build\build_root\s57r\000a14
------- [R6] {tool, FAILED} $(B)/util/_/datetime/parser.rl6.cpp
command C:\Users\Dmitry\.ya\build\build_root\s57r\000a3a/contrib/tools/ragel6/ra
gel6.exe -CT0 -L -IC:\devel\catboost -o C:\Users\Dmitry\.ya\build\build_root\s57
r\000a3a/util/_/datetime/parser.rl6.cpp C:\devel\catboost/util/datetime/parser.r
l6 failed with exit code -1073741819 in C:\Users\Dmitry\.ya\build\build_root\s57
r\000a3a
|41.6%| [R6] $(B)/library/cpp/tokenizer/nlptok_v3.rl6.cpp
|41.6%| [R6] $(B)/library/cpp/tokenizer/nlptok_v3.rl6.cpp
Failed

**Comment by dmvoro** [comment] 2020-09-11 09:12
As I see there is a bug with no slash "\Dmitry.ya\".

**Comment by dmvoro** [comment] 2020-09-14 17:12
As I see there is a bug with no slash "\Dmitry.ya\". Should be "Dmitry\.ya\"

**Comment by dmvoro** [comment] 2020-09-14 17:13
As I see there is a bug with no slash "\Dmitry.ya\". Should be "Dmitry\ .ya\"

**Comment by dmvoro** [comment] 2020-11-20 12:11
Can you please fix this bug?

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2020-11-25 09:25
With the latest trunk I cannot reproduce this bug.
Could you please check?

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2020-11-26 05:15
Could you please check that Data Execution Prevention is disabled for C:\Users\Dmitry.ya\build\build_root\dmbn\000a87/contrib/tools/ragel6/ragel6.exe?

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2020-11-26 07:30
We will look into this issue.

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2020-11-26 12:43
As experiment, could you please do set YA_CACHE_DIR=%TMP% and then try ya make etc.?

**Comment by dmvoro** [comment] 2020-11-26 16:06
I make this, a bit better but another error
|48.1%| [R6] $(B)/library/cpp/json/fast_sax/parser.rl6.cpp
|48.2%| [AR] $(B)/catboost/private/libs/data_types/private-libs-data_types.lib{,
------- [R6] {tool, FAILED} $(B)/util/_/datetime/parser.rl6.cpp
command C:\Users\Dmitry\AppData\Local\Temp\build\build_root\vll1\000a87/contrib/
tools/ragel6/ragel6.exe -CT0 -L -IC:\devel\catboost -o C:\Users\Dmitry\AppData\L
ocal\Temp\build\build_root\vll1\000a87/util/_/datetime/parser.rl6.cpp C:\devel\c
atboost/util/datetime/parser.rl6 failed with exit code -1073741819 in C:\Users\D
mitry\AppData\Local\Temp\build\build_root\vll1\000a87
|48.2%| [AR] $(B)/catboost/private/libs/data_types/private-libs-data_types.lib{,
------- [R6] {FAILED} $(B)/library/cpp/json/fast_sax/parser.rl6.cpp
command C:\Users\Dmitry\AppData\Local\Temp\build\build_root\vll1\000a61/contrib/
tools/ragel6/ragel6.exe -CT0 -L -IC:\devel\catboost -o C:\Users\Dmitry\AppData\L
ocal\Temp\build\build_root\vll1\000a61/library/cpp/json/fast_sax/parser.rl6.cpp
C:\devel\catboost/library/cpp/json/fast_sax/parser.rl6 failed with exit code -10
73741819 in C:\Users\Dmitry\AppData\Local\Temp\build\build_root\vll1\000a61
|48.2%| [AR] $(B)/catboost/private/libs/data_types/private-libs-data_types.lib{,
Failed

**Comment by kizill** [comment] 2020-11-27 07:10
Hello, i'm now worried that you may have some processor instruction sets incompatibility problems or allocator problem. Please send us full processor id or your cpuid information.

**Comment by dmvoro** [comment] 2020-11-27 10:56
I download CPU-Z and thats a report from it.

Processors Information
-------------------------------------------------------------------------

Socket 1			ID = 0
	Number of cores		4 (max 4)
	Number of threads	8 (max 8)
	Manufacturer		GenuineIntel
	Name			Intel Core i7 2600
	Codename		Sandy Bridge
	Specification		Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
	Package (platform ID)	Socket 1155 LGA (0x1)
	CPUID			6.A.7
	Extended CPUID		6.2A
	Core Stepping		D2
	Technology		32 nm
	TDP Limit		95.0 Watts
	Tjmax			98.0 °C
	Core Speed		1596.2 MHz
	Multiplier x Bus Speed	16.0 x 99.8 MHz
	Base frequency (cores)	99.8 MHz
	Base frequency (ext.)	99.8 MHz
	Stock frequency		3400 MHz
	Instructions sets	MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EM64T, VT-x, AES, AVX
	Microcode Revision	0x23
	L1 Data cache		4 x 32 KBytes, 8-way set associative, 64-byte line size
	L1 Instruction cache	4 x 32 KBytes, 8-way set associative, 64-byte line size
	L2 cache		4 x 256 KBytes, 8-way set associative, 64-byte line size
	L3 cache		8 MBytes, 16-way set associative, 64-byte line size
	Max CPUID level		0000000Dh
	Max CPUID ext. level	80000008h
	Cache descriptor	Level 1, D, 32 KB, 2 thread(s)
	Cache descriptor	Level 1, I, 32 KB, 2 thread(s)
	Cache descriptor	Level 2, U, 256 KB, 2 thread(s)
	Cache descriptor	Level 3, U, 8 MB, 16 thread(s)
	FID/VID Control		yes

**Comment by dmvoro** [comment] 2020-12-09 13:40
Maybe you have some another advices for me how to fix this error? I want to try

**Comment by kizill** [comment] 2021-01-27 20:51
Our devtools team said they won't fix bugs on deprecated versions of Windows, sorry :(
My next suggestion is to try hacking the ragel6 default allocator here: https://github.com/catboost/catboost/blob/master/contrib/tools/ragel6/ya.make#L16
by setting ```ALLOCATOR(LF)```

**Comment by kizill** [comment] 2021-01-29 08:00
Fixed default allocator in 3adde9fc84fb8590c792313c32a1d0983898ca29

**Closed by kizill** 2021-01-29 08:00 UTC
Labels: build issues
