### ISSUE TITLE
Catboost spark fit error java.lang.ClassCastException

### ISSUE THREAD

**Issue by vitormanita** [catboost/catboost#2256] opened 2022-12-27 10:17 UTC
**Problem:** `net.razorvine.pickle.objects.TimeDelta cannot be cast to java.time.Duration`
**catboost version:** `1.0.6`
**Operating System:** `10.4 LTS ML (includes Apache Spark 3.2.1, Scala 2.12)`

Hi, I'm trying to test `catboost_spark` in a Databricks notebook using the example from the official documentation: https://catboost.ai/en/docs/concepts/spark-quickstart-python#binary-classification

When I run this command:
```
classifier.fit(dataset=trainPool, evalDatasets=[evalPool])
```

The following error is raised:
```
java.lang.ClassCastException: net.razorvine.pickle.objects.TimeDelta cannot be cast to java.time.Duration

...

Py4JJavaError: An error occurred while calling o18779.w.
: java.lang.ClassCastException: net.razorvine.pickle.objects.TimeDelta cannot be cast to java.time.Duration
	at ai.catboost.spark.params.DurationParam.w(Helpers.scala:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
```

I believe there is a [similar issue](https://github.com/catboost/catboost/issues/2051) to this but it is now closed. Thank you in advance for the help.

**Comment by Reg1ss** [comment] 2023-01-16 11:54
same issue from Spark 3.2.0, Scala 2.12, CatBoost 1.1.1

**Comment by ssabzevari-antuit** [comment] 2024-11-27 19:00
Same issue with ai.catboost:catboost-spark_3.4_2.12:1.2.5.
This also causes com.microsoft.azure:synapseml_2.12:0.11.3 to fail. I get AttributeError: module 'com.microsoft.azure.synapse.ml.lightgbm' has no attribute 'LightGBMRegressionModel'

However when I remove the catboost one everything is working fine.

**Comment by andrey-khropov** [comment] 2024-11-30 15:36
Duplicate of #2051

**Closed by andrey-khropov** 2024-11-30 15:36 UTC
Labels: Spark
