### ISSUE TITLE
Can't convert bad label back to class name

### ISSUE THREAD

**Issue by VladislavMalkov** [catboost/catboost#523] opened 2018-10-31 21:41 UTC
Problem: {
Hi, I'm trying to use Catboost in Python, but I faced a problem:

CatboostError                             Traceback (most recent call last)
<ipython-input-12-4203155693dc> in <module>
     27 #model2.fit(pool)
     28 # Get predicted classes
---> 29 preds_class = model1.predict(test_data)
     30 # Get predicted probabilities for each class
     31 preds_proba = model1.predict_proba(test_data)

c:\users\vlad\appdata\local\programs\python\python36\lib\site-packages\catboost\core.py in predict(self, data, prediction_type, ntree_start, ntree_end, thread_count, verbose)
   2198         prediction : numpy.array
   2199         """
-> 2200         return self._predict(data, prediction_type, ntree_start, ntree_end, thread_count, verbose)
   2201 
   2202     def predict_proba(self, data, ntree_start=0, ntree_end=0, thread_count=-1, verbose=None):

c:\users\vlad\appdata\local\programs\python\python36\lib\site-packages\catboost\core.py in _predict(self, data, prediction_type, ntree_start, ntree_end, thread_count, verbose)
   1277         # TODO(kirillovs): very bad solution. user should be able to use custom multiclass losses
   1278         if loss_function_type is not None and (loss_function_type == 'MultiClass' or loss_function_type == 'MultiClassOneVsAll'):
-> 1279             return np.transpose(self._base_predict_multi(data, prediction_type, ntree_start, ntree_end, thread_count, verbose))
   1280         predictions = np.array(self._base_predict(data, prediction_type, ntree_start, ntree_end, thread_count, verbose))
   1281         if prediction_type == 'Probability':

c:\users\vlad\appdata\local\programs\python\python36\lib\site-packages\catboost\core.py in _base_predict_multi(self, pool, prediction_type, ntree_start, ntree_end, thread_count, verbose)
    883 
    884     def _base_predict_multi(self, pool, prediction_type, ntree_start, ntree_end, thread_count, verbose):
--> 885         return self._object._base_predict_multi(pool, prediction_type, ntree_start, ntree_end, thread_count, verbose)
    886 
    887     def _staged_predict_iterator(self, pool, prediction_type, ntree_start, ntree_end, eval_period, thread_count, verbose):

_catboost.pyx in _catboost._CatBoost._base_predict_multi()

_catboost.pyx in _catboost._CatBoost._base_predict_multi()

_catboost.pyx in _catboost._convert_to_visible_labels()

CatboostError: c:/goagent/pipelines/buildmaster/catboost.git/catboost/libs/labels/external_label_helper.cpp:80: Can't convert bad label back to class name.
}
catboost version: {0.10.4.1}
Operating System: {Windows 10}
GPU{RX570}

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2018-11-15 09:02
Hi Vladislav! Could you please provide a reproducer?

**Comment by GuillemGSubies** [comment] 2018-11-23 11:57
I have the same problem. I managed to reproduce it this way:

```
from sklearn.datasets import load_iris
from catboost import CatBoostClassifier
from skopt import BayesSearchCV
X ,y = load_iris(return_X_y=True)
opt = BayesSearchCV(
    CatBoostClassifier(loss_function='MultiClass'),
    {
        'iterations': (2,20),  
        'depth': (2,20),
    },
    n_iter=32
)
opt.fit(X, y)
predictions = opt.predict_proba(X)
predictions
```

Catboost version: 0.11.1
sklearn version: 0.19.1
skop version: 0.5.2

Error log:

```
0:	learn: -0.6735301	total: 1.05ms	remaining: 9.45ms
1:	learn: -0.6582676	total: 6.63ms	remaining: 26.5ms
2:	learn: -0.6440735	total: 9.86ms	remaining: 23ms
3:	learn: -0.6254035	total: 13.1ms	remaining: 19.6ms
4:	learn: -0.6112127	total: 16ms	remaining: 16ms
5:	learn: -0.5974237	total: 19.5ms	remaining: 13ms
6:	learn: -0.5840132	total: 21.1ms	remaining: 9.05ms
7:	learn: -0.5713526	total: 22.6ms	remaining: 5.64ms
8:	learn: -0.5557081	total: 23.4ms	remaining: 2.6ms
9:	learn: -0.5452203	total: 25.8ms	remaining: 0us

---------------------------------------------------------------------------
CatboostError                             Traceback (most recent call last)
<ipython-input-5-04b13eb64792> in <module>
     11     n_iter=32
     12 )
---> 13 opt.fit(X, y)
     14 predictions = opt.predict_proba(X)
     15 predictions

/opt/conda/lib/python3.6/site-packages/skopt/searchcv.py in fit(self, X, y, groups, callback)
    652                 optim_result = self._step(
    653                     X, y, search_space, optimizer,
--> 654                     groups=groups, n_points=n_points_adjusted
    655                 )
    656                 n_iter -= n_points

/opt/conda/lib/python3.6/site-packages/skopt/searchcv.py in _step(self, X, y, search_space, optimizer, groups, n_points)
    548         refit = self.refit
    549         self.refit = False
--> 550         self._fit(X, y, groups, params_dict)
    551         self.refit = refit
    552 

/opt/conda/lib/python3.6/site-packages/skopt/searchcv.py in _fit(self, X, y, groups, parameter_iterable)
    401                 error_score=self.error_score
    402             )
--> 403             for parameters in parameter_iterable
    404             for train, test in cv_iter)
    405 

/opt/conda/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in __call__(self, iterable)
    777             # was dispatched. In particular this covers the edge
    778             # case of Parallel used with an exhausted iterator.
--> 779             while self.dispatch_one_batch(iterator):
    780                 self._iterating = True
    781             else:

/opt/conda/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in dispatch_one_batch(self, iterator)
    623                 return False
    624             else:
--> 625                 self._dispatch(tasks)
    626                 return True
    627 

/opt/conda/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in _dispatch(self, batch)
    586         dispatch_timestamp = time.time()
    587         cb = BatchCompletionCallBack(dispatch_timestamp, len(batch), self)
--> 588         job = self._backend.apply_async(batch, callback=cb)
    589         self._jobs.append(job)
    590 

/opt/conda/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py in apply_async(self, func, callback)
    109     def apply_async(self, func, callback=None):
    110         """Schedule a func to be run"""
--> 111         result = ImmediateResult(func)
    112         if callback:
    113             callback(result)

/opt/conda/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py in __init__(self, batch)
    330         # Don't delay the application, to avoid keeping the input
    331         # arguments in memory
--> 332         self.results = batch()
    333 
    334     def get(self):

/opt/conda/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in __call__(self)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
    132 
    133     def __len__(self):

/opt/conda/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in <listcomp>(.0)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
    132 
    133     def __len__(self):

/opt/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py in _fit_and_score(estimator, X, y, scorer, train, test, verbose, parameters, fit_params, return_train_score, return_parameters, return_n_test_samples, return_times, error_score)
    486         fit_time = time.time() - start_time
    487         # _score will return dict if is_multimetric is True
--> 488         test_scores = _score(estimator, X_test, y_test, scorer, is_multimetric)
    489         score_time = time.time() - start_time - fit_time
    490         if return_train_score:

/opt/conda/lib/python3.6/site-packages/sklearn/model_selection/_validation.py in _score(estimator, X_test, y_test, scorer, is_multimetric)
    526             score = scorer(estimator, X_test)
    527         else:
--> 528             score = scorer(estimator, X_test, y_test)
    529 
    530         if hasattr(score, 'item'):

/opt/conda/lib/python3.6/site-packages/sklearn/metrics/scorer.py in _passthrough_scorer(estimator, *args, **kwargs)
    242 def _passthrough_scorer(estimator, *args, **kwargs):
    243     """Function that wraps estimator.score"""
--> 244     return estimator.score(*args, **kwargs)
    245 
    246 

/opt/conda/lib/python3.6/site-packages/catboost/core.py in score(self, X, y)
   2317         correct = []
   2318         y = np.array(y)
-> 2319         for i, val in enumerate(self.predict(X)):
   2320             correct.append(1 * (y[i] == val))
   2321         return np.mean(correct)

/opt/conda/lib/python3.6/site-packages/catboost/core.py in predict(self, data, prediction_type, ntree_start, ntree_end, thread_count, verbose)
   2188         prediction : numpy.array
   2189         """
-> 2190         return self._predict(data, prediction_type, ntree_start, ntree_end, thread_count, verbose)
   2191 
   2192     def predict_proba(self, data, ntree_start=0, ntree_end=0, thread_count=-1, verbose=None):

/opt/conda/lib/python3.6/site-packages/catboost/core.py in _predict(self, data, prediction_type, ntree_start, ntree_end, thread_count, verbose)
   1267         # TODO(kirillovs): very bad solution. user should be able to use custom multiclass losses
   1268         if loss_function_type is not None and (loss_function_type == 'MultiClass' or loss_function_type == 'MultiClassOneVsAll'):
-> 1269             return np.transpose(self._base_predict_multi(data, prediction_type, ntree_start, ntree_end, thread_count, verbose))
   1270         predictions = np.array(self._base_predict(data, prediction_type, ntree_start, ntree_end, thread_count, verbose))
   1271         if prediction_type == 'Probability':

/opt/conda/lib/python3.6/site-packages/catboost/core.py in _base_predict_multi(self, pool, prediction_type, ntree_start, ntree_end, thread_count, verbose)
    873 
    874     def _base_predict_multi(self, pool, prediction_type, ntree_start, ntree_end, thread_count, verbose):
--> 875         return self._object._base_predict_multi(pool, prediction_type, ntree_start, ntree_end, thread_count, verbose)
    876 
    877     def _staged_predict_iterator(self, pool, prediction_type, ntree_start, ntree_end, eval_period, thread_count, verbose):

_catboost.pyx in _catboost._CatBoost._base_predict_multi()

_catboost.pyx in _catboost._CatBoost._base_predict_multi()

_catboost.pyx in _catboost._convert_to_visible_labels()

CatboostError: catboost/libs/labels/external_label_helper.cpp:80: Can't convert bad label back to class name.

```

I will try to replicate it with GridSearchCV so the bug is easier to find

**Comment by VladislavMalkov** [comment] 2018-11-23 12:05
I fixed it. I just used catboost 0.5.2.1 and it works fine

**Comment by canglangshushu** [comment] 2018-12-03 17:04
@annaveronika @VladislavMalkov @GuillemGSubies @Evgueni-Petrov-aka-espetrov 
I also encountered the same problem in version 0.10. I tried version 0.5.2.1, which was incompatible with versions 0.10 and 0.11. How can I solve this problem?

**Comment by GuillemGSubies** [comment] 2018-12-05 09:56
I have made some experiments and this started to happen in version 0.10.0 and happens always you use GridSearchCV, BayesSearchCV, etc.

Reading the patch notes from 0.10.0 this makes sense because you introduced support to GridSearchCV

**Comment by radrow** [comment] 2018-12-05 09:57
I have encountered this issue in version 0.5.2.1 as well

**Comment by kizill** [comment] 2018-12-05 10:08
We apologize for such long inactivity, we'll fix this in a matter of days. After fixing, we are planning to do a minor release with this fix.

**Comment by andrey-khropov** [comment] 2018-12-06 14:22
The fix will be in the main branch today, meanwhile the workaround is to specify the number of classes explicitly using classes_count parameter in CatBoostClassifier constructor, like that:


    opt = GridSearchCV(
        CatBoostClassifier(loss_function='MultiClass', classes_count=len(set(y))),
        {
            'iterations': (2,20),  
            'depth': (2,10),
        }
    )
    opt.fit(X, y)
    predictions = opt.predict_proba(X)
    predictions

**Comment by canglangshushu** [comment] 2018-12-06 14:53
@GuillemGSubies 
I'm recoding the class notation by saying 0,1,2,3..."clf=CatBoostClassifier(loss_function='MultiClass') clf.predict(data,prediction_type='Class')" works well, so I think the idea of @andrey-khropov  is good, by knowing the class length to generate a sequence of 0,1,2,3... to replace the original class symbol.So this is the problem that I test predict (data,prediction_type='Class')) won't work,Hopefully this will help you

**Comment by GuillemGSubies** [comment] 2018-12-07 08:09
That works, thanks you very much!

**Comment by AlexRig** [comment] 2018-12-10 18:31
> The fix will be in the main branch today, meanwhile the workaround is to specify the number of classes explicitly using classes_count parameter in CatBoostClassifier constructor, like that:
> 
> ```
> opt = GridSearchCV(
>     CatBoostClassifier(loss_function='MultiClass', classes_count=len(set(y))),
>     {
>         'iterations': (2,20),  
>         'depth': (2,10),
>     }
> )
> opt.fit(X, y)
> predictions = opt.predict_proba(X)
> predictions
> ```

 I've tried using this work around but I'm now being told "If classes count is specified each target label should be nonnegative integer in [0,..,classes_count - 1]" when I try and fit. My target feature has 8 classes and I have passed a list of indices to cat_features. Any ideas?

**Comment by kizill** [comment] 2018-12-10 18:47
Bugfix released in 0.11.2

**Closed by kizill** 2018-12-10 18:47 UTC
Labels: bug, in progress

**Comment by andrey-khropov** [comment] 2018-12-10 18:56
> > The fix will be in the main branch today, meanwhile the workaround is to specify the number of classes explicitly using classes_count parameter in CatBoostClassifier constructor, like that:
> > ```
> > opt = GridSearchCV(
> >     CatBoostClassifier(loss_function='MultiClass', classes_count=len(set(y))),
> >     {
> >         'iterations': (2,20),  
> >         'depth': (2,10),
> >     }
> > )
> > opt.fit(X, y)
> > predictions = opt.predict_proba(X)
> > predictions
> > ```
> 
> I've tried using this work around but I'm now being told "If classes count is specified each target label should be nonnegative integer in [0,..,classes_count - 1]" when I try and fit. My target feature has 8 classes and I have passed a list of indices to cat_features. Any ideas?

Do you specify labels using python data structures or by loading from data files in catboost format (https://tech.yandex.com/catboost/doc/dg/concepts/input-data-docpage/)?

The error message sounds pretty self-explanatory to me. If you specify 'classes_count' all your label data must contain only integers specifying class indices (from 0 to 'classes_count - 1'). So your labels must be containing some other data.

> I have passed a list of indices to cat_features

cat_features is unrelated to this issue. It is used to specify types of features (X), not target/label (y).

Anyway, new release https://github.com/catboost/catboost/releases/tag/v0.11.2 contains the proper fix.

**Comment by AlexRig** [comment] 2018-12-10 19:02
> Bugfix released in 0.11.2

I've just done a `conda install catboost` and it's pulled 11.1 again?

**Comment by AlexRig** [comment] 2018-12-10 19:12
> > > The fix will be in the main branch today, meanwhile the workaround is to specify the number of classes explicitly using classes_count parameter in CatBoostClassifier constructor, like that:
> > > ```
> > > opt = GridSearchCV(
> > >     CatBoostClassifier(loss_function='MultiClass', classes_count=len(set(y))),
> > >     {
> > >         'iterations': (2,20),  
> > >         'depth': (2,10),
> > >     }
> > > )
> > > opt.fit(X, y)
> > > predictions = opt.predict_proba(X)
> > > predictions
> > > ```
> > 
> > 
> > I've tried using this work around but I'm now being told "If classes count is specified each target label should be nonnegative integer in [0,..,classes_count - 1]" when I try and fit. My target feature has 8 classes and I have passed a list of indices to cat_features. Any ideas?
> 
> Do you specify labels using python data structures or by loading from data files in catboost format (https://tech.yandex.com/catboost/doc/dg/concepts/input-data-docpage/)?
> 
> The error message sounds pretty self-explanatory to me. If you specify 'classes_count' all your label data must contain only integers specifying class indices (from 0 to 'classes_count - 1'). So your labels must be containing some other data.
> 
> > I have passed a list of indices to cat_features
> 
> cat_features is unrelated to this issue. It is used to specify types of features (X), not target/label (y).
> 
> Anyway, new release https://github.com/catboost/catboost/releases/tag/v0.11.2 contains the proper fix.

I'm passing a target feature which contains the integers (classifications) 1, 2, 3, 4, 5, 6, 7, 8?

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2018-12-11 04:16
It might be since class numbers start from 0.
