### ISSUE TITLE
there an error in the 0.26 of catboost 

### ISSUE THREAD

**Issue by lastadreamer** [catboost/catboost#1738] opened 2021-06-09 14:31 UTC
BUG:
catboost version:
Operating System:

in the version 0.26 of catboost, if you try to fit module by GPU,  it will interrupte the kernel

**Comment by DanielLumb** [comment] 2021-06-10 10:12
This might be a duplicate of #1735, which also lists more details about the issue.

**Comment by kizill** [comment] 2021-06-10 10:20
Closing as duplicate of #1735

**Closed by kizill** 2021-06-10 10:20 UTC
