### ISSUE TITLE
ld.lld: error: undefined symbol XXX referenced by - ninja

### ISSUE THREAD

**Issue by lijunruan** [catboost/catboost#2358] opened 2023-04-21 06:38 UTC
Problem:ld.lld: error: undefined symbol XXX referenced by - ninja
catboost version: 1.1.1
Operating System: aarch64 Ubuntu20.04
CPU: ARM
GPU:No
Error:
root@instance-aarch: **cmake ./ -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=build/toolchains/clang.toolchain -DPython3_ROOT_DIR=/usr/lib/python3/dist-packages/**

root@instance-aarch:**/home/ubuntu/4/catboost# ninja -C ./ catboost**
ninja: Entering directory `./'
[2752/3724] Linking CXX executable contrib/tools/flatc/bin/flatc
#### FAILED: contrib/tools/flatc/bin/flatc
: && /usr/bin/clang++ -fexceptions   -fno-common   -fcolor-diagnostics   -faligned-allocation   -fdebug-default-version=4   -ffunction-sections   -fdata-sections   -Wall   -Wextra   -Wno-parentheses   -Wno-implicit-const-int-float-conversion   -Wno-unknown-warning-option   -pipe   -D_THREAD_SAFE   -D_PTHREADS   -D_REENTRANT   -D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES   -D_LARGEFILE_SOURCE   -D__STDC_CONSTANT_MACROS   -D__STDC_FORMAT_MACROS   -D__LONG_LONG_SUPPORTED  -D_GNU_SOURCE -DLIBCXX_BUILDING_LIBCXXRT -fuse-init-array -D_FILE_OFFSET_BITS=64 -fsigned-char   -Woverloaded-virtual   -Wimport-preprocessor-directive-pedantic   -Wno-undefined-var-template   -Wno-return-std-move   -Wno-defaulted-function-deleted   -Wno-pessimizing-move   -Wno-deprecated-anon-enum-enum-conversion   -Wno-deprecated-enum-enum-conversion   -Wno-deprecated-enum-float-conversion   -Wno-ambiguous-reversed-operator   -Wno-deprecated-volatile  -O3 -DNDEBUG -fuse-ld=lld    -nodefaultlibs -ldl -lrt -Wl,--no-as-needed -fPIC -lpthread contrib/tools/flatc/bin/CMakeFiles/flatc.dir/__/__/__/libs/flatbuffers/src/flatc_main.cpp.o contrib/tools/flatc/bin/CMakeFiles/flatc.dir/__vcs_version__.c.o -o contrib/tools/flatc/bin/flatc  contrib/libs/flatbuffers/flatc/liblibs-flatbuffers-flatc.a  library/cpp/malloc/jemalloc/libcpp-malloc-jemalloc.a  library/cpp/malloc/api/libcpp-malloc-api.a  contrib/libs/jemalloc/libcontrib-libs-jemalloc.a  contrib/libs/cxxsupp/libcxx/liblibs-cxxsupp-libcxx.a  contrib/libs/cxxsupp/libcxxabi-parts/liblibs-cxxsupp-libcxxabi-parts.a  contrib/libs/cxxsupp/libcxxrt/liblibs-cxxsupp-libcxxrt.a  contrib/libs/cxxsupp/builtins/liblibs-cxxsupp-builtins.a  contrib/libs/libunwind/libcontrib-libs-libunwind.a  -lc -lm && :
**ld.lld: error: undefined symbol: __aarch64_ldadd8_relax**
\>>> referenced by jemalloc.c
\>>>               jemalloc.c.o:(a0ialloc) in archive contrib/libs/jemalloc/libcontrib-libs-jemalloc.a
\>>> referenced by jemalloc.c
\>>>               jemalloc.c.o:(a0idalloc) in archive contrib/libs/jemalloc/libcontrib-libs-jemalloc.a
\>>> referenced by jemalloc.c
\>>>               jemalloc.c.o:(do_realloc_nonnull_zero) in archive contrib/libs/jemalloc/libcontrib-libs-jemalloc.a
\>>> referenced 83 more times

**ld.lld: error: undefined symbol: __aarch64_ldadd4_rel**
\>>> referenced by jemalloc.c
\>>>               jemalloc.c.o:(je_arena_init) in archive contrib/libs/jemalloc/libcontrib-libs-jemalloc.a
\>>> referenced by jemalloc.c
\>>>               jemalloc.c.o:(je_arena_choose_hard) in archive contrib/libs/jemalloc/libcontrib-libs-jemalloc.a
\>>> referenced by jemalloc.c
\>>>               jemalloc.c.o:(je_arena_choose_hard) in archive contrib/libs/jemalloc/libcontrib-libs-jemalloc.a
\>>> referenced 2 more times

**Comment by Longcuirong** [comment] 2023-04-23 10:51
cmake --build catboost，when i do this in windows 10, there also occur 
![image](https://user-images.githubusercontent.com/18166739/233835568-9347749d-18a5-4203-ad37-e6a417e38ad3.png)

**Comment by andrey-khropov** [comment] 2023-04-23 22:34
> cmake --build catboost，when i do this in windows 10, there also occur
> 
> \catboost\contrib\libs\cxxsupp\libcxx\src\include\to_chars_floating_ point.h(39,26): error C3861: “size”: 找不到标识符 (编译源文件
> 
> \contrib\libs\cxxsupp\libcxx\src\support\win32\thread_win32 .cpp(246,52): error C2275: “std::__y1::chrono::milliseconds”: 将此类型用作表达式非法

Please create a separate issue for that because the nature of this error is completely unrelated to undefined symbols on Linux aarch64. And describe all the commands that you run.

We now have a convinient wrapper for CMake + Ninja called [`build_native.py`](https://github.com/catboost/catboost/blob/master/build/build_native.py) which can be called like that:

```
python .\build_native.py --build-root-dir <build_root_dir> --targets <,-separated target_list>
```

List of targets with their meaning can be found [here](https://github.com/catboost/catboost/issues/2091#issuecomment-1486551204).

`build_native.py` supports `--dry-run` and `--verbose` options so you can just see what commands will be actually executed without actually running them and `--help` will display the detailed help with all the options.

**Comment by lijunruan** [comment] 2023-04-26 10:28
ubuntu@instance-aarch:~/2/catboost/build$ python build_native.py --build-root-dir ./ --targets catboost
-- Build files have been written to: /home/ubuntu/2/catboost/build
INFO:root:Running "ninja -C ./ catboost"
ninja: Entering directory `./'
[2587/3561] Linking CXX executable contrib/tools/flatc/bin/flatc
FAILED: contrib/tools/flatc/bin/flatc
: && /usr/bin/clang++ -fexceptions   -fno-common   -fcolor-diagnostics   -faligned-allocation   -fdebug-default-version=4   -ffunction-sections   -fdata-sections   -Wall   -Wextra   -Wno-parentheses   -Wno-implicit-const-int-float-conversion   -Wno-unknown-warning-option   -pipe   -D_THREAD_SAFE   -D_PTHREADS   -D_REENTRANT   -D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES   -D_LARGEFILE_SOURCE   -D__STDC_CONSTANT_MACROS   -D__STDC_FORMAT_MACROS   -D__LONG_LONG_SUPPORTED  -D_GNU_SOURCE -DLIBCXX_BUILDING_LIBCXXRT -fuse-init-array -D_FILE_OFFSET_BITS=64 -fsigned-char   -Woverloaded-virtual   -Wimport-preprocessor-directive-pedantic   -Wno-undefined-var-template   -Wno-return-std-move   -Wno-defaulted-function-deleted   -Wno-pessimizing-move   -Wno-deprecated-anon-enum-enum-conversion   -Wno-deprecated-enum-enum-conversion   -Wno-deprecated-enum-float-conversion   -Wno-ambiguous-reversed-operator   -Wno-deprecated-volatile  -O3 -DNDEBUG -fuse-ld=lld    -nodefaultlibs -ldl -lrt -Wl,--no-as-needed -fPIC -lpthread contrib/tools/flatc/bin/CMakeFiles/flatc.dir/__/__/__/libs/flatbuffers/src/flatc_main.cpp.o contrib/tools/flatc/bin/CMakeFiles/flatc.dir/__vcs_version__.c.o -o contrib/tools/flatc/bin/flatc  contrib/libs/flatbuffers/flatc/liblibs-flatbuffers-flatc.a  library/cpp/malloc/jemalloc/libcpp-malloc-jemalloc.a  library/cpp/malloc/api/libcpp-malloc-api.a  contrib/libs/jemalloc/libcontrib-libs-jemalloc.a  contrib/libs/cxxsupp/libcxx/liblibs-cxxsupp-libcxx.a  contrib/libs/cxxsupp/libcxxabi-parts/liblibs-cxxsupp-libcxxabi-parts.a  contrib/libs/cxxsupp/libcxxrt/liblibs-cxxsupp-libcxxrt.a  contrib/libs/cxxsupp/builtins/liblibs-cxxsupp-builtins.a  contrib/libs/libunwind/libcontrib-libs-libunwind.a  -lc -lm && :
ld.lld: error: undefined symbol: __aarch64_ldadd8_relax
>>> referenced by jemalloc.c
>>>               jemalloc.c.o:(a0ialloc) in archive contrib/libs/jemalloc/libcontrib-libs-jemalloc.a
>>> referenced by jemalloc.c
>>>               jemalloc.c.o:(a0idalloc) in archive contrib/libs/jemalloc/libcontrib-libs-jemalloc.a
>>> referenced by jemalloc.c
>>>               jemalloc.c.o:(do_realloc_nonnull_zero) in archive contrib/libs/jemalloc/libcontrib-libs-jemalloc.a
>>> referenced 83 more times
... ...
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[2589/3561] Building CXX object contrib/tools/protoc/plugins/cpp_styleguide/CMakeFiles/cpp_styleguide.dir/cpp_styleguide.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/ubuntu/2/catboost/build/build_native.py", line 572, in <module>
    build(Opts(**vars(parsed_args)))
  File "/home/ubuntu/2/catboost/build/build_native.py", line 539, in build
    cmd_runner.run(ninja_cmd, env=build_environ)
  File "/home/ubuntu/2/catboost/build/build_native.py", line 164, in run
    subprocess.run(cmd, check=True, **subprocess_run_kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-C', './', 'catboost']' returned non-zero exit status 1.

**Comment by andrey-khropov** [comment] 2024-01-30 13:45
Duplicate of #2527

**Closed** 2024-01-30 13:45 UTC
Labels: build, Linux
