### ISSUE TITLE
Feature Request: Add Stop Training button to the Catboost widget

### ISSUE THREAD

**Issue by fingoldo** [catboost/catboost#2560] opened 2023-12-27 04:58 UTC
Problem:
many times I needed a way to stop training prematurely, after seeing on the live chart that accuracy improves too slowly.
I would prefer to stop training and use the trained model already, without waiting for all iterations specified in advance to finish.
Catboost users are allowed to interact with the widget while the model is training, is it possible to add a button or checkbox to stop training at the current iteration?
Effect should be the same as if the user has specified iterations=current_iteration from the beginning.

**Comment by andrey-khropov** [comment] 2024-03-15 21:36
Duplicate of #2048

**Closed by andrey-khropov** 2024-03-15 21:36 UTC
Labels: visualization, feature request
