### ISSUE TITLE
python code example how to use ranking by using 

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#359] opened 2018-05-23 17:43 UTC
Problem: {there is not expanatoin how to use python for ranking }
catboost version: {latest}
Operating System: {Windows}
CPU: {core7}

May you please share an example from 0 to end with data available how to use python for Ranking 
YetiRank, QueryRMSE, PFound, QuerySoftMax, QueryAverage, PairLogit, PairAccuracy
as written in https://tech.yandex.com/catboost/doc/dg/concepts/loss-functions-docpage/#loss-functions__ranking

**Comment by annaveronika** [comment] 2018-05-24 08:28
duplicate of #358

**Closed by annaveronika** 2018-05-24 08:28 UTC
Labels: duplicate
