### ISSUE TITLE
 Saved model's params are different from current model's params

### ISSUE THREAD

**Issue by MiMakh** [catboost/catboost#2257] opened 2022-12-27 17:41 UTC
Problem: Can't fit models on GPU,  Saved model's params are different from current model's params
catboost version: '1.1.1'
Operating System: Windows 10
CPU: 0
GPU: 1

model_cat_tm_1 = CatBoostClassifier(
    iterations=5000,
    loss_function ='Logloss',
    #eval_metric = 'AUC',
    learning_rate = 0.05,
    random_seed = 1,
    od_type = "Iter",
    od_wait = 200,
    depth = 5,
    task_type = "GPU",
    devices = '0:1',
    save_snapshot= False,
)

cv_params_tm_1 = model_cat_tm_1.get_params()
cv_data_tm_1 = cv(
    Pool(train_tm_treatment_one_features, train_tm_treatment_one_target),
    cv_params_tm_1,
    plot=True,
    verbose=100,
)

Gettting this error (tried, rebooting the system, open another script - doesn't help)

Training on fold [0/3]
---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_3516\715857703.py in <module>
      1 cv_params_tm_1 = model_cat_tm_1.get_params()
----> 2 cv_data_tm_1 = cv(
      3     Pool(train_tm_treatment_one_features, train_tm_treatment_one_target),
      4     cv_params_tm_1,
      5     plot=True,

~\AppData\Roaming\Python\Python39\site-packages\catboost\core.py in cv(pool, params, dtrain, iterations, num_boost_round, fold_count, nfold, inverted, partition_random_seed, seed, shuffle, logging_level, stratified, as_pandas, metric_period, verbose, verbose_eval, plot, plot_file, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, metric_update_interval, folds, type, return_models, log_cout, log_cerr)
   6648     with log_fixup(log_cout, log_cerr), plot_wrapper(plot, plot_file=plot_file, plot_title='Cross-validation plot', train_dirs=plot_dirs):
   6649         if not return_models:
-> 6650             return _cv(params, pool, fold_count, inverted, partition_random_seed, shuffle, stratified,
   6651                     metric_update_interval, as_pandas, folds, type, return_models)
   6652         else:

_catboost.pyx in _catboost._cv()

_catboost.pyx in _catboost._cv()

CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/cuda/methods/boosting_progress_tracker.cpp:171: Saved model's params are different from current model's params

**Comment by Robin069** [comment] 2023-01-05 10:37
Same issue here. The issue seems to be that cv() persists the fitted models under /catboost_info. The only workaround is to delete /catboost_info after each iteration of cv().

**Comment by KobanBanan** [comment] 2023-01-09 10:12
Same error

**Comment by KobanBanan** [comment] 2023-01-09 10:43
@MiMakh try only CPU, seems that error occurs when u running on GPU

**Comment by MiMakh** [comment] 2023-02-16 17:58
> 

How do delete /catboost_info? (Where is it located exactly?)

**Comment by andrey-khropov** [comment] 2023-04-23 19:55
> > 
> 
> How do delete /catboost_info? (Where is it located exactly?)

It's the default name of the directory for files generated during training specified by [`train_dir` training parameter](https://catboost.ai/en/docs/references/training-parameters/output#train_dir) (if you don't change it explicitly it will be located in the directory you run your program from).

**Comment by andrey-khropov** [comment] 2023-04-23 20:49
This issue is a duplicate of #2221

**Closed by andrey-khropov** 2023-04-23 20:49 UTC
Labels: bug, GPU, python
