### ISSUE TITLE
CatBoostRegressor Fails when change the bootstrap_type to No

### ISSUE THREAD

**Issue by parisaazimaee** [catboost/catboost#1394] opened 2020-08-19 20:23 UTC
@annaveronika 
I am training CatboostRegressor with these parameters: 
![image](https://user-images.githubusercontent.com/33792618/90685409-0002b200-e227-11ea-9c5f-3d772d8b87d8.png)

Problem: when I change the bootstrap_type parameter to 'No' i get this error:
    model.fit(train_pool, eval_set=eval_pool, early_stopping_rounds=20)
  File "/home/pazimaee/.local/lib/python3.6/site-packages/catboost/core.py", line 4662, in fit
    save_snapshot, snapshot_file, snapshot_interval, init_model)
  File "/home/pazimaee/.local/lib/python3.6/site-packages/catboost/core.py", line 1731, in _fit
    save_snapshot, snapshot_file, snapshot_interval, init_model
  File "/home/pazimaee/.local/lib/python3.6/site-packages/catboost/core.py", line 1659, in _prepare_train_params
    _check_train_params(params)
  File "_catboost.pyx", line 5624, in _catboost._check_train_params
  File "_catboost.pyx", line 5643, in _catboost._check_train_params
_catboost.CatBoostError: catboost/private/libs/options/json_helper.h:156: Can't parse parameter "type" with value: false
and when i won't pass the parameter i get this error which i have no idea why!
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4260, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4306, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/private/libs/algo/tensor_search_helpers.cpp:502: Too few sampling units (subsample=0.99, bootstrap_type=MVS): please increase sampling rate or disable sampling
catboost version: 0.23
Operating System: Windows 10
CPU: CPU

**Comment by parisaazimaee** [comment] 2020-08-20 00:03
I found out why i was getting the" _catboost.CatBoostError: catboost/private/libs/algo/tensor_search_helpers.cpp:502: Too few sampling units (subsample=0.99, bootstrap_type=MVS): please increase sampling rate or disable sampling". 
I am using log of one the columns as a baseline and there few zeros in that column once i filtered out the zeros i was not getting that error anymore. but there is still bug in the code which won't let use 'No' as the bootstrap_type

**Comment by LyzhinIvan** [comment] 2020-08-20 06:02
Hi, @parisaazimaee !
Please, provide your script with creation and training of CatBoost model. Now I can't reproduce your problem. Also, please, specify how many objects in your dataset?

**Comment by NikiforovG** [comment] 2021-08-20 18:07
@parisaazimaee check if you have `inf` values in your target.
I’ve got the same problem and it was caused by `inf` in my target.
Also it was described here: https://github.com/catboost/catboost/issues/1194

**Comment by andrey-khropov** [comment] 2024-03-10 18:03
> Hi, @parisaazimaee ! Please, provide your script with creation and training of CatBoost model. Now I can't reproduce your problem. Also, please, specify how many objects in your dataset?

As no additional information how to reproduce it has been provided, I'm closing this issue. Feel free to reopen if it is still an issue but please provide more context.

**Closed by andrey-khropov** 2024-03-10 18:03 UTC
