### ISSUE TITLE
Does cv() support training on GPU?

### ISSUE THREAD

**Issue by fantauzzi** [catboost/catboost#363] opened 2018-05-28 10:44 UTC
Problem: training on GPU with cv() stops with error "except learn on CPU task type, got GPU"
catboost version: 0.8.1 built from source
Operating System: Ubuntu 16.04 LST 64-bit
CPU: Intel® Core™ i7-2700K CPU @ 3.50GHz × 8 
GPU: GeForce GTX 1080/PCIe/SSE2

I can train a model with GPU with `CatBoostClassifier().fit`, but when I try to do it with `cv()` (using the same parameters) I get the error below.

Does `cv()` support training on GPU? In the doc. [here](https://tech.yandex.com/catboost/doc/dg/features/training-on-gpu-docpage/) it is not explicitly mentioned.

> ---------------------------------------------------------------------------
> CatboostError                             Traceback (most recent call last)
> <ipython-input-25-30696c6626c9> in <module>()
>       2              model.get_params(),
>       3              fold_count = 5,
> ----> 4              plot=True)
> 
> ~/.local/python3.5/lib/python3.5/site-packages/catboost/core.py in cv(pool, params, dtrain, iterations, num_boost_round, fold_count, nfold, inverted, partition_random_seed, seed, shuffle, logging_level, stratified, as_pandas, verbose, verbose_eval, plot)
>    2470 
>    2471     with log_fixup():
> -> 2472         return _cv(params, pool, fold_count, inverted, partition_random_seed, shuffle, stratified, as_pandas)
>    2473 
>    2474 
> 
> _catboost.pyx in _catboost._cv()
> 
> _catboost.pyx in _catboost._cv()
> 
> CatboostError: catboost/libs/algo/learn_context.h:124: Error: except learn on CPU task type, got GPU
> 
>

**Comment by Noxoomo** [comment] 2018-05-28 10:49
Hi!

CV is not supported on GPU yet

**Comment by annaveronika** [comment] 2018-06-01 08:20
duplicate of #339

**Closed by annaveronika** 2018-06-01 08:20 UTC
Labels: duplicate
