### ISSUE TITLE
distributed training on cpu

### ISSUE THREAD

**Issue by annaveronika** [catboost/catboost#153] opened 2017-10-30 17:18 UTC

**Comment by alkeshc** [comment] 2018-04-19 09:54
Hi, what is the tentative date/month of releasing distributed version of catboost.

**Comment by annaveronika** [comment] 2019-04-15 14:51
Sorry no date for now. We have not finished the work jet, and we have paused for now, but we will start again, sorry for such a long wait for this feature.

**Comment by Daniel8hen** [comment] 2019-07-20 12:35
Hi @annaveronika any update on Spark support? This is an essential feature for those boosting libraries and will definitely help us (me specifically) expose CatBoost to the world. Thank you!

**Comment by annaveronika** [comment] 2019-07-22 16:38
We are not working on it now, we know that it's important, so if we would get help with that, we would really appreciate it. I'm adding a help wanted label.

**Comment by btbbass** [comment] 2019-10-02 08:52
I think that first step would be to provide inference via Scala Spark, via a MOJO like interface (as for the XGBoost models exported from H2O via MOJO).

That way, we could at least using CATBOOST for inference, because, static datasets are good for showing off, but realtime production pipelines with low latency requirements implemented with Scala Spark are another thing :-) 

Then, training could be nice to have, but definitely another priority (and complexity I presume)

**Comment by errorsandwarnings** [comment] 2019-11-12 15:15
@annaveronika : I would like to lead and implement this.

**Comment by annaveronika** [comment] 2019-11-14 09:42
That's great news. Do you have experience with Spark?

**Comment by errorsandwarnings** [comment] 2019-11-14 16:24
@annaveronika : Yes.

**Comment by annaveronika** [comment] 2019-11-14 17:13
I think, it's a good idea to start with prediction. @btbbass suggested to provide inference via Scala Spark, would you start with this?

**Comment by errorsandwarnings** [comment] 2019-11-14 19:29
@annaveronika Are you suggesting we only provide inference from pretrained catboost ( outside spark ) in scala spark ?

**Comment by annaveronika** [comment] 2019-11-15 12:25
I think it's a good idea to start with something, I suggest to start with easiest part, then proceed with harder parts. Inference sounds like a good starting point.

**Comment by KlausGlueckert** [comment] 2019-11-18 23:41
@annaveronika I have read all the other open issues, but nowhere I can find a clear recommendation how to train catboost in GPU mode on a big dataset that does not fit into GPU ram. In one issue you explicitly recommend training on GPU even if the dataset does not fit into GPU memory. Ideally it would be nice to use a spark data.frame for this. What would be a best practice to do this at the moment?

**Comment by annaveronika** [comment] 2019-11-19 08:11
> @annaveronika I have read all the other open issues, but nowhere I can find a clear recommendation how to train catboost in GPU mode on a big dataset that does not fit into GPU ram. In one issue you explicitly recommend training on GPU even if the dataset does not fit into GPU memory. Ideally it would be nice to use a spark data.frame for this. What would be a best practice to do this at the moment?
> 
> **Spark scenario**
> 
> * 1 machine with 1 GPU (stand-alone cluster with virtual workers)
> * 1 machine with n GPUs (stand-alone cluster with virtual workers)
> * n machines with n GPUs each

If your dataset doesn't fit into GPU memory, you need to first do quantization and then use the compressed version of the pool for GPU training: https://catboost.ai/docs/concepts/python-reference_pool_quantized.html

If it still doesn't fit into GPU memory, try some of these tips:
https://catboost.ai/docs/concepts/faq.html#overcome-out-of-memory

**Comment by winston-p** [comment] 2019-12-17 06:13
> Hi @annaveronika any update on Spark support? This is an essential feature for those boosting libraries and will definitely help us (me specifically) expose CatBoost to the world. Thank you!

Totally agree. I'm a big fan of Catboost after switching over from XGBoost. I feel the next 'frontier' for Catboost is distributed training and inference, something sorely missing when other popular packages do offer.

@annaveronika In another post [506](https://github.com/catboost/catboost/issues/506), you mentioned that Catboost does have 'multi-node' training. I'm confused, are you saying that distributed training (with both CPU and GPU) is available, just not with Spark support?

> In Yandex we have many cases where we need to work with large datasets. In most cases we use GPU training. In rare cases when we dataset is too large to be trained on one machine with 8 GPU-s we use multi node GPU training.
> 
> We also have multi node CPU training, you can try using it in command line mode.
> 
> But we don't fully support multi node training it for open-source jet - there is no documentation. You can try using it with help that you get from ./catboost fit --help. So basically you need to run the binary separately on each node and use specific flags for distributed training.
> 
> We will write docs for that at some point. But I would strongly encourage you to use GPU-s. It is much faster than distributed CPU and it also can work with huge datasets.

**Comment by annaveronika** [comment] 2019-12-25 14:44
CatBoost does have multi node training, you can find it in cmdline help. But it is not documented and it is hard to use it for large datasets, because current open-source version loads the whole dataset into memory of master. Which makes it impossible to train on very large datasets.

**Comment by Daniel8hen** [comment] 2020-03-07 11:37
@annaveronika tomorrow we will meet in CatBoost meetup so prepare for the Spark-any-update question ;)

**Comment by andrey-khropov** [comment] 2020-10-09 20:19
We've released a prerelease version of Spark support. There're some notable limitations for now like the lack of support for categorical features, GPUs and PySpark, but all these will be supported in the nearest future.

The information is available at https://github.com/catboost/catboost/tree/master/catboost/spark/catboost4j-spark.

**Comment by btbbass** [comment] 2020-10-19 09:30
> We've released a prerelease version of Spark support. There're some notable limitations for now like the lack of support for categorical features, GPUs and PySpark, but all these will be supported in the nearest future.
> 

That's really great news! Thanks for that!
I have just a question:

is it able to use catboost models created NOT via spark ? (inference using models created not in spark )
What are the limitations in this case ?

**Comment by andrey-khropov** [comment] 2020-10-26 22:40
> is it able to use catboost models created NOT via spark ? (inference using models created not in spark )

It should be possible, I'll add the appropriate API to model classes to load from files in the native filesystem in a day or two.

> What are the limitations in this case ?

No categorical or text features for now. Support for them will be added later. Categorical features support will be added this week, text features are likely to be supported within a month.

**Comment by trouble-maker007** [comment] 2020-11-18 08:32
@andrey-khropov any update about support categorical features?

**Comment by andrey-khropov** [comment] 2020-11-19 22:24
> @andrey-khropov any update about support categorical features?
> And now does support spark version to load the python version trained model to inference?

I'm planning to publish a new RC release with the support of both these features this week or early next week.

**Comment by trouble-maker007** [comment] 2020-11-23 06:40
@andrey-khropov Great, Looking forward

**Comment by trouble-maker007** [comment] 2020-11-29 12:36
> > @andrey-khropov any update about support categorical features?
> > And now does support spark version to load the python version trained model to inference?
> 
> I'm planning to publish a new RC release with the support of both these features this week or early next week.

@andrey-khropov I could not find a new version on maven. Could I build the newest caboost4j to support these features?

**Comment by andrey-khropov** [comment] 2020-12-01 21:01
> > > @andrey-khropov any update about support categorical features?
> > > And now does support spark version to load the python version trained model to inference?
> > 
> > 
> > I'm planning to publish a new RC release with the support of both these features this week or early next week.
> 
> @andrey-khropov I could not find a new version on maven. Could I build the newest caboost4j to support these features?

I'm planning to update a maven package tomorrow. There're a couple of issues needed to be taken care of.

**Comment by RyanHuangNLP** [comment] 2020-12-28 03:11
@andrey-khropov is there any update about catboost new version on maven?

**Comment by saurzcode** [comment] 2021-01-05 19:38
Is the latest version on maven breaking ? I tried running the test for prediction mentioned in READMe, without any change for 2.11 and it breaks as  
```
Exception in thread "main" java.lang.AbstractMethodError: ai.catboost.spark.Pool.org$apache$spark$ml$param$Params$_setter_$org$apache$spark$ml$param$Params$$paramMap_$eq(Lorg/apache/spark/ml/param/ParamMap;)V
	at org.apache.spark.ml.param.Params$class.$init$(params.scala:868)
	at ai.catboost.spark.Pool.<init>(Pool.scala:244)
	at ai.catboost.spark.Pool.<init>(Pool.scala:250)
	at ai.catboost.spark.Pool.<init>(Pool.scala:289)
```

**Comment by andrey-khropov** [comment] 2021-01-28 09:16
> Is the latest version on maven breaking ? I tried running the test for prediction mentioned in READMe, without any change for 2.11 and it breaks as
> 
> ```
> Exception in thread "main" java.lang.AbstractMethodError: ai.catboost.spark.Pool.org$apache$spark$ml$param$Params$_setter_$org$apache$spark$ml$param$Params$$paramMap_$eq(Lorg/apache/spark/ml/param/ParamMap;)V
> 	at org.apache.spark.ml.param.Params$class.$init$(params.scala:868)
> 	at ai.catboost.spark.Pool.<init>(Pool.scala:244)
> 	at ai.catboost.spark.Pool.<init>(Pool.scala:250)
> 	at ai.catboost.spark.Pool.<init>(Pool.scala:289)
> ```

Sorry for a delayed response. I was unable to reproduce this error. If the issue still persist with the latest version (0.25-rc3) please open a separate issue and describe your environment in more details (OS, JRE version, full project including pom.xml/ sbt config etc).

**Comment by andrey-khropov** [comment] 2021-01-28 09:19
Spark package version has been updated to 0.25-rc3.
Changes since 0.25-rc1 include:

- Pairs support
- Categorical features support
- PySpark support (README.md has been updated with the relevant information).
- More logging
- Bugfixes

**Comment by achimbab** [comment] 2021-02-18 07:10
@annaveronika @winston-p 

> But we don't fully support multi node training it for open-source jet - there is no documentation. You can try using it with help that you get from ./catboost fit --help. So basically you need to run the binary separately on each node and use specific flags for distributed training.

Hi, 
Could I get a document for distributed training? 
Or is there any new related feature?

**Comment by andrey-khropov** [comment] 2021-02-18 08:33
> Hi,
> Can I get a document for distributed training?

No, there's no document for running the distributed training from CLI but there're some examples in the tests.

> Or is there any new related feature?

I'm quoting myself from [the comment above](https://github.com/catboost/catboost/issues/153#issuecomment-706384639):

> We've released a prerelease version of Spark support. 
> The information is available at https://github.com/catboost/catboost/tree/master/catboost/spark/catboost4j-spark.

**Comment by achimbab** [comment] 2021-02-18 08:45
@andrey-khropov 

Thanks for your answer.

I can't train complex models in CLI. When I started 'catboost fit' I got an exception.
```
(TCatBoostException) catboost/libs/train_lib/train_model.cpp:822: MaxTensorComplexity > 1 is not yet supported 
in distributed training on CPU
```

Is it OK with spark version?

**Comment by RyanHuangNLP** [comment] 2021-03-18 06:14
@andrey-khropov Is there any tutorials about how to use Categorical features ?

**Comment by andrey-khropov** [comment] 2021-03-20 03:39
> @andrey-khropov Is there any tutorials about how to use Categorical features ?

For now they are supported in the standard Spark API way: they are stored in the `features` column with numerical features in [org.apache.spark.ml.linalg.Vector](https://spark.apache.org/docs/latest/api/scala/org/apache/spark/ml/linalg/Vector.html)-type column and you have to mark them with `Nominal` attribute in features column metadata. 

You can see examples (in Scala) in the tests:

[test itself](https://github.com/catboost/catboost/blob/8a3b1f6e56711ee6b06a6f33e8e149067b7541c4/catboost/spark/catboost4j-spark/core/src/test/scala/ai/catboost/spark/CatBoostRegressorTest.scala#L578)

[code called from the test above that sets features attributes in column metadata](https://github.com/catboost/catboost/blob/8a3b1f6e56711ee6b06a6f33e8e149067b7541c4/catboost/spark/catboost4j-spark/core/src/test/scala/ai/catboost/spark/PoolTestHelpers.scala#L23-L38)

**Comment by andrey-khropov** [comment] 2021-03-20 03:42
> @andrey-khropov
> 
> Spark support is great!
> 
> I can't train complex models in CLI. When I started 'catboost fit' I got an exception.
> 
> ```
> (TCatBoostException) catboost/libs/train_lib/train_model.cpp:822: MaxTensorComplexity > 1 is not yet supported 
> in distributed training on CPU
> ```
> 
> Doesn't this exception appear in the spark version?

No, CatBoost Spark sets max_tensor_complexity to 1 explicitly.

**Comment by achimbab** [comment] 2021-03-20 04:29
@andrey-khropov 
Thank you.

**Comment by VlasovKirill** [comment] 2021-04-09 10:15
Closing as support for training on spark is mostly done. Plz open new issue if you have some problems.

**Closed by VlasovKirill** 2021-04-09 10:15 UTC
Labels: help wanted, in progress
