### ISSUE TITLE
Is CatboostEvaluation deprecated?

### ISSUE THREAD

**Issue by aamster** [catboost/catboost#987] opened 2019-09-06 18:06 UTC
Is CatboostEvaluation deprecated? There is a tutorial for feature selection using it at https://github.com/catboost/tutorials/blob/master/feature_selection/eval_tutorial.ipynb however I can't find it documented on the catboost site. Has it been replaced in favor of `get_feature_importance`?

**Comment by annaveronika** [comment] 2019-09-09 10:02
It's not deprecated, we plan to improve interfaces and to write documentation.

**Comment by annaveronika** [comment] 2019-09-13 16:56
Closing as a duplicate of https://github.com/catboost/catboost/issues/429

**Closed by annaveronika** 2019-09-13 16:56 UTC
