### ISSUE TITLE
Dying Jupyter Lab kernel on Mac M1

### ISSUE THREAD

**Issue by DeeStarks** [catboost/catboost#1883] opened 2021-10-14 13:54 UTC
### Problem:

The kernel dies and outputs a verified failed message
Code:
```python
clf = ctb.CatBoostClassifier()
cv = GridSearchCV(
    estimator=clf, 
    param_grid=grid_params, 
    verbose=500, 
    cv=5, 
    n_jobs=4
)
cv.fit(X, y, **fit)
```

Output:
```sh
VERIFY failed (2021-10-14T14:57:32.508688+0100): 
  catboost/libs/data/quantization.cpp:245
  CalcQuantizationAndNanMode(): requirement binarizationOptions.BorderCount > 0 failed
NPrivate::InternalPanicImpl(int, char const*, char const*, int, int, int, TBasicStringBuf<char, std::__y1::char_traits<char> >, char const*, unsigned long)+751 (0x12F48A05F)
NPrivate::Panic(NPrivate::TStaticBuf const&, int, char const*, char const*, char const*, ...)+315 (0x12F487CCB)
NCB::TQuantizationImpl::Do(NCB::TQuantizationOptions const&, TIntrusivePtr<NCB::TDataProviderTemplate<NCB::TRawObjectsDataProvider>, TDefaultIntrusivePtrOps<NCB::TDataProviderTemplate<NCB::TRawObjectsDataProvider> > >, TIntrusivePtr<NCB::TQuantizedFeaturesInfo, TDefaultIntrusivePtrOps<NCB::TQuantizedFeaturesInfo> >, bool, TRestorableFastRng64*, NPar::ILocalExecutor*, TMaybe<TVector<TArrayRef<float const>, std::__y1::allocator<TArrayRef<float const> > >, NMaybe::TPolicyUndefinedExcept> const&)::'lambda'(NCB::TFeatureIdx<(EFeatureType)0>)::operator()(NCB::TFeatureIdx<(EFeatureType)0>) const::'lambda'()::operator()() const+5836 (0x12F95B20C)
std::__y1::__function::__func<NCB::ExecuteTasksInParallel(TVector<std::__y1::function<void ()>, std::__y1::allocator<std::__y1::function<void ()> > >*, NPar::ILocalExecutor*)::$_0, std::__y1::allocator<NCB::ExecuteTasksInParallel(TVector<std::__y1::function<void ()>, std::__y1::allocator<std::__y1::function<void ()> > >*, NPar::ILocalExecutor*)::$_0>, void (int)>::operator()(int&&)+47 (0x12F51686F)
(anonymous namespace)::TFunctionWrapperWithPromise::LocalExec(int)+54 (0x12F4FF796)
void tbb::detail::d1::dynamic_grainsize_mode<tbb::detail::d1::adaptive_mode<tbb::detail::d1::auto_partition_type> >::work_balance<tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<int>, tbb::detail::d1::parallel_for_body<NPar::TTbbLocalExecutor<false>::ExecRange(TIntrusivePtr<NPar::ILocallyExecutable, TDefaultIntrusivePtrOps<NPar::ILocallyExecutable> >, int, int, int)::'lambda'()::operator()() const::'lambda'(int), int>, tbb::detail::d1::auto_partitioner const>, tbb::detail::d1::blocked_range<int> >(tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<int>, tbb::detail::d1::parallel_for_body<NPar::TTbbLocalExecutor<false>::ExecRange(TIntrusivePtr<NPar::ILocallyExecutable, TDefaultIntrusivePtrOps<NPar::ILocallyExecutable> >, int, int, int)::'lambda'()::operator()() const::'lambda'(int), int>, tbb::detail::d1::auto_partitioner const>&, tbb::detail::d1::blocked_range<int>&, tbb::detail::d1::execution_data&)+805 (0x12F502BB5)
void tbb::detail::d1::partition_type_base<tbb::detail::d1::auto_partition_type>::execute<tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<int>, tbb::detail::d1::parallel_for_body<NPar::TTbbLocalExecutor<false>::ExecRange(TIntrusivePtr<NPar::ILocallyExecutable, TDefaultIntrusivePtrOps<NPar::ILocallyExecutable> >, int, int, int)::'lambda'()::operator()() const::'lambda'(int), int>, tbb::detail::d1::auto_partitioner const>, tbb::detail::d1::blocked_range<int> >(tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<int>, tbb::detail::d1::parallel_for_body<NPar::TTbbLocalExecutor<false>::ExecRange(TIntrusivePtr<NPar::ILocallyExecutable, TDefaultIntrusivePtrOps<NPar::ILocallyExecutable> >, int, int, int)::'lambda'()::operator()() const::'lambda'(int), int>, tbb::detail::d1::auto_partitioner const>&, tbb::detail::d1::blocked_range<int>&, tbb::detail::d1::execution_data&)+414 (0x12F50287E)
tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<int>, tbb::detail::d1::parallel_for_body<NPar::TTbbLocalExecutor<false>::ExecRange(TIntrusivePtr<NPar::ILocallyExecutable, TDefaultIntrusivePtrOps<NPar::ILocallyExecutable> >, int, int, int)::'lambda'()::operator()() const::'lambda'(int), int>, tbb::detail::d1::auto_partitioner const>::execute(tbb::detail::d1::execution_data&)+147 (0x12F5025B3)
tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&)+284 (0x12F4EAD3C)
tbb::detail::r1::arena::process(tbb::detail::r1::thread_data&)+466 (0x12F4E7D32)
tbb::detail::r1::market::process(rml::job&)+59 (0x12F4F071B)
tbb::detail::r1::rml::private_worker::run()+61 (0x12F4F1B5D)
tbb::detail::r1::rml::private_worker::thread_routine(void*)+9 (0x12F4F1B19)
_pthread_start+224 (0x7FFF20332950)
```

### Catboost version:
0.26.1

### Operating System:
MacOS

### GPU:
Apple M1 Chip, 8-core GPU

**Comment by DeeStarks** [comment] 2021-10-14 17:46
Oh! Thanks @andrey-khropov 
It was actually my border count. I made a mistake by setting it to `[4]` instead of `[254]`

**Comment by andrey-khropov** [comment] 2021-10-14 20:32
> Oh! Thanks @andrey-khropov It was actually my border count. I made a mistake by setting it to `[4]` instead of `[254]`

`[4]` should work without error as any other positive integer. Although it might be not what you intended.

Is your problem solved now and this issue can be closed?

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2021-10-15 08:33
@DeeStarks could you please share a reproducer? or close the issue? 
I have played a bit with the snippet that you provide, and a random dataset, and cannot reproduce the issue.

**Closed** 2021-10-15 12:03 UTC
