### ISSUE TITLE
ImportError: cannot import name 'MetricVisualizer' from 'catboost' 

### ISSUE THREAD

**Issue by jccguma** [catboost/catboost#2270] opened 2023-01-16 11:21 UTC
Problem: ImportError: cannot import name 'MetricVisualizer' from 'catboost' 
catboost version: 1.0.0
Operating System: Ubuntu 20 WSL on W10
Python 3.8.10

I do not know why this is happening. Thanks in advance.

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2023-01-18 06:26
hi @jccguma ✋ 
many thanks for trying catboost ❤️‍🔥
MetricVisualizer is available only if catboost is able to import additional modules (see python-package/catboost/widget/ipythonwidget.py)
most likely (since we do not test catboost + wsl) this step fails under wsl, and MetricVisualizer becomes unavailable
you may try catboost for windows instead

**Comment by kizill** [comment] 2023-01-24 13:42
Hello! Don't you have a file with name `catboost.py` or folder `catboost` in current working directoruy named catboost? I guess they could be erroneously loaded.

**Comment by andrey-khropov** [comment] 2023-11-23 23:58
As no additional information has been provided I'm closing this issue. Feel free to reopen if necessary with additional information to reproduce.

**Closed by andrey-khropov** 2023-11-23 23:58 UTC
Labels: need info, python
