### ISSUE TITLE
getting CatBoostError: Invalid cat_features[6] = 22 value: index must be < 22 but len(x_train.columns) is 23

### ISSUE THREAD

**Issue by javiercoh** [catboost/catboost#2607] opened 2024-03-09 01:06 UTC
Problem: getting "catBoostError: Invalid cat_features[6] = 22 value: index must be < 22" but len(cat_features) = 23
catboost version:1.2.3
Operating System: Linux 24.01.30
CPU:4 cores, 28 GB RAM, 56 GB disk
GPU:

`      
print(x_train.columns)

print(len(x_train.columns)) # this returns 23

categorical_positions = [11,12,13,17,20,21,22]

model = CatBoostRegressor(iterations=100,
                                loss_function=f'MultiQuantile:alpha={quantile_str}', cat_features=categorical_positions)

model.fit(x_train, y_train)
`

**Comment by andrey-khropov** [comment] 2024-03-09 14:29
Can you give more detailed information to reproduce? I cannot reproduce this error.

Here's the code that works without problems for me.

```py
    import numpy as np
    import pandas as pd
    from catboost import CatBoostRegressor

    n_samples = 10
    x_train_dict = {}

    for i in range(23):
        x_train_dict[str(i)] = np.random.random_integers(100, size=n_samples)

    x_train = pd.DataFrame(x_train_dict)
    y_train = np.random.random_sample(n_samples)

    quantile_str = '0.1,0.9'

    print(len(x_train.columns)) # this returns 23
    categorical_positions = [11,12,13,17,20,21,22]

    model = CatBoostRegressor(iterations=100,
    loss_function=f'MultiQuantile:alpha={quantile_str}', cat_features=categorical_positions)

    model.fit(x_train, y_train)
```

**Comment by andrey-khropov** [comment] 2024-10-17 21:05
No additional info is provided, so I am closing this issue. Feel free to reopen with more details if necessary.

**Closed by andrey-khropov** 2024-10-17 21:05 UTC
Labels: need info, python
