### ISSUE TITLE
pip installation is ok but not working on windows 

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#1048] opened 2019-10-25 20:35 UTC
Problem:

pip installation is ok but not working on windows 
pip install catboost

Collecting catboost

  Downloading https://files.pythonhosted.org/packages/54/79/303315d11b208f74f46255a0a7ba3836e9f540998cd05837e6b408ab2404/catboost-0.18-cp36-none-win_amd64.whl (62.0MB)

     |████████████████████████████████| 62.0MB 6.4MB/s

Requirement already satisfied: matplotlib in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from catboost) (3.1.1)

Requirement already satisfied: six in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from catboost) (1.12.0)

Requirement already satisfied: scipy in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from catboost) (1.1.0)

Requirement already satisfied: pandas>=0.24.0 in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from catboost) (0.25.2)

Requirement already satisfied: plotly in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from catboost) (3.6.1)

Requirement already satisfied: numpy>=1.16.0 in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from catboost) (1.16.4)

Requirement already satisfied: graphviz in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from catboost) (0.13)

Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from matplotlib->catboost) (1.0.1)

Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from matplotlib->catboost) (2.2.0)

Requirement already satisfied: python-dateutil>=2.1 in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from matplotlib->catboost) (2.7.3)

Requirement already satisfied: cycler>=0.10 in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from matplotlib->catboost) (0.10.0)

Requirement already satisfied: pytz>=2017.2 in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from pandas>=0.24.0->catboost) (2018.4)

Requirement already satisfied: requests in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from plotly->catboost) (2.18.4)

Requirement already satisfied: nbformat>=4.2 in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from plotly->catboost) (4.4.0)

Requirement already satisfied: retrying>=1.3.3 in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from plotly->catboost) (1.3.3)

Requirement already satisfied: decorator>=4.0.6 in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from plotly->catboost) (4.3.0)

Requirement already satisfied: setuptools in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from kiwisolver>=1.0.1->matplotlib->catboost) (41.0.1)

Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from requests->plotly->catboost) (3.0.4)

Requirement already satisfied: idna<2.7,>=2.5 in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from requests->plotly->catboost) (2.6)

Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from requests->plotly->catboost) (1.22)

Requirement already satisfied: certifi>=2017.4.17 in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from requests->plotly->catboost) (2019.9.11)

Requirement already satisfied: ipython_genutils in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from nbformat>=4.2->plotly->catboost) (0.2.0)

Requirement already satisfied: traitlets>=4.1 in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from nbformat>=4.2->plotly->catboost) (4.3.2)

Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from nbformat>=4.2->plotly->catboost) (2.6.0)

Requirement already satisfied: jupyter_core in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (from nbformat>=4.2->plotly->catboost) (4.4.0)

Installing collected packages: catboost

Successfully installed catboost-0.18

 

 

 

File "d:\oct25_catboost.py", line 3, in <module>

  import catboost

File "C:\Users\abc\AppData\Local\Continuum\anaconda3\Lib\site-packages\catboost\__init__.py", line 1, in <module>

  from .core import FeaturesData, EFstrType, Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatBoostError, cv, train, sum_models, _have_equal_features # noqa

File "C:\Users\abc\AppData\Local\Continuum\anaconda3\Lib\site-packages\catboost\core.py", line 62, in <module>

  _catboost = get_catboost_bin_module()

File "C:\Users\abc\AppData\Local\Continuum\anaconda3\Lib\site-packages\catboost\core.py", line 53, in get_catboost_bin_module

  loaded_catboost = imp.load_dynamic('_catboost', so_path)

File "C:\Users\abc\AppData\Local\Continuum\anaconda3\Lib\imp.py", line 343, in load_dynamic

  return _load(spec)

File "C:\Users\abc\AppData\Local\Continuum\anaconda3\Lib\site-packages\catboost\_catboost.pyd", line 918, in init _catboost

 

builtins.ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

 

catboost version: latest
Operating System: windows
CPU: i5
# GPU:

**Comment by DanielLumb** [comment] 2019-10-25 22:07
Definitely seems you have numpy version incompatibility, so you might want to dig a bit into this.

**Comment by Sandy4321** [comment] 2019-10-27 14:38
as you asked it is


np.__version__

'1.14.5'

**Comment by DanielLumb** [comment] 2019-10-28 17:34
Then upgrading it to at least 1.16 should solve the problem.

**Comment by dbakshee** [comment] 2019-11-14 09:37
Hi @Sandy4321 , have you managed to solve your problem?

Looks like you have got two versions of numpy on your system. Version 1.16.4 in c:\users\abc\appdata\local\continuum\anaconda3\lib\site-packages (shown by pip install), and version 1.14.5 that you see. 

Activating your anaconda environment before running catboost may help.

**Comment by Sandy4321** [comment] 2019-11-15 13:42
I see, so activate Anaconda?

**Comment by dbakshee** [comment] 2019-11-29 02:53
Hi @Sandy4321 
Is your issue solved?

**Comment by Sandy4321** [comment] 2019-11-29 12:39
Activating your anaconda environment before running catboost may help.
What does it mean, how to do it?

**Comment by dbakshee** [comment] 2019-11-29 15:27
Normally you just open an Anaconda prompt. 

Could you check if the python you use to run the script that imports catboost is the anaconda python? If you run `where python` and `where pip` you should see the same location, I suppose.

**Comment by annaveronika** [comment] 2019-11-29 16:08
The problem is not with catboost, so a good place for this discussion would ba stackoverflow.
I'm closing the issue, because issues is a place for problems and features in catboost. Please post on stackoverflow or look there for solutions.

**Closed by annaveronika** 2019-11-29 16:08 UTC
