### ISSUE TITLE
How to define Timestamp column in data separate from feature_names

### ISSUE THREAD

**Issue by antipisa** [catboost/catboost#1811] opened 2021-08-17 20:35 UTC
Problem:
catboost version: 0.26
Operating System: Linux RH7
CPU: 

How can one use the Timestamp column in data to be consistent with has_time=True? If the column is present in the data, it is treated as a feature, but one cannot specify this in the Pool object.

```
import pandas as pd
from catboost import CatBoostRegressor, Pool


params = {"boosting_type":"Ordered", 
"has_time":True,
"num_boost_round":500,
"loss_function":"RMSE",
"eval_metric":"RMSE"}

model = CatBoostRegressor(**params)
X['Timestamp'] = pd.datetime(2020, 1, 2, 16, 30)
pool = Pool(X,label=y, cat_features=["A","B"], feature_names=["A","B","C","D"])

```
raises

`CatBoostError: Invalid length of feature_names=4 :  must be equal to the number of columns in data=5
`

**Comment by andrey-khropov** [comment] 2021-08-28 13:39
> one cannot specify this in the Pool object.

That's an omission that will be fixed soon.

**Comment by andrey-khropov** [comment] 2021-08-28 21:49
Duplicate of #1016

**Closed by andrey-khropov** 2021-08-28 21:49 UTC
Labels: in progress
