### ISSUE TITLE
If catboost_spark.CatBoostClassifier().fit() is used, fit() cannot be completed

### ISSUE THREAD

**Issue by Eye-Wuppertal** [catboost/catboost#2309] opened 2023-03-01 11:14 UTC
Problem: If catboost_spark.CatBoostClassifier().fit() is used, fit() cannot be completed
catboost version: catboost-spark_3.0_2.12-1.1.1
Operating System:windows10
version:
python :3.9
spark: 3.0
scala: 2.12

I want catboost to run on spark. According to the official documentation and other users' examples, the jar package is successfully imported, so that catboost_spark can read, but for some reason, the fit() function cannot be completed. I hope someone can help me to solve it.

```python
from pyspark.sql import Row, SparkSession
from pyspark.ml.linalg import Vectors, VectorUDT
from pyspark.sql.types import *


spark = SparkSession.builder \
    .master("local") \
    .appName("catboost_spark") \
    .config("spark.submit.pyFiles", f"catboost-spark_3.0_2.12-1.1.1.jar") \
    .config("spark.jars", f"catboost-common-1.1.1.jar") \
    .config("spark.jars", f"catboost-spark-macros_2.12-1.1.1.jar") \
    .config("spark.jars", f"catboost-prediction-1.1.1.jar") \
    .config("spark.jars", f"classgraph-4.8.154.jar") \
    .getOrCreate()

import catboost_spark

srcDataSchema = [
    StructField("features", VectorUDT()),
    StructField("label", StringType())
]

trainData = [
    Row(Vectors.dense(0.1, 0.2, 0.11), "0"),
    Row(Vectors.dense(0.97, 0.82, 0.33), "1"),
    Row(Vectors.dense(0.13, 0.22, 0.23), "1"),
    Row(Vectors.dense(0.8, 0.62, 0.0), "0")
]

trainDf = spark.createDataFrame(spark.sparkContext.parallelize(trainData), StructType(srcDataSchema))
trainPool = catboost_spark.Pool(trainDf)

evalData = [
    Row(Vectors.dense(0.22, 0.33, 0.9), "1"),
    Row(Vectors.dense(0.11, 0.1, 0.21), "0"),
    Row(Vectors.dense(0.77, 0.0, 0.0), "1")
]

evalDf = spark.createDataFrame(spark.sparkContext.parallelize(evalData), StructType(srcDataSchema))
evalPool = catboost_spark.Pool(evalDf)

classifier = catboost_spark.CatBoostClassifier()

# train a model
# model = classifier.fit(trainPool, eval_set=[evalPool])
model = classifier.fit(trainPool)
# apply the model
predictions = model.transform(evalPool.data)
predictions.show()

# save the model
savedModelPath = "/my_models/binclass_model"
model.write().save(savedModelPath)

# save the model as a local file in CatBoost native format
savedNativeModelPath = './my_local_models/binclass_model.cbm'
model.saveNativeModel(savedNativeModelPath)

# load the model (can be used in a different Spark session)

loadedModel = catboost_spark.CatBoostClassificationModel.load(savedModelPath)

predictionsFromLoadedModel = loadedModel.transform(evalPool.data)
predictionsFromLoadedModel.show()

# load the model as a local file in CatBoost native format

loadedNativeModel = catboost_spark.CatBoostClassificationModel.loadNativeModel(savedNativeModelPath)

predictionsFromLoadedNativeModel = loadedNativeModel.transform(evalPool.data)
predictionsFromLoadedNativeModel.show()
```
![err](https://user-images.githubusercontent.com/70760761/222123430-6ab3273c-e09d-4e80-ba47-312facf70b11.png)

**Comment by andrey-khropov** [comment] 2024-02-16 16:47
Duplicate of #2151

**Closed by andrey-khropov** 2024-02-16 16:47 UTC
Labels: Spark
