### ISSUE TITLE
Fatal error on fit()

### ISSUE THREAD

**Issue by malugina** [catboost/catboost#51] opened 2017-07-21 21:14 UTC
![screenshot](https://user-images.githubusercontent.com/30290446/28482152-343d08ca-6e78-11e7-897c-4411ae705f34.JPG)
import catboost - ok
create the regressor (or classifier) - ok
fit() - always error
Python 2.7 (64 bit), windows7

**Comment by annaveronika** [comment] 2017-07-22 21:44
CatBoost builds oblivious trees - full binary trees with requested depth. So for depth==32 you have a tree with 2^32 leafs which causes an out of memory error. We'll do a better diagnostic for that soon, but for now I recommend using depth <= 16. Best values for depth usually are 6 <= depth <= 12.

**Comment by annaveronika** [comment] 2017-07-24 13:05
MATRIXNET-772, MATRIXNET-766

**Comment by malugina** [comment] 2017-07-24 15:02
annaveronika, it's not a memory error, and depth=3 or depth=7 don't change the situation

**Comment by annaveronika** [comment] 2017-08-02 10:42
Can you reproduce it using the last version?

**Comment by malugina** [comment] 2017-08-03 15:35
no, the same error (catboost 0.1.1.6)

**Comment by purelistica** [comment] 2017-08-09 10:24
I have the same problem with both Python 3.6 and 2.7 (with Anaconda environment and without it), with catboost 0.1.1.6/0.1.1.5 on Windows 10

**Comment by annaveronika** [comment] 2017-08-23 13:28
The problem here is that all features are constant, so you cannot learn anything from that. We will add better diagnostic and fix our example in documentation.

**Comment by annaveronika** [comment] 2017-08-23 13:47
We cannot reproduce your problem...

**Comment by exprmntr** [comment] 2017-08-23 15:28
@malugina, @purelistica, please tell us your CPU model, probably it can be a source of a problems

**Comment by malugina** [comment] 2017-08-24 11:17
@exprmntr 
Intel Core 2 Duo P8700 2.53 GHz
I think this problem not in CPU, but in installed software, service packs or system configuration.

**Comment by annaveronika** [comment] 2017-10-18 15:46
Sorry for a long response. Could you please provide a core dump?
Here is an instruction: https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181(v=vs.85).aspx

**Comment by annaveronika** [comment] 2017-10-19 15:05
This should be fixed now. Could you try to build from master and test it?

**Comment by annaveronika** [comment] 2017-10-30 10:30
Closing because of inactivity.

**Comment by AndreyGurevich** [comment] 2017-11-13 15:58
I installed catboost today using pip, it worked properly 3 times and then i got the same error. 

Reboot did not helped me. 
Would you reopen this issue or should i open the new one? 
More diagnostic will be provided tomorrow.

**Comment by annaveronika** [comment] 2017-11-13 16:04
Could you build the cmdline binary and run it?
Here is the instruction:
https://tech.yandex.com/catboost/doc/dg/concepts/cli-installation-docpage/#local-copy-installation
Please build it without -r flag (then it'll be in debug mode)

If it fails, could you provide a core dump? Here is an instruction:
https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181(v=vs.85).aspx
Please provide the Mini dump

**Comment by AndreyGurevich** [comment] 2017-11-13 18:14
1) Problem is OS-dependent. The same ipynb file, the same Anaconda enviroment, but different OS.
On Win 8, Win 10 it works well
On Win 7 64 bit it fails

2) I use this code, almost from samples:
`cat_model = CatBoostClassifier(
    custom_loss=['AUC'],
    random_seed=42
)`

When custom_loss=['AUC'], it fails on Win7. When custom_loss=['Accuracy'], it works well on both Win7&10

Do you still really need dumps? If yes, I`ll provide them.

**Comment by kizill** [comment] 2017-11-13 18:18
What cpu are on windows 7 machine? Do you run it on virtual machine?

**Comment by AndreyGurevich** [comment] 2017-11-13 18:21
Core-i5 4590
It`s phisical PC, not virtual

Just got the same error on win10, calling predict_proba after fitting with custom_loss=['AUC'] :(

**Comment by kizill** [comment] 2017-11-13 18:34
Can you provide some code that reproduces your problem?

**Comment by AndreyGurevich** [comment] 2017-11-13 18:58
Yes.
1) You`ll need data from  https://www.kaggle.com/c/flight-delays-2017/data or from github:
https://github.com/AndreyGurevich/education_rep/blob/master/ODS/flight_delays_test.csv
https://github.com/AndreyGurevich/education_rep/blob/master/ODS/flight_delays_train.csv
2) ipynb 
https://github.com/AndreyGurevich/education_rep/blob/master/ODS/hw10_session2_flight_delays_kaggle.ipynb


debug:
1) `cat_model = CatBoostClassifier(
    #loss_function='CrossEntropy',
    custom_loss=['AUC'],
    random_seed=42
)
categorical_features_indices = np.where(X.dtypes == np.object)[0]
`
CatboostError: st/catboost/libs/algo/apply.cpp:72: Insufficient float features count


2) `cat_model = CatBoostClassifier(
    loss_function='CrossEntropy',
    custom_loss=['AUC'],
    random_seed=42
)
categorical_features_indices = np.where(X.dtypes == np.object)[0]
`

CatboostError: st/catboost/libs/algo/apply.cpp:72: Insufficient float features count

3) `cat_model = CatBoostClassifier(
    #loss_function='CrossEntropy',
    custom_loss=['AUC'],
    random_seed=42
)

categorical_features_indices = np.where(X.dtypes != np.float)[0]
`
**Python fails here**

It has different categorical_features_indices

At 3rd code it`s `array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)`

**Comment by AndreyGurevich** [comment] 2017-11-13 19:19
There is at least one bug in my code: different columns sets in dataframe **X_train**, used for fitting and dataframe **test**, used for **predict_proba**. 
I fixed it and have no errors.

**Comment by annaveronika** [comment] 2017-11-14 11:07
CatboostError: st/catboost/libs/algo/apply.cpp:72: Insufficient float features count

This means, jupyter notebook doesn't crash, you get an exception, so it works as planned.

**Comment by annaveronika** [comment] 2017-11-14 11:08
No, it crashes, we'll add an exception.

**Comment by AndreyGurevich** [comment] 2017-11-14 11:14
It will be great. especially if exception will have text like "Data for fitting and prediction has different columns lists".

Catboost now has some situations, when wrong usage code leads to exceptions, but they are not as useful, as they can be.

**Comment by annaveronika** [comment] 2017-11-14 11:17
Could you list the situations, so that we could fix it? Or next time if you face one of those, you could create an issue or make a pr to fix it.

**Comment by AndreyGurevich** [comment] 2017-11-14 11:23
I`ll try at least create new issues.

**Comment by annaveronika** [comment] 2017-11-25 15:36
it should give a more clear message now.

**Closed by annaveronika** 2017-11-25 15:36 UTC
Labels: in progress
