### ISSUE TITLE
save_model not working in R

### ISSUE THREAD

**Issue by sylar1234** [catboost/catboost#342] opened 2018-05-08 11:45 UTC
Problem: I am trying to save catboost model but it throws an error 

Code - fit_params <- list(iterations = 1000,
		   eval_metric = 'RMSE',
		   od_type = 'Iter',
		   od_wait = 50,
                   thread_count = 10,
                   loss_function = 'RMSE',
                   border_count = 128,
                   depth = 10,
		   random_strength = 2,
		   bagging_temperature = 1,
                   learning_rate = 0.03,
                   l2_leaf_reg = 3,
                   train_dir = 'train_dir',
		   boosting_type = 'Ordered',
		   metric_period = 100)
				   
mymodel <- catboost.train(traincat, testcat, fit_params)

a<- catboost.save_model(mymodel, model_path = "C:/Users/u349075/Documents/catboost")

> Error in catboost.save_model(mymodel, model_path = "C:/Users/u349075/Documents/catboost") : 
>   (Access is denied.) atboost/util/system/file.cpp:619: can't open "C:/Users/u349075/Documents/catboost" with mode CreateAlways|WrOnly|Seq (0x00000034)

catboost version: v0.8.1
Operating System: Windows 7
CPU: Intel Core i5 - 5300U CPU @2.3GHz
# GPU: NA

**Comment by CliffordLai** [comment] 2018-05-17 21:30
catboost.save_model() works correctly on my windows PC, it seems that the problem was caused by the system user permission instead of catboost itself. I think you can try changing the save path.

You can also use the default R save() function to check if you have the permission to write anything on that save path.

**Comment by sylar1234** [comment] 2018-05-18 04:49
I am able to save using default R save function but when I try to load that file, R can read it but doesn't recognize it as Catboost model file.

**Comment by annaveronika** [comment] 2018-09-04 13:18
We fixed it now! The code is on github, the binaries will be provided with the next release which will be in about a week or two.

**Closed by annaveronika** 2018-09-04 13:18 UTC
Labels: R, planned

**Comment by capyy** [comment] 2018-10-18 18:07
I have the same issue with R 3.5.1 and Catboost 0.10.3.

Is it supposed to be solved ?

**Comment by annaveronika** [comment] 2018-10-18 18:13
It should work now, we'll check and get back to you

**Comment by dbakshee** [comment] 2018-10-19 06:17
Hi @capyy 

Could you elaborate on what is 'the same issue' that you see?

Once you've got a working model, you can check saving/loading with the following commands (works with Catboost 0.10.3):
```r
pred <- catboost.predict(model, test_pool)
head(pred)

### Check catboost.save_model/load_model
ignore <- catboost.save_model(model, 'tmp-model')
model1 <- catboost.load_model('tmp-model')
pred1 <- catboost.predict(model1, test_pool)
head(pred1)
all(pred1 == pred)

### Check R save/load
save(model, file='tmp-env')
env1 <- new.env()
load('tmp-env', envir=env1)
pred2 <- catboost.predict(env1$model, test_pool)
head(pred2)
all(pred2 == pred)

### Check R saveRDS/readRDS
saveRDS(model, file='tmp-model-rds')
model3 <- readRDS('tmp-model-rds')
pred3 <- catboost.predict(model3, test_pool)
head(pred3)
all(pred3 == pred)
```

**Comment by capyy** [comment] 2018-10-19 12:43
Hi @dbakshee,

I do not know the impact but I use catboost through caret. So I do my preduction using:
`pred <- caret::predict.train(model, newdata=x_testing, type="prob")` and it works.

I tried your code and only modified the prediction line. Let me knoe if it makes no sense.

```
    ### Check catboost.save_model/load_model 
    ignore <- catboost.save_model(model, 'tmp-model')
    model1 <- catboost.load_model('tmp-model')
    pred1 <- catboost.predict(model1, test_pool)
    head(pred1)
    all(pred1 == pred)
```
Rstudio crash on : `ignore <- catboost.save_model(model, 'tmp-model')`
```
### Check R save/load
save(model, file='tmp-env')
env1 <- new.env()
load('tmp-env', envir=env1)
#pred2 <- catboost.predict(env1$model, test_pool)
pred2 <-caret::predict.train(env1$model, newdata=x_testing, type="prob")
head(pred2)
all(pred2 == pred)
```
Rstudio crash on : `pred2 <-caret::predict.train(env1$model, newdata=x_testing, type="prob")`
```
### Check R saveRDS/readRDS
saveRDS(model, file='tmp-model-rds')
model3 <- readRDS('tmp-model-rds')
#pred3 <- catboost.predict(model3, test_pool)
pred3 <- caret::predict.train(model3, newdata=x_testing, type="prob")
head(pred3)
all(pred3 == pred)
```
Rstudio crash on : `pred3 <-caret::predict.train(model3, newdata=x_testing, type="prob")`

Thanks !

**Comment by capyy** [comment] 2018-10-19 12:54
To amswer your first question, yesterday I had the same message with "Access is denied"

But today, as you can see in my post above, it just crash. Pretty sure this is not a library but a user issue :-)

**Comment by capyy** [comment] 2018-10-20 20:06
I got the answer on Stackoverflow but here are what I was doing to have a crash:

 I was mixing 3 things wrong :

trying to saved with : save or saveRDS (R crashed)

When I tried to save with Catboost I did catboost::catboost.save_model(model, "model") instead of model$finalModel. Trying to save complete model object crash R (R crashed) (but if the model is trained with Catboost only, without Caret, it works)


When I tried to predict I used caret::predict instead of catboost.predict (R crashed)
