### ISSUE TITLE
CatboostError: catboost/cuda/cuda_lib/cuda_manager.cpp:199: Condition violated: `State == nullptr'

### ISSUE THREAD

**Issue by natyahlyi** [catboost/catboost#432] opened 2018-08-02 11:02 UTC
Problem: Trying to train model using GPU on google colab, installed cuda 9.1, while running `fit()`
got this error
```
CatboostError                             Traceback (most recent call last)
<ipython-input-29-12dd739d7ba3> in <module>()
      1 
      2 print("Started Training")
----> 3 model.fit(train_pool)

/usr/local/lib/python3.6/dist-packages/catboost/core.py in fit(self, X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds)
   2393         return self._fit(X, y, cat_features, None, sample_weight, None, None, None, None, baseline,
   2394                          use_best_model, eval_set, verbose, logging_level, plot, column_description,
-> 2395                          verbose_eval, metric_period, silent, early_stopping_rounds)
   2396 
   2397     def predict(self, data, ntree_start=0, ntree_end=0, thread_count=-1, verbose=None):

/usr/local/lib/python3.6/dist-packages/catboost/core.py in _fit(self, X, y, cat_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds)
   1070 
   1071         with log_fixup():
-> 1072             self._train(train_pool, eval_sets, params, allow_clear_pool)
   1073 
   1074         if (not self._object._has_leaf_weights_in_model()) and allow_clear_pool:

/usr/local/lib/python3.6/dist-packages/catboost/core.py in _train(self, train_pool, test_pool, params, allow_clear_pool)
    816 
    817     def _train(self, train_pool, test_pool, params, allow_clear_pool):
--> 818         self._object._train(train_pool, test_pool, params, allow_clear_pool)
    819         setattr(self, '_is_fitted', True)
    820         setattr(self, '_random_seed', self._object._get_random_seed())

_catboost.pyx in _catboost._CatBoost._train()

_catboost.pyx in _catboost._CatBoost._train()

CatboostError: catboost/cuda/cuda_lib/cuda_manager.cpp:199: Condition violated: `State == nullptr'
```
catboost version: 0.9.1.1
Operating System: Linux (Google Colab)
# GPU: K80

**Comment by annaveronika** [comment] 2018-09-13 14:26
Can you please try running the latest version 0.10?

**Comment by GaGaMan1101** [comment] 2019-08-13 07:12
@annaveronika  I had this error when I ran the `CatboostRegressor` using GPU, 
but it seems fine when I switch to CPU. 

It was ok to use 0.13 catboost with cuda 10 on GPU, however now always erros with GPU

**Comment by annaveronika** [comment] 2019-11-14 09:56
@GaGaMan1101 Could you please provide a reproducing example with the latest version of catboost (later than 0.18) ?

**Comment by vbugaevskii** [comment] 2020-01-26 12:31
Get same error with CUDA 10.1 for catboost==0.20.2.

```bash
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

```
---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
<ipython-input-13-0878d722a4e7> in <module>
     26         cl = CatBoostRegressor(max_depth=8, thread_count=16, verbose=True,
     27                                task_type='GPU', random_state=seed)
---> 28         cl = cl.fit(X_train, y_train[target])
     29 
     30         y_pred = cl.predict(X_valid)

/catboost/catboost/python-package/catboost/core.py in fit(self, X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   4377                          use_best_model, eval_set, verbose, logging_level, plot, column_description,
   4378                          verbose_eval, metric_period, silent, early_stopping_rounds,
-> 4379                          save_snapshot, snapshot_file, snapshot_interval, init_model)
   4380 
   4381     def predict(self, data, ntree_start=0, ntree_end=0, thread_count=-1, verbose=None):

/catboost/catboost/python-package/catboost/core.py in _fit(self, X, y, cat_features, text_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   1724                 params,
   1725                 allow_clear_pool,
-> 1726                 train_params["init_model"]
   1727             )
   1728 

/catboost/catboost/python-package/catboost/core.py in _train(self, train_pool, test_pool, params, allow_clear_pool, init_model)
   1253 
   1254     def _train(self, train_pool, test_pool, params, allow_clear_pool, init_model):
-> 1255         self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
   1256         self._set_trained_model_attributes()
   1257 

_catboost.pyx in _catboost._CatBoost._train()

_catboost.pyx in _catboost._CatBoost._train()

CatBoostError: catboost/cuda/cuda_lib/cuda_manager.cpp:201: Condition violated: `State == nullptr'
```

I've tried to build the library manually according to the instruction [here](https://catboost.ai/docs/installation/python-installation-method-build-from-source-linux-macos.html#python-installation-method-build-from-source-linux-macos), but it didn't help.

Here is installation command:

```
../../../ya make -r -j4 -DUSE_ARCADIA_PYTHON=no -DHAVE_CUDA=yes -DCUDA_ROOT=/usr/local/cuda-10.1/ -DPYTHON_CONFIG=python3-config -DOS_SDK=local
```

**Comment by kizill** [comment] 2020-01-27 11:07
Could you reproduce such an issue with official catboost wheel from pypi?

**Comment by bobbyt2012** [comment] 2020-01-27 15:24
I'm having the same issue. Happened when I upgraded to 20.2, but persists when I uninstalled and reverted to 18.2.

**Comment by kizill** [comment] 2020-01-27 15:56
@bobbyt2012 hope you can help us sending minimal reproducing code sample!

**Comment by bobbyt2012** [comment] 2020-01-27 17:36
@kizill I can't provide the data, but I believe I have alleviated the issue. I believe it was caused by a bad update or uninstall/reinstall. I built a new virtualenv and installed the latest version of catboost and it appears to be functioning as usual now. 

```
cat_features_index = np.array([0,1,2,3,4,5,6,7,12])
model = CatBoostRegressor(max_depth=12, learning_rate=0.15, loss_function='RMSE', task_type = 'GPU',
                          grow_policy = 'Lossguide', n_estimators=1500)

model.fit(X_train, y_train, cat_features=cat_features_index, eval_set=(X_test, y_test), plot=True)
```

Thanks for all the work you do.

**Comment by annaveronika** [comment] 2020-01-28 08:26
closing the issue then

**Closed by annaveronika** 2020-01-28 08:26 UTC
Labels: GPU, need info

**Comment by xnuohz** [comment] 2020-02-21 14:08
Get same error with CUDA 9.0 and Python 3.6.9 for catboost==0.21.

**Comment by kizill** [comment] 2020-02-21 14:31
We currently need CUDA driver >= 9.2, could you update and try again?

**Comment by kirtan-desai** [comment] 2020-04-14 16:50
I am having the same issue on google colab with catboost 0.22

CatBoostError: catboost/cuda/cuda_lib/cuda_manager.cpp:201: Condition violated: `State == nullptr'

What should I do?

**Comment by khaled-2020** [comment] 2020-11-08 16:44
cat_model.fit(X_train,y_train, cat_features=categorical_features_indices)
CatBoostError                             Traceback (most recent call last)
<ipython-input-243-9e71dc39973f> in <module>
----> 1 cat_model.fit(X_train,y_train, cat_features=categorical_features_indices)

~\anaconda3\lib\site-packages\catboost\core.py in fit(self, X, y, cat_features, text_features, embedding_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   4296         self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
   4297                   eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period,
-> 4298                   silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   4299         return self
   4300 

~\anaconda3\lib\site-packages\catboost\core.py in _fit(self, X, y, cat_features, text_features, embedding_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   1807                 params,
   1808                 allow_clear_pool,
-> 1809                 train_params["init_model"]
   1810             )
   1811 

~\anaconda3\lib\site-packages\catboost\core.py in _train(self, train_pool, test_pool, params, allow_clear_pool, init_model)
   1256 
   1257     def _train(self, train_pool, test_pool, params, allow_clear_pool, init_model):
-> 1258         self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
   1259         self._set_trained_model_attributes()
   1260 

_catboost.pyx in _catboost._CatBoost._train()

_catboost.pyx in _catboost._CatBoost._train()

CatBoostError: c:/program files (x86)/go agent/pipelines/buildmaster/catboost.git/catboost/cuda/cuda_lib/cuda_manager.cpp:201: Condition violated: `State == nullptr'

**Comment by ul611** [comment] 2021-07-17 15:36
The same problem 
CatBoostError: catboost/cuda/cuda_lib/cuda_manager.cpp:201: Condition violated: `State == nullptr'

CatBoost version '0.25.1'
Actually, it's really strange because yesterday I ran the same code and everything was alright. I didn't upgrade or reinstall anything. I even didn't turn the internet on)

What should I do?

**Comment by SandyBy** [comment] 2021-08-25 02:17
> The same problem
> CatBoostError: catboost/cuda/cuda_lib/cuda_manager.cpp:201: Condition violated: `State == nullptr'
> 
> CatBoost version '0.25.1'
> Actually, it's really strange because yesterday I ran the same code and everything was alright. I didn't upgrade or reinstall anything. I even didn't turn the internet on)
> 
> What should I do?

same problem. cpu goes well but quite slow, gpu failed. have you solved it?

**Comment by sintaanjelina** [comment] 2022-02-28 16:08
`
CatBoostError                             Traceback (most recent call last)
e:\sub.ipynb Cell 70' in <cell line: 7>()
      1 from catboost import CatBoostClassifier
      4 cb_clf = CatBoostClassifier(iterations=1000,
      5                            task_type="GPU",
      6                            devices='0:1')
----> 7 cb_clf.fit(df_train_set,
      8           df_train_labels,
      9           verbose=False)
     11 y_pred_cb = cb_clf.predict(df_test_set)
     13 print("Cat Boosting:")

File E:\Program\myvenv\lib\site-packages\catboost\core.py:4768, in CatBoostClassifier.fit(self, X, y, cat_features, text_features, embedding_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   4765 if 'loss_function' in params:
   4766     CatBoostClassifier._check_is_compatible_loss(params['loss_function'])
-> 4768 self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
   4769           eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period,
   4770           silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   4771 return self

File E:\Program\myvenv\lib\site-packages\catboost\core.py:2089, in CatBoost._fit(self, X, y, cat_features, text_features, embedding_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   2085 allow_clear_pool = train_params["allow_clear_pool"]
   2087 with log_fixup(log_cout, log_cerr), \
   2088     plot_wrapper(plot, [_get_train_dir(self.get_params())]):
-> 2089     self._train(
   2090         train_pool,
   2091         train_params["eval_sets"],
   2092         params,
   2093         allow_clear_pool,
   2094         train_params["init_model"]
   2095     )
   2097 # Have property feature_importance possibly set
   2098 loss = self._object._get_loss_function_name()

File E:\Program\myvenv\lib\site-packages\catboost\core.py:1516, in _CatBoostBase._train(self, train_pool, test_pool, params, allow_clear_pool, init_model)
   1515 def _train(self, train_pool, test_pool, params, allow_clear_pool, init_model):
-> 1516     self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
   1517     self._set_trained_model_attributes()

File _catboost.pyx:4402, in _catboost._CatBoost._train()

File _catboost.pyx:4451, in _catboost._CatBoost._train()

CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/cuda/cuda_lib/cuda_manager.cpp:201: Condition violated: `State == nullptr'`

Catboost version 1.0.4.
ipywidgets           7.6.5

Same problem with catboost GPU. what should i do?

**Comment by yk4r2** [comment] 2022-07-04 07:33
```python
---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
<timed exec> in <module>

~/.pyenv/versions/kaggle/lib/python3.7/site-packages/catboost/core.py in fit(self, X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   5591                          use_best_model, eval_set, verbose, logging_level, plot, column_description,
   5592                          verbose_eval, metric_period, silent, early_stopping_rounds,
-> 5593                          save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   5594 
   5595     def predict(self, data, prediction_type=None, ntree_start=0, ntree_end=0, thread_count=-1, verbose=None, task_type="CPU"):

~/.pyenv/versions/kaggle/lib/python3.7/site-packages/catboost/core.py in _fit(self, X, y, cat_features, text_features, embedding_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   2281                 params,
   2282                 allow_clear_pool,
-> 2283                 train_params["init_model"]
   2284             )
   2285 

~/.pyenv/versions/kaggle/lib/python3.7/site-packages/catboost/core.py in _train(self, train_pool, test_pool, params, allow_clear_pool, init_model)
   1703 
   1704     def _train(self, train_pool, test_pool, params, allow_clear_pool, init_model):
-> 1705         self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
   1706         self._set_trained_model_attributes()
   1707 

_catboost.pyx in _catboost._CatBoost._train()

_catboost.pyx in _catboost._CatBoost._train()

CatBoostError: catboost/cuda/cuda_lib/cuda_manager.cpp:201: Condition violated: `State == nullptr'
```
Same here((

**Comment by napzter13** [comment] 2022-09-30 10:53
Same here.. Doesn't matter how much I reinstall environments and drivers etc...

`File c:\ProgramData\Anaconda3\envs\py39gpu\lib\site-packages\catboost\core.py:5128, in CatBoostClassifier.fit(self, X, y, cat_features, text_features, embedding_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, plot_file, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   5125 if 'loss_function' in params:
   5126     CatBoostClassifier._check_is_compatible_loss(params['loss_function'])
-> 5128 self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
   5129           eval_set, verbose, logging_level, plot, plot_file, column_description, verbose_eval, metric_period,
   5130           silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   5131 return self

File c:\ProgramData\Anaconda3\envs\py39gpu\lib\site-packages\catboost\core.py:2355, in CatBoost._fit(self, X, y, cat_features, text_features, embedding_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, plot_file, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
...
File _catboost.pyx:4622, in _catboost._CatBoost._train()

File _catboost.pyx:4671, in _catboost._CatBoost._train()

CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/cuda/cuda_lib/cuda_manager.cpp:201: Condition violated: `State == nullptr'`

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2022-09-30 12:26
@napzter13 
4 years have passed, and we still don't have an end-to-end reproducer for this problem :(
maybe you could provide one?

**Comment by napzter13** [comment] 2022-09-30 12:45
> @napzter13 4 years have passed, and we still don't have an end-to-end reproducer for this problem :( maybe you could provide one?

Sure. It is specifically when using the 'CUDA_VISIBLE_DEVICES' registry.

This code:
```
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

from catboost import CatBoostClassifier

train_data = [[0, 3],
              [4, 1],
              [8, 1],
              [9, 1]]
train_labels = [0, 0, 1, 1]

model = CatBoostClassifier(iterations=2000,
                            depth = 15,
                           task_type="GPU")
model.fit(train_data,
          train_labels,
          verbose=True)
```

Produces at my end:
```
CatBoostError                             Traceback (most recent call last)
Cell In [3], line 14
      9 train_labels = [0, 0, 1, 1]
     11 model = CatBoostClassifier(iterations=2000,
     12                             depth = 15,
     13                            task_type="GPU")
---> 14 model.fit(train_data,
     15           train_labels,
     16           verbose=True)

File c:\ProgramData\Anaconda3\envs\py39gpu\lib\site-packages\catboost\core.py:5128, in CatBoostClassifier.fit(self, X, y, cat_features, text_features, embedding_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, plot_file, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   5125 if 'loss_function' in params:
   5126     CatBoostClassifier._check_is_compatible_loss(params['loss_function'])
-> 5128 self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
   5129           eval_set, verbose, logging_level, plot, plot_file, column_description, verbose_eval, metric_period,
   5130           silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   5131 return self

File c:\ProgramData\Anaconda3\envs\py39gpu\lib\site-packages\catboost\core.py:2355, in CatBoost._fit(self, X, y, cat_features, text_features, embedding_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, plot_file, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   2351 allow_clear_pool = train_params["allow_clear_pool"]
   2353 with log_fixup(log_cout, log_cerr), \
   2354     plot_wrapper(plot, plot_file, 'Training plots', [_get_train_dir(self.get_params())]):
-> 2355     self._train(
   2356         train_pool,
...
File _catboost.pyx:4622, in _catboost._CatBoost._train()

File _catboost.pyx:4671, in _catboost._CatBoost._train()

CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/cuda/cuda_lib/cuda_manager.cpp:201: Condition violated: `State == nullptr'
```

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2022-10-03 07:37
seems like i did not publish my response
your reproducer works for me from jupyter notebook and from command-line python
![image](https://user-images.githubusercontent.com/7053671/193523652-81ca1bcf-ef65-4846-ab1c-225baa4562c1.png)
i also checked that `import catboost` + train + `del catboost` + `import catboost` + train works
