### ISSUE TITLE
make[2]: *** [contrib/tools/flatc/bin/CMakeFiles/flatc.dir/build.make:127: contrib/tools/flatc/bin/flatc] Error 1

### ISSUE THREAD

**Issue by lijunruan** [catboost/catboost#2336] opened 2023-03-22 11:37 UTC
Problem:make[2]: *** [contrib/tools/flatc/bin/CMakeFiles/flatc.dir/build.make:127: contrib/tools/flatc/bin/flatc] Error 1
catboost version:1.1.1
Operating System: Oracle Linux 8 on ARM
CPU: Yes
GPU: No
Info:
Ｉhave followed the doc. https://catboost.ai/en/docs/installation/cli-installation-cmake-install 
gcc :  8.5.0 20210514 (Red Hat 8.5.0-16.0.2)
jdk :  "18.0.2.1" 2022-08-18
python3.6
When I exec :　cmake --build catboost　
Then :
stdexcept.cpp:(.text._ZNSt11logic_erroraSERKS_+0x24): undefined reference to `__aarch64_ldadd4_acq_rel'
stdexcept.cpp:(.text._ZNSt11logic_erroraSERKS_+0x30): undefined reference to `__aarch64_ldadd4_acq_rel'
../../../libs/cxxsupp/libcxx/liblibs-cxxsupp-libcxx.a(stdexcept.cpp.o): In function `std::runtime_error::runtime_error(std::runtime_error const&)':
stdexcept.cpp:(.text._ZNSt13runtime_errorC2ERKS_+0x20): undefined reference to `__aarch64_ldadd4_acq_rel'
../../../libs/cxxsupp/libcxx/liblibs-cxxsupp-libcxx.a(stdexcept.cpp.o): In function `std::runtime_error::operator=(std::runtime_error const&)':
stdexcept.cpp:(.text._ZNSt13runtime_erroraSERKS_+0x24): undefined reference to `__aarch64_ldadd4_acq_rel'
../../../libs/cxxsupp/libcxx/liblibs-cxxsupp-libcxx.a(stdexcept.cpp.o):stdexcept.cpp:(.text._ZNSt13runtime_erroraSERKS_+0x30): more undefined references to `__aarch64_ldadd4_acq_rel' follow
../../../libs/cxxsupp/libcxx/liblibs-cxxsupp-libcxx.a(new.cpp.o): In function `std::set_new_handler(void (*)())':
new.cpp:(.text._ZSt15set_new_handlerPFvvE+0x10): undefined reference to `__aarch64_swp8_acq_rel'
../../../libs/cxxsupp/libcxxrt/liblibs-cxxsupp-libcxxrt.a(guard.cc.o): In function `__cxa_guard_acquire':
guard.cc:(.text.__cxa_guard_acquire+0x38): undefined reference to `__aarch64_cas8_acq_rel'
guard.cc:(.text.__cxa_guard_acquire+0x5c): undefined reference to `__aarch64_cas8_acq_rel'
../../../libs/cxxsupp/libcxxrt/liblibs-cxxsupp-libcxxrt.a(guard.cc.o): In function `__cxa_guard_abort':
guard.cc:(.text.__cxa_guard_abort+0x14): undefined reference to `__aarch64_cas8_acq_rel'
../../../libs/cxxsupp/libcxxrt/liblibs-cxxsupp-libcxxrt.a(guard.cc.o): In function `__cxa_guard_release':
guard.cc:(.text.__cxa_guard_release+0x14): undefined reference to `__aarch64_cas8_acq_rel'
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [contrib/tools/flatc/bin/CMakeFiles/flatc.dir/build.make:127: contrib/tools/flatc/bin/flatc] Error 1
make[1]: *** [CMakeFiles/Makefile2:19679: contrib/tools/flatc/bin/CMakeFiles/flatc.dir/all] Error 2
make: *** [Makefile:101: all] Error 2

**Comment by lijunruan** [comment] 2023-03-28 03:24
may solve this problem？

**Comment by andrey-khropov** [comment] 2023-03-28 09:48
Do you need to build from the codebase that corresponds exactly to CatBoost version 1.1.1 ?

If you are ok with building from master you should try build using the following:

1) Prerequisites:
- python 3.7+
- CMake 3.18+
- CLang 12+
- Conan (1.57-1.59, 2.x won't work for now)
- Some build program (ninja is preferable but make is also possible) 

2) If catboost is cloned from github to the directory $catboost_src_dir :

```
cmake $catboost_src_dir -B $build_dir -G  $generator -DCMAKE_BUILD_TYPE=$build_type -DCMAKE_TOOLCHAIN_FILE=$catboost_src_dir/build/toolchains/clang.toolchain -DCATBOOST_COMPONENTS=$catboost_components
```

where

`$generator` - “Ninja" for Ninja or “Unix Makefiles” for make.
`$build_type` - build type - `Debug` or `Release`
`$catboost_components` - ";"-separated components from CatBoost to build (configure for all components if not specified):

 - `app` - build catboost app
 - `libs` - application libraries from `libs/model_interface`
 - `R-package` - for R package shared library
 - `python-package` - for Python package shared library
 - `jvm-packages` - for JVM applier
 - `spark` - for packages for Spark

`clang.toolchain` expects that `clang` will point to `clang` 12+, if the default `clang` has version less than 12 then you have to either replace `clang` with the `clang` with the newer version (like `clang-12`, `clang++-12`).
Or either copy the toolchain to the new file and make the necessary changes there and pass it to `CMAKE_TOOLCHAIN_FILE` instead. 

3. After cmake run either

```
ninja -C $build_dir $targets
```

or 

```
make -C $build_dir -j $build_threads_count  $targets
```
where `$targets` is space-separated list of binary artefacts to build:
- `catboost` - CLI app
- `_catboost` - python package shared library
-  `catboostmodel` - C/C++ applier shared library
-  `catboostmodel_static` - C/C++ applier static library with CatBoost dependencies linked in.
- `catboost_train_interface` - C/C++ train API shared library
- `catboost4j-prediction` - JVM applier JNI shared library
- `catboost4j-spark-impl` - Spark native JNI shared library part.
- `catboostr` - R package shared library

**Comment by lijunruan** [comment] 2023-04-04 05:13
Thanks andrey-khropov,I have got the following issue:

root@instance-aarch:/home/ubuntu/5/catboost# ninja -C ./ catboost
ninja: Entering directory `./'
[2751/3722] Linking CXX executable contrib/tools/flatc/bin/flatc
FAILED: contrib/tools/flatc/bin/flatc
: && /usr/bin/clang++-13 -fexceptions   -fno-common   -fcolor-diagnostics   -faligned-allocation   -fdebug-default-version=4   -ffunction-sections   -fdata-sections   -Wall   -Wextra   -Wno-parentheses   -Wno-implicit-const-int-float-conversion   -Wno-unknown-warning-option   -pipe   -D_THREAD_SAFE   -D_PTHREADS   -D_REENTRANT   -D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES   -D_LARGEFILE_SOURCE   -D__STDC_CONSTANT_MACROS   -D__STDC_FORMAT_MACROS   -D__LONG_LONG_SUPPORTED  -D_GNU_SOURCE -DLIBCXX_BUILDING_LIBCXXRT -fuse-init-array -D_FILE_OFFSET_BITS=64 -fsigned-char   -Woverloaded-virtual   -Wimport-preprocessor-directive-pedantic   -Wno-undefined-var-template   -Wno-return-std-move   -Wno-defaulted-function-deleted   -Wno-pessimizing-move   -Wno-deprecated-anon-enum-enum-conversion   -Wno-deprecated-enum-enum-conversion   -Wno-deprecated-enum-float-conversion   -Wno-ambiguous-reversed-operator   -Wno-deprecated-volatile  -O3 -DNDEBUG -lc -lm -nodefaultlibs -ldl -lrt -Wl,--no-as-needed -fPIC -lpthread contrib/tools/flatc/bin/CMakeFiles/flatc.dir/__/__/__/libs/flatbuffers/src/flatc_main.cpp.o contrib/tools/flatc/bin/CMakeFiles/flatc.dir/__vcs_version__.c.o -o contrib/tools/flatc/bin/flatc  library/cpp/malloc/jemalloc/libcpp-malloc-jemalloc.a  contrib/libs/flatbuffers/flatc/liblibs-flatbuffers-flatc.a  library/cpp/malloc/api/libcpp-malloc-api.a  contrib/libs/jemalloc/libcontrib-libs-jemalloc.a  contrib/libs/cxxsupp/libcxx/liblibs-cxxsupp-libcxx.a  contrib/libs/cxxsupp/libcxxabi-parts/liblibs-cxxsupp-libcxxabi-parts.a  contrib/libs/cxxsupp/libcxxrt/liblibs-cxxsupp-libcxxrt.a  contrib/libs/libunwind/libcontrib-libs-libunwind.a  contrib/libs/cxxsupp/builtins/liblibs-cxxsupp-builtins.a && :
/usr/bin/ld: contrib/libs/jemalloc/libcontrib-libs-jemalloc.a(prof_log.c.o): in function `je_prof_try_log':
prof_log.c:(.text.unlikely.je_prof_try_log+0x1d4): undefined reference to `__aarch64_ldadd8_relax'
/usr/bin/ld: contrib/libs/jemalloc/libcontrib-libs-jemalloc.a(prof_log.c.o): in function `prof_log_thr_index':
prof_log.c:(.text.prof_log_thr_index+0x120): undefined reference to `__aarch64_ldadd8_relax'
/usr/bin/ld: contrib/libs/jemalloc/libcontrib-libs-jemalloc.a(prof_log.c.o): in function `prof_log_bt_index':
prof_log.c:(.text.prof_log_bt_index+0x11c): undefined reference to `__aarch64_ldadd8_relax'
/usr/bin/ld: contrib/libs/jemalloc/libcontrib-libs-jemalloc.a(prof_log.c.o): in function `je_prof_log_start':
prof_log.c:(.text.unlikely.je_prof_log_start+0x9c): undefined reference to `atexit'

**Comment by andrey-khropov** [comment] 2024-01-30 13:44
Duplicate of #2527

**Closed by andrey-khropov** 2024-01-30 13:44 UTC
Labels: build
