### ISSUE TITLE
Error "Attempt to call single feature writer on packed feature writer" with embedding features on GPU

### ISSUE THREAD

**Issue by highly0** [catboost/catboost#2591] opened 2024-02-05 09:12 UTC
Problem: 
I'm trying to train a regression task with a dataset that includes numerical, text, and embedding features (which includes sentence embeddings using MPNET and TFIDF vectors; all in numpy arrays format). Previously, I was able to train the same regression model without the embedding features (If I dropped all embedding features from X_train and X_test, training is successful and very fast). However, when I included the embedding features, I get this error "Attempt to call single feature writer on packed feature writer" (it took 20 minutes for training on GPU to produce this error on `verbose=1`). Initially, I had the param`verbose=200`, so training failed hours after I started it. Any insights as to why this error popped up?

UPDATE: training on CPU on the dataset with numerical, text, and embedding features was succesful. It seems like there is a bug with the GPU training for embedding features?

catboost version: 1.2.2
GPU:  NVIDIA GeForce RTX 3090

**Comment by Dforgeek** [comment] 2024-02-14 08:43
Having the same problem. Asked question on stackoverflow yesterday: https://stackoverflow.com/questions/77987029/getting-catboosterror-attempt-to-call-single-feature-writer-on-packed-feature

Version: 1.2.2
GPU: A100/V100

Unfortunately, I don't have access to the older versions of catboost now, but I definitely remember that there was no such problem on one of the older versions. If you have the opportunity, I advise you to try to install other version of catboost package (for example - 1.1)

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2024-03-29 06:44
Looks like duplicate of https://github.com/catboost/catboost/issues/2249

This error is occurs, if embedding encoders produces a binary feature

**Closed** 2024-03-29 11:08 UTC
Labels: bug, GPU

**Comment by korotaS** [comment] 2024-06-05 11:53
I had the same issue with embeddings on GPU (on versions 1.1 and 1.2.5), but my solution was quite strange. 
Initially I had such features: `emb_0, score_0, class_0, ..., emb_N, score_N, class_N`, where `emb_i` was an embedding and `class_i` was a categorical feature, and it was training without errors. I caught this error when I added one more embedding feature **before** all other features. After I placed that embedding feature **after** all other features, the error was gone...

**Comment by dudelstein** [comment] 2025-01-21 20:49
Hi, I'm still having this issue when training on Sagemaker with catboost version 1.2.7 on GPU with numerical embedding features. I made sure the embedding features are the last in my dataframe. Has anyone experienced this?

**Comment by dalgu90** [comment] 2025-02-19 16:45
I'm having a similar issue when there are only categorical and embedding features in a dataset (no numerical features). I just downgraded to 1.2.5 to get around this without knowing the issue.

**Comment by dudelstein** [comment] 2025-02-19 16:55
@dalgu90 thanks for commenting, is it the case that when there's a numerical feature the algorithm works? I'm pretty sure I also just have categoricals and an embedding.
