### ISSUE TITLE
`Unsupported .eh_frame_hdr version` and `Can't convert bad label back to class name` errors in python

### ISSUE THREAD

**Issue by radrow** [catboost/catboost#565] opened 2018-12-03 10:14 UTC
Problem: Trying to predict multiclass classification leads to different errors on different machines 
catboost version: 0.11.1
Operating System: Linux 4.19.4-arch1-1-ARCH and 4.4.0-81-generic #104-Ubuntu
CPU: Intel(R) Core(TM) i7-7700HQ and Intel(R) Xeon(R) CPU E5-2630 v4
Python version: 3.7.1 and 3.6.7

I have tried to run following snippet of code:

```python
from catboost import CatBoostClassifier
import pandas as pd

X_train = pd.DataFrame(data={
    'ft1': [1,1,2],
    'ft2': [1,2,3],
    'ft3': [1,2,1],
})
y_train = pd.Series([1,2,3])

X_train.index.name = 'object_id'
y_train.index.name = 'object_id'

cat_model = CatBoostClassifier(
                         learning_rate=0.3,
                         loss_function='MultiClass',
                         custom_loss=['Accuracy'],
                         random_seed=3721,
                         max_depth=7,
                         n_estimators=100,
                         reg_lambda=0.1,
                         logging_level='Verbose',
)


cat_model.fit(X_train, y=y_train, eval_set=[(X_train, y_train)], early_stopping_rounds=50)
cat_model.predict(X_train)
print("DONE")

```

Which resulted in following errors:
With python 3.7.1:
```
libunwind: decodeEHHdr /var/lib/go-agent/pipelines/BuildMaster/catboost.git/contrib/libs/libunwind_master/src/EHHeaderParser.hpp:62 - Unsupported .eh_frame_hdr version
[1]    28328 abort (core dumped)  python cat.py
```

With python 3.6.7:
```
Traceback (most recent call last):
  File "/home/radek/cat.py", line 27, in <module>
    cat_model.predict(X_train)
  File "/home/radek/.conda/envs/plasticc/lib/python3.6/site-packages/catboost/core.py", line 2190, in predict
    return self._predict(data, prediction_type, ntree_start, ntree_end, thread_count, verbose)
  File "/home/radek/.conda/envs/plasticc/lib/python3.6/site-packages/catboost/core.py", line 1269, in _predict
    return np.transpose(self._base_predict_multi(data, prediction_type, ntree_start, ntree_end, thread_count, verbose))
  File "/home/radek/.conda/envs/plasticc/lib/python3.6/site-packages/catboost/core.py", line 875, in _base_predict_multi
    return self._object._base_predict_multi(pool, prediction_type, ntree_start, ntree_end, thread_count, verbose)
  File "_catboost.pyx", line 1561, in _catboost._CatBoost._base_predict_multi
  File "_catboost.pyx", line 1576, in _catboost._CatBoost._base_predict_multi
  File "_catboost.pyx", line 1877, in _catboost._convert_to_visible_labels
_catboost.CatboostError: catboost/libs/labels/external_label_helper.cpp:80: Can't convert bad label back to class name.
```

The problem is reproducible with different kinds of dataframes and also with "MultiClassOneVsAll" loss. I suspect that error for 3.7.1 is a kind of bug or library-version issue, but completely I don't understand the second one. Is it my mistake or some kind of internal problem? If the first one, what could be most general reason for this exception to be risen?

**Comment by GuillemGSubies** [comment] 2018-12-04 14:23
#523

**Comment by annaveronika** [comment] 2018-12-11 19:38
closed as duplicate

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2018-12-12 06:31
Now noexecstack is on by default. https://github.com/catboost/catboost/commit/4883e73504aadf44e2689c7059770c55536eeeab

**Comment by elbaro** [comment] 2018-12-20 07:49
Still having this issue in Python 3.7.1, libunwind 1.2.1-2.

```
sudo pip install catboost

pip show catboost
Name: catboost
Version: 0.11.2
```

```
libunwind: decodeEHHdr /var/lib/go-agent/pipelines/BuildMaster/catboost.git/contrib/libs/libunwind_master/src/EHHeaderParser.hpp:62 - Unsupported .eh_frame_hdr version
zsh: abort (core dumped)  python cat.py predict
```

The code for the Titanic task is [here](https://ideone.com/mmjvaI)

**Comment by yazevnul** [comment] 2019-01-14 07:22
Hi, we'll look into this issue (internal id MLTOOLS-2840).

**Comment by yazevnul** [comment] 2019-01-14 08:39
How much RAM do you have? 

Can you try running
```bash
/usr/bin/time -v python cat.py predict
```
And show me output?

And can you try to give me a core dump, or at least a stack trace? To obtain a stack trace you'll need to run:
```bash
gdb -q -- python cat.py predict
set follow-fork-mode child // this one and the rest you'll need to enter in GDB session
catch throw
r
bt
```

**Comment by elbaro** [comment] 2019-01-14 10:09
I have a 64GB RAM and it crashes immediately.

```
❯ /usr/bin/time -v python cat.py predict
--
libunwind: decodeEHHdr /var/lib/go-agent/pipelines/BuildMaster/catboost.git/contrib/libs/libunwind_master/src/EHHeaderParser.hpp:62 - Unsupported .eh_frame_hdr version
Command terminated by signal 6
    Command being timed: "python cat.py predict"
    User time (seconds): 0.58
    System time (seconds): 0.39
    Percent of CPU this job got: 68%
    Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.43
    Average shared text size (kbytes): 0
    Average unshared data size (kbytes): 0
    Average stack size (kbytes): 0
    Average total size (kbytes): 0
    Maximum resident set size (kbytes): 247316
    Average resident set size (kbytes): 0
    Major (requiring I/O) page faults: 0
    Minor (reclaiming a frame) page faults: 32378
    Voluntary context switches: 56
    Involuntary context switches: 59
    Swaps: 0
    File system inputs: 0
    File system outputs: 0
    Socket messages sent: 0
    Socket messages received: 0
    Signals delivered: 0
    Page size (bytes): 4096
    Exit status: 0
```

```
❯ coredumpctl info 23354

           PID: 23354
           UID: 1000
           GID: 1000
        Signal: 6 (ABRT)
  Command Line: /usr/bin/python cat.py predict
    Executable: /usr/bin/python3.7
 Control Group: /user.slice/user-1000.slice/session-4.scope
          Unit: session-4.scope
         Slice: user-1000.slice
       Session: 4
     Owner UID: 1000
       Boot ID: 10223e8d052c409eba09cfa5d8a5444e
    Machine ID: ad202e73f4064d47b3da38948e2eba25
       Storage: /var/lib/systemd/coredump/core.python.1000.10223e8d052c409eba09cfa5d8a5444e.23354.1547459371000000.lz4
       Message: Process 23354 (python) of user 1000 dumped core.
                
                Stack trace of thread 23354:
                #0  0x00007ffff7de1d7f raise (libc.so.6)
                #1  0x00007ffff7dcc672 abort (libc.so.6)
                #2  0x00007fffec8de40a _ZL10assert_rtnPKcS0_iS0_ (_catboost.so)
                #3  0x00007fffec8e15d6 _ZZN9libunwind17LocalAddressSpace18findUnwindSectionsEmRNS_18UnwindInfoSectionsEENKUlP12dl_phdr_infomPvE_clES4_mS5_ (_catboost.so)
                #4  0x00007ffff7ee0fdf dl_iterate_phdr (libc.so.6)
                #5  0x00007fffec8dea4f _ZN9libunwind12UnwindCursorINS_17LocalAddressSpaceENS_16Registers_x86_64EE24setInfoBasedOnIPRegisterEb (_catboost.so)
                #6  0x00007fffec8de8ca _ZN9libunwind12UnwindCursorINS_17LocalAddressSpaceENS_16Registers_x86_64EE4stepEv (_catboost.so)
                #7  0x00007fffec8e4ed8 _Unwind_Backtrace (_catboost.so)
                #8  0x00007fffec9d2163 _ZN10TBackTrace7CaptureEv (_catboost.so)
                #9  0x00007fffeca83fbc _ZN16NCatboostOptions16TJsonFieldHelperINS_7TOptionIjEELb0EE4ReadERKN5NJson10TJsonValueEPS2_ (_catboost.so)
                #10 0x00007fffeca8aa31 _ZN16NCatboostOptions32TUnimplementedAwareOptionsLoader8LoadManyINS_7TOptionIfEEJNS2_IjEES4_NS2_INS_27TOverfittingDetectorOptionsEEENS2_I13EBoostingTypeEES4_NS_25TUnimplementedAwareOptionIjNS_15TSupportedTasksIJL9ETaskType0EEEEEENS9_IbNSA_IJLSB_1EEEEEENS9_I18EDataPartitionTypeSC_EEEEEvPT_DpPT0_ (_catboost.so)
                #11 0x00007fffeca8a936 _ZN16NCatboostOptions11CheckedLoadIJNS_7TOptionIfEES2_NS1_IjEES3_NS1_INS_27TOverfittingDetectorOptionsEEENS1_I13EBoostingTypeEES3_NS_25TUnimplementedAwareOptionIjNS_15TSupportedTasksIJL9ETaskType0EEEEEENS8_IbNS9_IJLSA_1EEEEEENS8_I18EDataPartitionTypeSB_EEEEEvRKN5NJson10TJsonValueEDpPT_ (_catboost.so)
                #12 0x00007fffeca89516 _ZN16NCatboostOptions16TBoostingOptions4LoadERKN5NJson10TJsonValueE (_catboost.so)
                #13 0x00007fffeca74cdb _ZN16NCatboostOptions16TJsonFieldHelperINS_7TOptionINS_16TBoostingOptionsEEELb0EE4ReadERKN5NJson10TJsonValueEPS3_ (_catboost.so)
                #14 0x00007fffeca74776 _ZN16NCatboostOptions32TUnimplementedAwareOptionsLoader8LoadManyINS_7TOptionINS_16TBoostingOptionsEEEJNS2_INS_28TObliviousTreeLearnerOptionsEEENS2_INS_22TDataProcessingOptionsEEENS2_INS_16TLossDescriptionEEENS2_ImEENS2_INS_17TCatFeatureParamsEEENS2_IN5NJson10TJsonValueEEESG_NS2_I13ELoggingLevelEENS2_IbEENS2_INS_14TMetricOptionsEEEEEEvPT_DpPT0_ (_catboost.so)
                #15 0x00007fffeca73a6e _ZN16NCatboostOptions11CheckedLoadIJNS_7TOptionI9ETaskTypeEENS1_INS_14TSystemOptionsEEENS1_INS_16TBoostingOptionsEEENS1_INS_28TObliviousTreeLearnerOptionsEEENS1_INS_22TDataProcessingOptionsEEENS1_INS_16TLossDescriptionEEENS1_ImEENS1_INS_17TCatFeatureParamsEEENS1_IN5NJson10TJsonValueEEESJ_NS1_I13ELoggingLevelEENS1_IbEENS1_INS_14TMetricOptionsEEEEEEvRKSI_DpPT_ (_catboost.so)
                #16 0x00007fffeca6b5d8 _ZN16NCatboostOptions16TCatBoostOptions4LoadERKN5NJson10TJsonValueE (_catboost.so)
                #17 0x00007fffeca71c98 _ZN16NCatboostOptions11LoadOptionsERKN5NJson10TJsonValueE (_catboost.so)
                #18 0x00007fffeca8dba8 _Z14CheckFitParamsRKN5NJson10TJsonValueEPK26TCustomObjectiveDescriptorPK23TCustomMetricDescriptor (_catboost.so)
                #19 0x00007fffec837dd3 _ZL41__pyx_pw_9_catboost_25_check_train_paramsP7_objectS0_ (_catboost.so)
                #20 0x00007ffff7b86118 _PyMethodDef_RawFastCallKeywords (libpython3.7m.so.1.0)
                #21 0x00007ffff7b86461 _PyCFunction_FastCallKeywords (libpython3.7m.so.1.0)
                #22 0x00007ffff7bf5a75 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                #23 0x00007ffff7b85a3b _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                #24 0x00007ffff7bf1522 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                #25 0x00007ffff7b3f879 _PyEval_EvalCodeWithName (libpython3.7m.so.1.0)
                #26 0x00007ffff7b85be2 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                #27 0x00007ffff7bf1522 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                #28 0x00007ffff7b85a3b _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                #29 0x00007ffff7bf176d _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                #30 0x00007ffff7b3f879 _PyEval_EvalCodeWithName (libpython3.7m.so.1.0)
                #31 0x00007ffff7b407a4 PyEval_EvalCodeEx (libpython3.7m.so.1.0)
                #32 0x00007ffff7b407cc PyEval_EvalCode (libpython3.7m.so.1.0)
                #33 0x00007ffff7c691e4 n/a (libpython3.7m.so.1.0)
                #34 0x00007ffff7c6a6ee PyRun_FileExFlags (libpython3.7m.so.1.0)
                #35 0x00007ffff7c6dc45 PyRun_SimpleFileExFlags (libpython3.7m.so.1.0)
                #36 0x00007ffff7c6ff43 n/a (libpython3.7m.so.1.0)
                #37 0x00007ffff7c7014c _Py_UnixMain (libpython3.7m.so.1.0)
                #38 0x00007ffff7dce223 __libc_start_main (libc.so.6)
                #39 0x000055555555505e _start (python3.7)

```

**Comment by yazevnul** [comment] 2019-01-14 12:14
Can you try to build python package from source? But you'll need to modify build script differently this time 
https://github.com/catboost/catboost/issues/610#issuecomment-453917114, append `'-DCFLAGS= _LIBUNWIND_TRACING_UNWINDING=1', -DCXXFLAGS= _LIBUNWIND_TRACING_UNWINDING=1'` and replace `'-r'` with `'-d'`. Then install python package (better use virtual environment, but you probably already know it) and try run `python3 cat.py predict`).

**Comment by yazevnul** [comment] 2019-01-14 12:21
And can you try to go to `util/system/ut`, run `ya make -dttt` in it? It will help us understand if `libunwind` doesn't work on you machine at all or this is a problem with libpython+glibc+catboost introperability.

**Comment by elbaro** [comment] 2019-01-15 05:45
```
~/catboost/util/system/ut master* ⇣
❯ ../../../ya make -dttt
Error[-WBadIncl]: in $B/util/system/ut/util-system-ut: could not resolve include file: library/testing/benchmark/bench.h included from here: $S/util/system/unaligned_mem_ut.cpp
Error[-WBadDir]: in $B/util/system/ut/util-system-ut: PEERDIR to missing directory: $S/library/testing/benchmark
Configure error (use -k to proceed)
```

**Comment by yazevnul** [comment] 2019-01-16 07:47
To be honest I have no ideas at this point :) I'll try to make a VM with Manjaro on it to reproduce your issue, will get back to you then.

And about issue with `util/system/ut` build, turns out not dependencies of published pieces of code were published on GitHub (only those, that were necessary to build CatBoost), we'll add missing dependencies in near future, but there is no deadline yet.

**Comment by kizill** [comment] 2019-07-29 15:07
fixed libunwind issues in https://github.com/catboost/catboost/commit/c9a3e0cfae2da0e441e91c07883df472e3dc9fbc
with https://github.com/llvm-mirror/libunwind/commit/216d7214f8b99a575883e5b8bec871ab1a6ea42e

**Closed by kizill** 2019-07-29 15:07 UTC
Labels: duplicate

**Comment by alexey-milovidov** [comment] 2021-04-04 02:00
@kizill The patch does not prevent printing the messages `Unsupported .eh_frame_hdr version` to stderr.
See also https://github.com/ClickHouse/ClickHouse/issues/15638
