### ISSUE TITLE
Cross validation issue - object grouping (not enough objects for splitting into requested amount of parts)

### ISSUE THREAD

**Issue by femtomc** [catboost/catboost#1607] opened 2021-03-12 16:32 UTC
Problem: Trying to run CV on a pool where n << p (366 x ~1000).
catboost version: 0.24.4
Operating System: Ubuntu 18.04
CPU: Intel Xeon Platinum 8259

Is there a minimum number of data points required as a function of num_folds and p features?

**Comment by andrey-khropov** [comment] 2021-03-12 20:58
Could you explain what do you mean by `n` and `p` ?

The general rule is that the number of data points (or the number of groups if your data contain groups) must be greater than the number of folds. Usually much greater because datasets with very small number of data points are typically not enough for good quality training or evaluation.

**Comment by femtomc** [comment] 2021-03-15 20:26
@andrey-khropov Sure! By n, I mean the number of data points. By p, I mean the number of features.

I experimented with approximately 370 data points, and asked for a 5 way split. But `CatBoost` throws an error in `cv` -- number of objects insufficient to form splits. I reduced this down to a 2-split as well, but got the same error. I wasn't sure if there was some internal checks.

If this sounds unusual -- it's likely an issue on my end, because I'm calling CatBoost through Python from another language, so it's possible that the API I setup is not working correctly.

**Comment by andrey-khropov** [comment] 2021-03-20 03:21
Sorry for a delayed response.

I cannot reproduce such an error on a simple test case:

```py
import sys

import numpy as np

import catboost as cb


print ('python version=%s' % sys.version)
print ('catboost version=%s' % cb.version.VERSION)

n = 360
p = 1000

dataset = cb.Pool(np.random.rand(n, p), label=np.random.rand(n))
results = cb.cv(
    dataset,
    params={'loss_function': 'RMSE'},
    fold_count=5,
    iterations=5
)
```

works as intended (with both fold_count=2 and fold_count=5):

```
$ ./cv_on_small_data.py 
python version=3.8.1 (default, Feb  6 2020, 23:19:34) 
[GCC 5.4.0 20160609]
catboost version=0.24.4
0:	learn: 0.5720464	test: 0.5730703	best: 0.5730703 (0)	total: 146ms	remaining: 586ms
1:	learn: 0.5620959	test: 0.5639584	best: 0.5639584 (1)	total: 236ms	remaining: 354ms
2:	learn: 0.5525033	test: 0.5553620	best: 0.5553620 (2)	total: 325ms	remaining: 217ms
3:	learn: 0.5434523	test: 0.5471322	best: 0.5471322 (3)	total: 412ms	remaining: 103ms
4:	learn: 0.5356983	test: 0.5404553	best: 0.5404553 (4)	total: 496ms	remaining: 0us
```

So, more details from you are needed to reproduce this error (source code and ideally - data, if it is not covered by NDA or something).

**Comment by kizill** [comment] 2021-04-05 22:53
Maybe you are passing group ids to CatBoost?

**Comment by kizill** [comment] 2021-04-22 11:32
Closing as irreproducible, please reopen if you can provide some code that'll reproduce this problem.

**Closed by kizill** 2021-04-22 11:32 UTC
Labels: need info

**Comment by femtomc** [comment] 2021-04-22 14:54
Likely was passing group ids to CatBoost -- you were correct. Thanks for checking back in! Fine to c lose.
