### ISSUE TITLE
why gpu model file is much bigger than cpu model with same parameters and dataset?

### ISSUE THREAD

**Issue by yuunnn** [catboost/catboost#680] opened 2019-02-19 11:26 UTC
Problem: {gpu model file is much bigger than cpu model with same parameters and dataset?}
Operating System: {redhat 7}
GPU: {tesla p100}

i train the gpu model and cpu model with same parameters and same dataset ,and same models just like:
`model.save_model('test.m',format='cbm')`

and i find the gpu model file is 1.5Gb while the cpu model file is only 35m, what should i do to fix this？

**Comment by annaveronika** [comment] 2019-02-21 20:45
This can happen if you have categorical features. Is this the case?
This probably means that gpu training has selected more categorical feature combinations.
One difference between cpu and gpu is that cpu has a regularizer that is responsible for the model size, it penalizes selecting those features that result in large models. Gpu implementation doesn't have that jet, this might be the cause.

One thing that you can to to control model size on gpu is you can set max_ctr_complexity = 1 or 2, then you will not have large combinations, and the model will be less.

**Comment by yuunnn** [comment] 2019-02-22 15:51
thanks a alot！

**Comment by annaveronika** [comment] 2019-02-22 16:02
https://github.com/catboost/catboost/issues/693 - here is an issue for model_size_reg.

**Comment by annaveronika** [comment] 2019-02-22 16:02
Should I close this issue?

**Comment by yuunnn** [comment] 2019-02-22 16:09
sure,I will close this issue,and thank you very much!
catboost helps me a lot on my recent projcet which is full of categorical features.

**Closed** 2019-02-22 16:09 UTC
Labels: need info
