### ISSUE TITLE
saving and loading a 'cbm' model

### ISSUE THREAD

**Issue by Bluesman79** [catboost/catboost#1041] opened 2019-10-18 13:27 UTC
Problem: saving a model in cbm format of just 10.9kB and then loading it cause no problem; but saving a model in cbm format of 932.4MB (same data-set was used for training both models, the small one had a few iterators and a depth of 2 while the other had 9990 iterators and depth of 15) and trying to load returns the following error: 
![Screenshot from 2019-10-18 15-23-02](https://user-images.githubusercontent.com/15981606/67097822-3745a400-f1bb-11e9-80b2-add67df4caf2.png)

I use python and also the model would be in a production environment so I would appreciate any recommendation as regards the 'best' format the model to be saved. 

Thanks in advance.

catboost version: 0.16.5
Operating System: Ubuntu18.04LTS
CPU: Intel® Core™ i9-9960X CPU @ 3.10GHz × 32 
GPU: GeForce RTX 2080 Ti/PCIe/SSE2

I forgot to mention that the training was made on GPU.

**Comment by annaveronika** [comment] 2019-10-18 13:30
Is it possible for you to share the model file?

**Comment by Bluesman79** [comment] 2019-10-18 13:31
yes sure. please tell me how and I will.

**Comment by annaveronika** [comment] 2019-10-18 13:32
please put it to some cloud and send the link to me in the email annaveronika@yandex-team.ru

**Comment by annaveronika** [comment] 2019-10-18 13:56
This is the correct way to use the model, we'll make a fix and you'll be able to load the model correctly. Until the fix is out, you can use the same version for prediction as you have used for training the model, and it should work. Very sorry for inconvenience!

**Comment by annaveronika** [comment] 2019-10-18 16:35
Actually I think the solution is very simple! Looks like the problem is that you are using format="cbm" instead of "catboost". We'll add an alias, and for now just change the format :)

**Comment by annaveronika** [comment] 2019-10-18 16:53
You can also just omit the usage of format parameter, it will be this one by default.

**Comment by Bluesman79** [comment] 2019-10-19 12:54
On the same training-set I tuned two models: the first one had ~10000 iterators and depth of 15. I saved it without using any 'format' (so by default it had the 'catboost'. Then I tried to upload it as it was, without using the 'format = catboost' parameter, but also using it. Same error. So then I retrain the model and then saved it using 'format=cbm' and tried to load it using 'format=cbm' but it didn't work (Same error). Then I trained a small parameters model (the second one) in order to see if the save and load 'cbm' process is going to work.

The second one had just a few iterators and a depth of 2 since I wanted to check if the size of the saved model had a correlation with the error. It seemed it had.

By the way, I sent you the file via wetransfer. 

Thanks a lot for your time!

**Comment by annaveronika** [comment] 2019-10-21 08:41
CatBoost builds full binary trees by default. Which means that a single tree of depth 15 has 2^15 =32768 nodes. As a result your model weights 10^4 * 2^15 * 8 bytes > 2.5 GB. And this is just for leaf values.
The latest version should give you a warning about that. Please try upgrading to the latest version and check that a warning is present.

It is recommended to use depth up to 10 or 12 if you are using the default growing strategy.

**Comment by annaveronika** [comment] 2019-10-21 09:13
So the problem is in parameters - depth 15 + 10k trees. In the last version it fails on parameter check.
Closing the issue, let us know if you'll not have the parameter check in the last version or if you have other problems!

**Closed by annaveronika** 2019-10-21 09:13 UTC

**Comment by Bluesman79** [comment] 2019-10-21 09:28
I checked it with depth 10 and it worked like a charm. I am checking it with depth 12 now. Also I am using the latest version now. Thanks.

**Comment by Bluesman79** [comment] 2019-10-21 10:01
It worked also with depth 12.
