### ISSUE TITLE
Memory leak when using threads

### ISSUE THREAD

**Issue by erikdubbelboer** [catboost/catboost#1760] opened 2021-07-02 13:19 UTC
When loading and unloading models from different threads memory isn't released.

I have a made a sample process to show the leak: https://github.com/erikdubbelboer/catboost-memory-leak

**Comment by kizill** [comment] 2021-07-16 04:11
I've reproduced this issue, thank you a lot for your code! Debugging the case.

**Comment by kizill** [comment] 2021-09-27 19:01
Finally found a root cause - that's how malloc works with system allocator, caching allocations with per thread arenas. 
To reproduce it just set either environment variable `MALLOC_ARENA_MAX=1` (in your case there would be 128 arenas, so it'll consume up to 8 arenas per thread * 128 threads * 94Mb model size ≈ 89.6Gb. Try to play with it to balance real speed and max RSS. Another way - to use alternative allocator in your program, for example tcmalloc, mimalloc etc. Another way that will mostly affect speed - setup `MALLOC_MMAP_THRESHOLD_=0` so all allocations would be through mmap syscalls, without caches. Thank you and closing as there is no actual leak :) 
I've found some related materials where you can check for details:
https://www.algolia.com/blog/engineering/when-allocators-are-hoarding-your-precious-memory/
https://sploitfun.wordpress.com/2015/02/10/understanding-glibc-malloc/

So closing as there is no actual problem :)

**Closed by kizill** 2021-09-27 19:01 UTC

**Comment by erikdubbelboer** [comment] 2021-09-28 22:43
Thanks for finding the issue. Good that it's documented here now.

We were calling catboost from Go. We fixed our issue by calling [`runtime.LockOSThread()`](https://pkg.go.dev/runtime#LockOSThread) which makes sure our code is always executed on the same thread.
