### ISSUE TITLE
Reproducible error: 'catboost/private/libs/algo/tensor_search_helpers.cpp:99: This should be unreachable'

### ISSUE THREAD

**Issue by MrIsCM** [catboost/catboost#2776] opened 2024-11-14 20:01 UTC
Problem: Catboost crashes when trying to fit it.
catboost version: '1.2.7'

I had some trouble when fitting a catboost model because it would randomly crash with the following error:

> catboost/private/libs/algo/tensor_search_helpers.cpp:99: This should be unreachable

After opening a [discussion on Kaggle](https://www.kaggle.com/competitions/playground-series-s4e10/discussion/542912) I had very helpful answers and a user ( [brocoli beef](https://www.kaggle.com/siukeitin) ) found a way to reproduce the bug.

Here is [a notebook in Kaggle reproducing the error](https://www.kaggle.com/code/mriscm/catboost-troubleshooting)

Here is the code:

```python



import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, StandardScaler
from catboost import CatBoostClassifier

import sklearn; print(F'{sklearn.__version__=}')
import catboost; print(F'{catboost.__version__=}')

train = pd.read_csv('/kaggle/input/playground-series-s4e10/train.csv', index_col='id')
original = pd.read_csv('/kaggle/input/loan-approval-prediction/credit_risk_dataset.csv')
X = pd.concat([train, original]).reset_index(drop=True)
y = X.pop('loan_status')
X_train, X_test, y_train, y_test = train_test_split(
    X, y, stratify=y, shuffle=True, test_size=0.2, random_state=2024
)
categorical_columns = X.select_dtypes(include=['object']).columns
categorical_ordinal = ['loan_grade']
categorical_onehot = categorical_columns.drop(categorical_ordinal)
preprocessor = make_column_transformer(
    (OrdinalEncoder(), categorical_ordinal),
    (OneHotEncoder(), categorical_onehot),
    remainder=StandardScaler()
)
preprocessor.fit(X_train)
X_train_prep = preprocessor.transform(X_train)
X_test_prep = preprocessor.transform(X_test)

param =  {'depth': 10, 'learning_rate': 0.06345571757885117, 'iterations': 704, 'l2_leaf_reg': 3.530853437959887e-05, 
          'border_count': 57, 'bagging_temperature': 0.7781031075121588, 'random_strength': 0.09624502165898663, 
          'scale_pos_weight': 2.8526113665010016}
model = CatBoostClassifier(**param, verbose=0, use_best_model=True, random_state=100)

model.fit(X_train_prep, y_train,
          eval_set=[(X_test_prep, y_test)],
          early_stopping_rounds=20,  # Early stopping to prevent overfitting
          verbose=False)


```

Here is the error message:

```python
---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
Cell In[2], line 34
     29 param =  {'depth': 10, 'learning_rate': 0.06345571757885117, 'iterations': 704, 'l2_leaf_reg': 3.530853437959887e-05, 
     30           'border_count': 57, 'bagging_temperature': 0.7781031075121588, 'random_strength': 0.09624502165898663, 
     31           'scale_pos_weight': 2.8526113665010016}
     32 model = CatBoostClassifier(**param, verbose=0, use_best_model=True, random_state=100)
---> 34 model.fit(X_train_prep, y_train,
     35           eval_set=[(X_test_prep, y_test)],
     36           early_stopping_rounds=20,  # Early stopping to prevent overfitting
     37           verbose=False)

File /opt/conda/lib/python3.10/site-packages/catboost/core.py:5245, in CatBoostClassifier.fit(self, X, y, cat_features, text_features, embedding_features, graph, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, plot_file, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   5242 if 'loss_function' in params:
   5243     CatBoostClassifier._check_is_compatible_loss(params['loss_function'])
-> 5245 self._fit(X, y, cat_features, text_features, embedding_features, None, graph, sample_weight, None, None, None, None, baseline, use_best_model,
   5246           eval_set, verbose, logging_level, plot, plot_file, column_description, verbose_eval, metric_period,
   5247           silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   5248 return self

File /opt/conda/lib/python3.10/site-packages/catboost/core.py:2410, in CatBoost._fit(self, X, y, cat_features, text_features, embedding_features, pairs, graph, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, plot_file, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   2407 allow_clear_pool = train_params["allow_clear_pool"]
   2409 with plot_wrapper(plot, plot_file, 'Training plots', [_get_train_dir(self.get_params())]):
-> 2410     self._train(
   2411         train_pool,
   2412         train_params["eval_sets"],
   2413         params,
   2414         allow_clear_pool,
   2415         train_params["init_model"]
   2416     )
   2418 # Have property feature_importance possibly set
   2419 loss = self._object._get_loss_function_name()

File /opt/conda/lib/python3.10/site-packages/catboost/core.py:1790, in _CatBoostBase._train(self, train_pool, test_pool, params, allow_clear_pool, init_model)
   1789 def _train(self, train_pool, test_pool, params, allow_clear_pool, init_model):
-> 1790     self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
   1791     self._set_trained_model_attributes()

File _catboost.pyx:5017, in _catboost._CatBoost._train()

File _catboost.pyx:5066, in _catboost._CatBoost._train()

CatBoostError: catboost/private/libs/algo/tensor_search_helpers.cpp:99: This should be unreachable
```

The datasets used are public in Kaggle.
- [Loan Approval Status](https://www.kaggle.com/competitions/playground-series-s4e10/data)
- [Loan Approval Prediction](https://www.kaggle.com/datasets/chilledwanker/loan-approval-prediction)

Hope it helps.
If any other detail is needed, just let me know.

**Comment by andrey-khropov** [comment] 2024-12-24 11:59
Duplicate of #2647

**Closed by andrey-khropov** 2024-12-24 11:59 UTC
Labels: in progress, crash
