### ISSUE TITLE
Exception when CatBoostRegressor is disposed

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#685] opened 2019-02-21 01:29 UTC
If I create a CatBoostRegressor instance in a script, then when the script tears down CatBoostRegressor throws an exception

i.e. save the following in a script then run it from the console

```
from catboost import CatBoostRegressor
estimator = CatBoostRegressor(loss_function='RMSE', has_time=True, logging_level='Silent', task_type='GPU', devices='0')
```

> TypeError: 'NoneType' object is not callable
> Exception ignored in: '_catboost._CatBoost.__dealloc__'
> TypeError: 'NoneType' object is not callable

catboost version: catboost==0.11.2

**Comment by annaveronika** [comment] 2019-03-01 13:58
This is a bug, thanks a lot for pointing this out, we'll fix it!

**Comment by ferasterkawi** [comment] 2020-01-11 08:53
Same problem in classification when call:
model.fit(train_data, train_labels, cat_features)

17:	learn: 0.5208805	total: 163ms	remaining: 18.1ms
18:	learn: 0.5126644	total: 164ms	remaining: 8.63ms
19:	learn: 0.5046535	total: 165ms	remaining: 0us
TypeError: 'NoneType' object is not callable
Exception ignored in: '_catboost._CatBoost.__dealloc__'
TypeError: 'NoneType' object is not callable

My versions:
print(catboost.__version__)
0.20.2
python --version
Python 3.8.1

Thanks #^_^#

**Comment by annaveronika** [comment] 2020-01-14 08:55
Sorry for the long wait! We forgot about the issue, we'll try to fix it in one of the next releases.

**Comment by andrey-khropov** [comment] 2020-02-06 20:23
> Same problem in classification when call:
> model.fit(train_data, train_labels, cat_features)
> 
> 17: learn: 0.5208805 total: 163ms remaining: 18.1ms
> 18: learn: 0.5126644 total: 164ms remaining: 8.63ms
> 19: learn: 0.5046535 total: 165ms remaining: 0us
> TypeError: 'NoneType' object is not callable
> Exception ignored in: '_catboost._CatBoost.**dealloc**'
> TypeError: 'NoneType' object is not callable
> 
> My versions:
> print(catboost.**version**)
> 0.20.2
> python --version
> Python 3.8.1
> 
> Thanks #^_^#

I was unable to reproduce the issue, please give more context (full script code, Operating system version, do you use conda or pip install?)

**Comment by david-waterworth** [comment] 2020-02-06 22:10
I'm running on Ubuntu using vscode as an editor. The code I originally posted used to reproduce the issue on catboost 0.11, since then I've upgraded both cuda and catboost and I can no longer reproduce the issue so I'll close it.

**Comment by ferasterkawi** [comment] 2020-02-10 11:07
Sorry for waiting for my reply... the problem still exists even in the new version of CatBoost.
Any example of catboost results the same alarm.

For example:
import catboost
from catboost import CatBoostClassifier
print(catboost.__version__)

cat_features = [0,1,2]

train_data = [["a", "b", 1, 4, 5, 6],
              ["a", "b", 4, 5, 6, 7],
              ["c", "d", 30, 40, 50, 60]]
print(train_data.__class__)
train_labels = [1,1,0]

model = CatBoostClassifier(iterations=20,
                           loss_function = "CrossEntropy",
                           train_dir = "crossentropy")

model.fit(train_data, train_labels, cat_features)
predictions = model.predict(train_data)

**************************************************************

0.21
<class 'list'>
0:	learn: 0.6895278	total: 93.3ms	remaining: 1.77s
1:	learn: 0.6872395	total: 99.4ms	remaining: 895ms
2:	learn: 0.6836646	total: 100ms	remaining: 569ms
3:	learn: 0.6801172	total: 101ms	remaining: 405ms
4:	learn: 0.6765972	total: 102ms	remaining: 307ms
5:	learn: 0.6743684	total: 103ms	remaining: 241ms
6:	learn: 0.6708914	total: 105ms	remaining: 194ms
7:	learn: 0.6674412	total: 110ms	remaining: 165ms
8:	learn: 0.6652545	total: 111ms	remaining: 136ms
9:	learn: 0.6630779	total: 113ms	remaining: 113ms
10:	learn: 0.6596855	total: 114ms	remaining: 93.5ms
11:	learn: 0.6563190	total: 116ms	remaining: 77.4ms
12:	learn: 0.6529783	total: 117ms	remaining: 63.1ms
13:	learn: 0.6496632	total: 118ms	remaining: 50.7ms
14:	learn: 0.6463733	total: 120ms	remaining: 39.9ms
15:	learn: 0.6431085	total: 121ms	remaining: 30.2ms
16:	learn: 0.6398685	total: 122ms	remaining: 21.5ms
17:	learn: 0.6366532	total: 124ms	remaining: 13.8ms
18:	learn: 0.6334623	total: 125ms	remaining: 6.58ms
19:	learn: 0.6302956	total: 126ms	remaining: 0us
TypeError: 'NoneType' object is not callable
Exception ignored in: '_catboost._CatBoost.__dealloc__'
TypeError: 'NoneType' object is not callable

Process finished with exit code 0

**Comment by andrey-khropov** [comment] 2020-02-11 14:00
> Sorry for waiting for my reply... the problem still exists even in the new version of CatBoost.
> Any example of catboost results the same alarm.
> 
> For example:
> 
> ```python
> import catboost
> from catboost import CatBoostClassifier
> print(catboost.__version__)
> 
> cat_features = [0,1,2]
> 
> train_data = [["a", "b", 1, 4, 5, 6],
>               ["a", "b", 4, 5, 6, 7],
>               ["c", "d", 30, 40, 50, 60]]
> print(train_data.__class__)
> train_labels = [1,1,0]
> 
> model = CatBoostClassifier(iterations=20,
>                            loss_function = "CrossEntropy",
>                            train_dir = "crossentropy")
> 
> model.fit(train_data, train_labels, cat_features)
> predictions = model.predict(train_data)
> ```
> 
> ```
> 0.21
> <class 'list'>
> 0:	learn: 0.6895278	total: 93.3ms	remaining: 1.77s
> 1:	learn: 0.6872395	total: 99.4ms	remaining: 895ms
> 2:	learn: 0.6836646	total: 100ms	remaining: 569ms
> 3:	learn: 0.6801172	total: 101ms	remaining: 405ms
> 4:	learn: 0.6765972	total: 102ms	remaining: 307ms
> 5:	learn: 0.6743684	total: 103ms	remaining: 241ms
> 6:	learn: 0.6708914	total: 105ms	remaining: 194ms
> 7:	learn: 0.6674412	total: 110ms	remaining: 165ms
> 8:	learn: 0.6652545	total: 111ms	remaining: 136ms
> 9:	learn: 0.6630779	total: 113ms	remaining: 113ms
> 10:	learn: 0.6596855	total: 114ms	remaining: 93.5ms
> 11:	learn: 0.6563190	total: 116ms	remaining: 77.4ms
> 12:	learn: 0.6529783	total: 117ms	remaining: 63.1ms
> 13:	learn: 0.6496632	total: 118ms	remaining: 50.7ms
> 14:	learn: 0.6463733	total: 120ms	remaining: 39.9ms
> 15:	learn: 0.6431085	total: 121ms	remaining: 30.2ms
> 16:	learn: 0.6398685	total: 122ms	remaining: 21.5ms
> 17:	learn: 0.6366532	total: 124ms	remaining: 13.8ms
> 18:	learn: 0.6334623	total: 125ms	remaining: 6.58ms
> 19:	learn: 0.6302956	total: 126ms	remaining: 0us
> TypeError: 'NoneType' object is not callable
> Exception ignored in: '_catboost._CatBoost.__dealloc__'
> TypeError: 'NoneType' object is not callable
> 
> Process finished with exit code 0
> ```

This code example works for me without any errors (with either MacOS 10.13 or Linux Ubumtu 16.04 or Windows 10 with python 3.8.1 and catboost 0.21). So I still need more context to reproduce (Operating system version, do you use conda or pip install?)

**Comment by ferasterkawi** [comment] 2020-02-15 15:57
Hi... I recognized that the alarm does not appear in JUPYTER notebook but still in other python environments. What is the explanation for that?

![image](https://user-images.githubusercontent.com/44900316/74591001-a245a100-501c-11ea-91a9-bf5de0349e3d.png)

**Comment by lrnilingy** [comment] 2020-03-02 19:47
> > Sorry for waiting for my reply... the problem still exists even in the new version of CatBoost.
> > Any example of catboost results the same alarm.
> > For example:
> > ```python
> > import catboost
> > from catboost import CatBoostClassifier
> > print(catboost.__version__)
> > 
> > cat_features = [0,1,2]
> > 
> > train_data = [["a", "b", 1, 4, 5, 6],
> >               ["a", "b", 4, 5, 6, 7],
> >               ["c", "d", 30, 40, 50, 60]]
> > print(train_data.__class__)
> > train_labels = [1,1,0]
> > 
> > model = CatBoostClassifier(iterations=20,
> >                            loss_function = "CrossEntropy",
> >                            train_dir = "crossentropy")
> > 
> > model.fit(train_data, train_labels, cat_features)
> > predictions = model.predict(train_data)
> > ```
> > 
> > 
> > ```
> > 0.21
> > <class 'list'>
> > 0:	learn: 0.6895278	total: 93.3ms	remaining: 1.77s
> > 1:	learn: 0.6872395	total: 99.4ms	remaining: 895ms
> > 2:	learn: 0.6836646	total: 100ms	remaining: 569ms
> > 3:	learn: 0.6801172	total: 101ms	remaining: 405ms
> > 4:	learn: 0.6765972	total: 102ms	remaining: 307ms
> > 5:	learn: 0.6743684	total: 103ms	remaining: 241ms
> > 6:	learn: 0.6708914	total: 105ms	remaining: 194ms
> > 7:	learn: 0.6674412	total: 110ms	remaining: 165ms
> > 8:	learn: 0.6652545	total: 111ms	remaining: 136ms
> > 9:	learn: 0.6630779	total: 113ms	remaining: 113ms
> > 10:	learn: 0.6596855	total: 114ms	remaining: 93.5ms
> > 11:	learn: 0.6563190	total: 116ms	remaining: 77.4ms
> > 12:	learn: 0.6529783	total: 117ms	remaining: 63.1ms
> > 13:	learn: 0.6496632	total: 118ms	remaining: 50.7ms
> > 14:	learn: 0.6463733	total: 120ms	remaining: 39.9ms
> > 15:	learn: 0.6431085	total: 121ms	remaining: 30.2ms
> > 16:	learn: 0.6398685	total: 122ms	remaining: 21.5ms
> > 17:	learn: 0.6366532	total: 124ms	remaining: 13.8ms
> > 18:	learn: 0.6334623	total: 125ms	remaining: 6.58ms
> > 19:	learn: 0.6302956	total: 126ms	remaining: 0us
> > TypeError: 'NoneType' object is not callable
> > Exception ignored in: '_catboost._CatBoost.__dealloc__'
> > TypeError: 'NoneType' object is not callable
> > 
> > Process finished with exit code 0
> > ```
> 
> This code example works for me without any errors (with either MacOS 10.13 or Linux Ubumtu 16.04 or Windows 10 with python 3.8.1 and catboost 0.21). So I still need more context to reproduce (Operating system version, do you use conda or pip install?)

Hi, I saw this error as well.

Operating system version: Manjaro Linux 19.0.1

I did a pip install within a conda environment (the conda install fails with this python version so I did pip install):

packages in environment at /home/rlu/miniconda3/envs/gen_py:
| Name     | Version | Build      | Channel     |
|----------|---------|------------|-------------|
| catboost | 0.22    | pypi_0     | pypi        |
| python   | 3.8.1   | h357f687_2 | conda-forge |

**Comment by kizill** [comment] 2020-03-02 21:51
@lrnilingy, I've just installed Manjaro Linux 19.0.1 XFCE into Virtualbox and installed python=3.8 + catboost=0.22 in anaconda and it still doesn't reproduces. Could you provide temporary access to your system so we could debug?

**Comment by lrnilingy** [comment] 2020-03-03 02:52
Hi @kizill I tested creating a new conda environment with python=3.8, and then pip install catboost, indeed there is no issue.

For my existing conda environment, I just removed the pip-installed catboost, and downgrade python to 3.7, and conda install catboost - now the issue is gone. So far so good. Thank you.

**Comment by kizill** [comment] 2020-03-03 09:15
@lrnilingy could you try reverting your anaconda installation back to the point where an issue will reproduce again and then archive it and somehow share with us?

**Comment by nicholasjma** [comment] 2020-03-19 17:31
His example doesn't reproduce for me, and I'm having trouble coming up with a compact example that reproduces the problem, but I have run into this problem, and I think the relevant line of code is here: https://github.com/catboost/catboost/blob/master/catboost/python-package/catboost/_catboost.pyx#L4024

For whatever reason, self.__test_evals.size is None and this is causing __dealloc__ to generate a TypeError. It'd be easy to catch the exception and and just skip the deletions. If you want to know what's causing the model object to be in this state, I can look into what is doing that on my end

**Comment by kizill** [comment] 2020-03-20 10:38
That was a tricky bug - when cython translated a cycle for deallocation of `__test_evals` array members it used mixture of python loop to iterate over range(N), but it could happen when global builtin name `range` would be None already. Now we checked that loop is translated to native c-style loop `for(size_t i = 0; i < N; ++i) {...}` and so we don't call or instantiate any python objects or functions.
The fix is in master, will appear in next release.

**Closed by kizill** 2020-03-20 10:38 UTC
Labels: bug, in progress, need info

**Comment by annaveronika** [comment] 2020-03-20 10:45
Thank you so much for helping us to reproduce it!
