### ISSUE TITLE
NDCG seem to have implicit required argument

### ISSUE THREAD

**Issue by v-goncharenko** [catboost/catboost#2355] opened 2023-04-18 21:04 UTC
Problem: Jupyter kernel dies when I try to calculate NDCG without `group_id` argument
catboost version: 1.1.1
Operating System: MacOS, Ubuntu

```python
from catboost.metrics import NDCG

ndcg = NDCG()
ndcg.eval([1, 2, 3, 4, 5], [1, 2, 3, 4, 5])
```
this causes kernel to die without any message.

```python
from catboost.metrics import NDCG

ndcg = NDCG()
ndcg.eval([1, 2, 3, 4, 5], [1, 2, 3, 4, 5], group_id=[1, 1, 1, 1, 1])
```

this (see `group_id` presented) returns 1.0

Expected behaviour:
**Either** treat absence of `group_id` as single group (preffered by me).
**Or** define `group_id` required argument in docmuentation and raise human readable error when it is not provided.

**Comment by andrey-khropov** [comment] 2023-04-20 10:13
Duplicate of #2343

**Closed by andrey-khropov** 2023-04-20 10:13 UTC
Labels: bug, python, crash
