### ISSUE TITLE
Dying kernel on Jupiter notebook

### ISSUE THREAD

**Issue by AMSolin** [catboost/catboost#1197] opened 2020-03-02 20:10 UTC
Problem: After run model.fit() (CatBoostClassifier) in jupiter notebook i got message "The kernel appears to have died. It will restart automatically.". Its happens also on tutorial https://github.com/catboost/tutorials/blob/master/python_tutorial.ipynb
Re-installing anaconda don't solve problem.

catboost version: 0.22 (same problem 0.21)
Operating System:  Windows 10 Corporate LTSC
CPU: Intel(R) Core(TM)2 Quad_CPU 8400 2.66GHz

**Comment by kizill** [comment] 2020-03-02 20:12
Hi! Could you check jupyter notebook output in console? I hope there could be something like exception or another kind of message.

**Comment by AMSolin** [comment] 2020-03-02 20:18
Hi! In output i got this:
```
[I 23:15:42.605 NotebookApp] Kernel started: bf7ff532-ac0f-4ec0-b5ba-580df2b98c93
[I 23:16:09.574 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel bf7ff532-ac0f-4ec0-b5ba-580df2b98c93 restarted
```

**Comment by AMSolin** [comment] 2020-03-04 21:46
> Hi! Could you check jupyter notebook output in console? I hope there could be something like exception or another kind of message.

my CPU doesn't support AVX instructions. It can be a reason of my problem?

**Comment by kizill** [comment] 2020-03-10 13:18
Could you try attaching a debugger to python.exe that runs your kernel and make crashdump? You may use WinDBG or another windows debugger.

**Comment by annaveronika** [comment] 2020-03-10 13:23
@AMSolin We are trying to reproduce this error for a while already. It reproduces only on Windows and only in some rare cases. We cannot reproduce on our machines. So if you would help us with this it would be very-very cool. If you have any questions about how to make a crashdump or something like that - let us know!

**Comment by AMSolin** [comment] 2020-03-14 10:29
@kizill , @annaveronika got this via WINDBG:

```
(103c.1010): Illegal instruction - code c000001d (first chance)
(103c.1524): Illegal instruction - code c000001d (first chance)
(103c.1010): Illegal instruction - code c000001d (!!! second chance !!!)
*** WARNING: Unable to verify checksum for C:\Users\Alexander\Anaconda3\envs\clear_py.py\lib\site-packages\catboost\_catboost.pyd
_catboost!PyInit__catboost+0x4a6389:
00007ffa`3101e329 f3480fb8c2      popcnt  rax,rdx
```

**Comment by sviperm** [comment] 2020-03-27 13:02
I've got the same error on Ubuntu 18.04 on running cross validation code from [here](https://github.com/catboost/tutorials/blob/master/classification/classification_tutorial.ipynb) and [here](https://github.com/catboost/tutorials/blob/master/cross_validation/cv_tutorial.ipynb)

Code
```
from catboost import cv

# datafrme is pd.DataFrame
# columns: label - _0 or 1_, text - _str_; and index as _int_
dataframe = ...

train, test = train_test_split(dataframe, test_size=0.2)

params = {
    'loss_function': 'Logloss',
    'iterations': 100,
    'custom_loss': 'AUC',
    'learning_rate': 0.1,
    'random_seed': 63,
    'task_type': 'GPU',
}

train_pool = Pool(
    train.drop('label', axis=1),
    train['label'],
    text_features=['text'],
    feature_names=None
)

cv_data = cv(
    params = params,
    pool = train_pool,
    fold_count=5,
    shuffle=True,
    partition_random_seed=0,
    plot=True,
    stratified=True,
    verbose=False
)
```

notebook output in console:
```
[I 15:28:24.226 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports
```
Error is in jupyter lab too. Error missing after commenting `task_type` parameter. Thats very strange, because text processing needs GPU.

[Proof](https://github.com/catboost/tutorials/blob/master/text_features/text_features_in_catboost.ipynb):
```
def fit_catboost_on_rotten_tomatoes(X_train, X_test, y_train, y_test, catboost_params={}, verbose=100):
    learn_pool = Pool(
        X_train, 
        y_train,
        text_features=['text'],
        feature_names=None
    )
    test_pool = Pool(
        X_test, 
        y_test,
        text_features=['text'],
        feature_names=None
    )
    
    catboost_default_params = {
        'iterations': 1000,
        'learning_rate': 0.1,
        'eval_metric': 'Accuracy',
        'task_type': 'CPU'
    }
    
    catboost_default_params.update(catboost_params)
    
    model = CatBoostClassifier(**catboost_default_params)
    model.fit(learn_pool, eval_set=test_pool, verbose=verbose, plot=True)

    return model

fit_catboost_on_rotten_tomatoes(
    train.drop('label', axis=1),
    test.drop('label', axis=1),
    train['label'],
    test['label']
)
```
Output:
```
CatBoostError: catboost/libs/train_lib/train_model.cpp:689: Feature calcers are not supported in CPU training yet
```

Does cross-validation works properly in this situation? Can I use it? or better to use custom methods to check training quality? 

Thank you ❤️

**Comment by annaveronika** [comment] 2020-05-07 14:51
> I've got the same error on Ubuntu 18.04 on running cross validation code from [here](https://github.com/catboost/tutorials/blob/master/classification/classification_tutorial.ipynb) and [here](https://github.com/catboost/tutorials/blob/master/cross_validation/cv_tutorial.ipynb)
> 
> Code
> 
> ```
> from catboost import cv
> 
> # datafrme is pd.DataFrame
> # columns: label - _0 or 1_, text - _str_; and index as _int_
> dataframe = ...
> 
> train, test = train_test_split(dataframe, test_size=0.2)
> 
> params = {
>     'loss_function': 'Logloss',
>     'iterations': 100,
>     'custom_loss': 'AUC',
>     'learning_rate': 0.1,
>     'random_seed': 63,
>     'task_type': 'GPU',
> }
> 
> train_pool = Pool(
>     train.drop('label', axis=1),
>     train['label'],
>     text_features=['text'],
>     feature_names=None
> )
> 
> cv_data = cv(
>     params = params,
>     pool = train_pool,
>     fold_count=5,
>     shuffle=True,
>     partition_random_seed=0,
>     plot=True,
>     stratified=True,
>     verbose=False
> )
> ```
> 
> notebook output in console:
> 
> ```
> [I 15:28:24.226 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports
> ```
> 
> Error is in jupyter lab too. Error missing after commenting `task_type` parameter. Thats very strange, because text processing needs GPU.
> 
> [Proof](https://github.com/catboost/tutorials/blob/master/text_features/text_features_in_catboost.ipynb):
> 
> ```
> def fit_catboost_on_rotten_tomatoes(X_train, X_test, y_train, y_test, catboost_params={}, verbose=100):
>     learn_pool = Pool(
>         X_train, 
>         y_train,
>         text_features=['text'],
>         feature_names=None
>     )
>     test_pool = Pool(
>         X_test, 
>         y_test,
>         text_features=['text'],
>         feature_names=None
>     )
>     
>     catboost_default_params = {
>         'iterations': 1000,
>         'learning_rate': 0.1,
>         'eval_metric': 'Accuracy',
>         'task_type': 'CPU'
>     }
>     
>     catboost_default_params.update(catboost_params)
>     
>     model = CatBoostClassifier(**catboost_default_params)
>     model.fit(learn_pool, eval_set=test_pool, verbose=verbose, plot=True)
> 
>     return model
> 
> fit_catboost_on_rotten_tomatoes(
>     train.drop('label', axis=1),
>     test.drop('label', axis=1),
>     train['label'],
>     test['label']
> )
> ```
> 
> Output:
> 
> ```
> CatBoostError: catboost/libs/train_lib/train_model.cpp:689: Feature calcers are not supported in CPU training yet
> ```
> 
> Does cross-validation works properly in this situation? Can I use it? or better to use custom methods to check training quality?
> 
> Thank you ❤️

Text features were not supported on CPU before version 0.23, now they are supported, so you should not see this error msg.

**Comment by scelikr** [comment] 2020-06-22 11:35
@annaveronika I don't know if these issues are related or not, but I get the same error when using the GPU. When I use the CPU, everything is normal. When using a GPU, my RAM is 100% full and I get a dead kernel error. When I use the CPU on the same data I have about 60% free RAM and everything works well.

**Comment by imitusov** [comment] 2021-02-09 08:39
> @annaveronika I don't know if these issues are related or not, but I get the same error when using the GPU. When I use the CPU, everything is normal. When using a GPU, my RAM is 100% full and I get a dead kernel error. When I use the CPU on the same data I have about 60% free RAM and everything works well.

I have the same issue

**Comment by maximrohit** [comment] 2021-02-25 10:53
Getting the same error!

**Comment by maximrohit** [comment] 2021-02-25 11:25
'grow_policy':'Depthwise' was the parameter causing the issue, although I didn't see a spike in CPU or memory , but a change there got everything to work

**Comment by nstoichkov7** [comment] 2021-06-24 15:01
I have the same issue under Windows 10, CPU Xeon E5-2670, GPU Nvidia GTX 1070, python 3.8
I do not change the value of grow_policy parameter, use it with its default value  "SymmetricTree"

In JupyterLab I got only this error "AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports"
When I execute .py file  with the same code in it, the execution terminates without any errors.

This problem only occur in version 0.26
In version 0.21 everything works fine

**Comment by nateGeorge** [comment] 2021-07-01 04:47
I'm getting the same error on Win10 with catboost version 0.26. With version 0.25.1, it works.

**Comment by kizill** [comment] 2021-07-05 21:30
@nateGeorge @nstoichkov7
Will merge fix in https://github.com/catboost/catboost/pull/1763 and then we will publish release 0.26.1 in a matter of days, thank you all for patience 😺
Closing as duplicate of #1735, more info here

**Closed** 2021-07-05 21:30 UTC

**Comment by v1lev** [comment] 2021-07-26 17:23
When?!

**Comment by garikhgh** [comment] 2021-07-31 21:11
I have the same issue. windows 10

**Comment by pigeongcc** [comment] 2022-11-01 12:22
The same problem. Ubuntu 22.04, catboost 1.1, Python 3.9, Dataspell IDE

Jupyter output:
```
[I 15:19:00.979 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 2765c776-adf4-4501-afe8-69234c766906 restarted
```
At the moment the kernel restarted, this was printed to the console (IDE was started from console):
`2022-11-01 15:19:00,980 [7744710]   WARN - #o.j.p.n.j.m.JupyterMessageBuffer - Too many messages in queue, deleting first`

**Comment by sharov-am** [comment] 2022-11-11 15:36
Hi.

Same issue on Yandex Cloud, DataSpehere, cb is '0.24', cloud machine is g1.1. With CPU everything is fine.

```
#!g1.1
def objective(trial):
    param = {
        
        'task_type': 'GPU', #if get_gpu_device_count() else 'CPU',
        'depth': trial.suggest_int('depth', 2, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.001, 1),
        'iterations': trial.suggest_categorical('iterations', [250,500,1000,1500,2500]),
        'l2_leaf_reg': trial.suggest_int('l2_leaf_reg', 1, 50),
        'verbose':trial.suggest_categorical('verbose',[False]),
        'random_seed':trial.suggest_categorical('random_seed', [37]),
        'grow_policy': trial.suggest_categorical('grow_policy', ['SymmetricTree','Depthwise','Lossguide']),
        "objective": trial.suggest_categorical("objective", ["RMSE"]),
        "eval_metric": trial.suggest_categorical("eval_metric", ["RMSE"]),
        #"boosting_type": trial.suggest_categorical("boosting_type", ["Ordered", "Plain"]),
        "bootstrap_type": trial.suggest_categorical("bootstrap_type", ["Bayesian", "Bernoulli", "MVS"]),
        'early_stopping_rounds':trial.suggest_categorical('early_stopping_rounds',[100]),


    }

    model = cb.CatBoostRegressor(**param)
    model.fit(X_train,y_train,eval_set=[(X_val,y_val)])
    y_pred = model.predict(X_val)
    r2 = r2_score(y_val, y_pred)
    rmse = mean_squared_error(y_val, y_pred, squared=False)
    print(f"Calculate metric score:{'R2: {:.2f}'.format(r2)} {'RMSE: {:.3f}'.format(rmse)}")
    return rmse
```
[I 2022-11-11 15:31:20,906] Trial 0 finished with value: 3.763250243696167 and parameters: {'depth': 3, 'learning_rate': 0.7758876847715672, 'iterations': 500, 'l2_leaf_reg': 13, 'verbose': False, 'random_seed': 37, 'grow_policy': 'Depthwise', 'objective': 'RMSE', 'eval_metric': 'RMSE', 'bootstrap_type': 'Bernoulli', 'early_stopping_rounds': 100}. Best is trial 0 with value: 3.763250243696167.
Calculate metric score:R2: 0.15 RMSE: 3.763
[I 2022-11-11 15:31:22,833] Trial 1 finished with value: 4.013688185406422 and parameters: {'depth': 10, 'learning_rate': 0.0024225603690260465, 'iterations': 250, 'l2_leaf_reg': 22, 'verbose': False, 'random_seed': 37, 'grow_policy': 'SymmetricTree', 'objective': 'RMSE', 'eval_metric': 'RMSE', 'bootstrap_type': 'MVS', 'early_stopping_rounds': 100}. Best is trial 0 with value: 3.763250243696167.
Calculate metric score:R2: 0.03 RMSE: 4.014
[I 2022-11-11 15:31:24,593] Trial 2 finished with value: 3.9417766249908093 and parameters: {'depth': 2, 'learning_rate': 0.045141866900455865, 'iterations': 1000, 'l2_leaf_reg': 49, 'verbose': False, 'random_seed': 37, 'grow_policy': 'SymmetricTree', 'objective': 'RMSE', 'eval_metric': 'RMSE', 'bootstrap_type': 'MVS', 'early_stopping_rounds': 100}. Best is trial 0 with value: 3.763250243696167.
Calculate metric score:R2: 0.07 RMSE: 3.942
[I 2022-11-11 15:31:26,013] Trial 3 finished with value: 3.8787431497598064 and parameters: {'depth': 7, 'learning_rate': 0.9792472670614719, 'iterations': 500, 'l2_leaf_reg': 49, 'verbose': False, 'random_seed': 37, 'grow_policy': 'SymmetricTree', 'objective': 'RMSE', 'eval_metric': 'RMSE', 'bootstrap_type': 'MVS', 'early_stopping_rounds': 100}. Best is trial 0 with value: 3.763250243696167.
Calculate metric score:R2: 0.10 RMSE: 3.879
[I 2022-11-11 15:31:27,746] Trial 4 finished with value: 3.719810999811176 and parameters: {'depth': 5, 'learning_rate': 0.4847457535145216, 'iterations': 500, 'l2_leaf_reg': 49, 'verbose': False, 'random_seed': 37, 'grow_policy': 'Lossguide', 'objective': 'RMSE', 'eval_metric': 'RMSE', 'bootstrap_type': 'Bayesian', 'early_stopping_rounds': 100}. Best is trial 4 with value: 3.719810999811176.
Calculate metric score:R2: 0.17 RMSE: 3.720
[I 2022-11-11 15:31:29,374] Trial 5 finished with value: 3.7062342144406406 and parameters: {'depth': 7, 'learning_rate': 0.2208724963039443, 'iterations': 500, 'l2_leaf_reg': 14, 'verbose': False, 'random_seed': 37, 'grow_policy': 'Depthwise', 'objective': 'RMSE', 'eval_metric': 'RMSE', 'bootstrap_type': 'Bernoulli', 'early_stopping_rounds': 100}. Best is trial 5 with value: 3.7062342144406406.
Calculate metric score:R2: 0.17 RMSE: 3.706
KernelNotResponding: The kernel died unexpectedly and has been restarted. If the restart fails, restart the kernel from the Kernel menu.
