### ISSUE TITLE
Build without strange tools like ya

### ISSUE THREAD

**Issue by KOLANICH** [catboost/catboost#205] opened 2017-12-22 09:46 UTC
It'd be nice if this was built not with `ya` but with an ordinary CMake and setuptools without using any custom tools or any downloaded from the net.

**Comment by annaveronika** [comment] 2017-12-25 10:26
It's a duplicate of #34 
We are planning to release sources of our build system. And we also plan to generate make files, so that it will be possible to build using CMake.

**Closed by annaveronika** 2017-12-25 10:26 UTC
