### ISSUE TITLE
simple_ctr bug

### ISSUE THREAD

**Issue by antipisa** [catboost/catboost#742] opened 2019-03-23 20:44 UTC
I believe there is a bug with the simple_ctr param. The following error at the _end_ of training after .fit() is called.

```
from catboost import CatBoostRegressor, Pool

simple_ctr = ["Borders:TargetBorderCount=15", "Buckets:TargetBorderCount=15", "Borders:TargetBorderType=MinEntropy", "Counter:CtrBorderCount=20"]

params = {"boosting_type":"Ordered", 
"num_boost_round":100,
 "simple_ctr":simple_ctr}

model = CatBoostRegressor(**params)
model.fit(Pool(X,label=y))
```

Traceback:
```

>>>def _train(self, train_pool, test_pool, params, allow_clear_pool):
>>>self._object._train(train_pool, test_pool, params, allow_clear_pool)
>>>self._set_trained_model_attributes()

>>>_catboost.pyx in _catboost._CatBoost._train()
>>>_catboost.pyx in _catboost._CatBoost._train()

CatboostError: util/generic/hash.h:1652: Key not found in hashtable: TModelSplit


```

**Comment by annaveronika** [comment] 2019-04-02 12:33
Thanks for the report, we'll look into this!

**Comment by nikitxskv** [comment] 2019-04-04 13:32
@antipisa Hi!
Now we fixed it.
Try to update, rebuild CatBoost and try again.

**Comment by wang122300090** [comment] 2019-11-11 08:28
I update ,but I did not solve it

**Comment by annaveronika** [comment] 2019-11-11 09:00
@wang122300090 Could you please provide a full reproducing example?

**Comment by annaveronika** [comment] 2019-11-19 14:21
Closing again. @wang122300090 If you will have problems with the new version of CatBoost, please create a new issue and provide a minimal reproducing example.

**Closed by annaveronika** 2019-11-19 14:21 UTC
Labels: in progress

**Comment by kellinpelrine** [comment] 2019-12-06 07:43
I have a similar issue with multiclass classification randomized search, on catboost-0.20.

```
train_pool = Pool(data=X_train,
                 label=y_train,
                 cat_features=[...],
                 weight=train_weights
                  )
model = CatBoostClassifier(
    iterations=10000,
    task_type='GPU'
  )

grid = {'learning_rate': [0.03, 0.1],
        'depth': [4, 6, 10],
        'l2_leaf_reg': [1, 3, 5, 7, 9]}

randomized_search_result = model.randomized_search(grid,
                                                   X=train_pool)
```

Produces the following:

```
0:	loss: 0.0000000	best: 0.0000000 (0)
---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
<ipython-input-16-e470a0a70ca4> in <module>()
     19 
     20 randomized_search_result = model.randomized_search(grid,
---> 21                                                    X=train_pool)
     22 
     23 '''

1 frames
/usr/local/lib/python3.6/dist-packages/catboost/core.py in _tune_hyperparams(self, param_grid, X, y, cv, n_iter, partition_random_seed, calc_cv_statistics, search_by_train_test_split, refit, shuffle, stratified, train_size, verbose, plot)
   3011                 param_grid, train_params["train_pool"], params, n_iter,
   3012                 fold_count, partition_random_seed, shuffle, stratified, train_size,
-> 3013                 search_by_train_test_split, calc_cv_statistics, custom_folds, verbose
   3014             )
   3015 

_catboost.pyx in _catboost._CatBoost._tune_hyperparams()

_catboost.pyx in _catboost._CatBoost._tune_hyperparams()

CatBoostError: util/generic/hash.h:1668: Key not found in hashtable: MultiClass
```

Changing the loss function to MultiClassOneVsAll changes the message correspondingly, so it seems to be something to do with that. Is it a bug?
