### ISSUE TITLE
Trying to install catboost on M1. (Python 3.9.7)

### ISSUE THREAD

**Issue by solanki-aman** [catboost/catboost#1995] opened 2022-01-29 20:23 UTC
Problem: Cannot pip install CatBoost
catboost version: 1.0.4
Operating System: MacOS 12.1
CPU: Apple M1

**Comment by andrey-khropov** [comment] 2022-02-02 23:35
This issue is a duplicate of #1526.

**Closed by andrey-khropov** 2022-02-02 23:35 UTC
Labels: duplicate
