### ISSUE TITLE
PyPI package returns a warning

### ISSUE THREAD

**Issue by henry0312** [catboost/catboost#89] opened 2017-08-20 09:40 UTC
On macOS 10.12.1,
 
```
❯ ipython
Python 3.6.1 (default, May 12 2017, 21:53:15)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import catboost
/usr/local/var/pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module '_catboost' does not match runtime version 3.6
  return f(*args, **kwds)
```

**Comment by annaveronika** [comment] 2017-10-31 16:04
This is a duplicate of
https://github.com/catboost/catboost/issues/138

Most probably the problem is in the way you installed catboost. Maybe you installed it with 3.5 system python, then you run it with anaconda python which is 3.6.

**Closed by annaveronika** 2017-10-31 16:04 UTC
