### ISSUE TITLE
How to  visualize decision tree in catboost

### ISSUE THREAD

**Issue by kumarvrsec** [catboost/catboost#667] opened 2019-02-06 12:20 UTC
How to  visualize decision tree in catboost

**Comment by annaveronika** [comment] 2019-02-21 21:09
That is such a nice feature to have, thanks for the issue! I hope we'll have some external contributer, waiting for help!

**Comment by annaveronika** [comment] 2019-02-21 21:20
I guess this is a duplicate of #355 
Look into that one, we'll post news there. Closing as duplicate.

**Closed by annaveronika** 2019-02-21 21:20 UTC
Labels: help wanted
