### ISSUE TITLE
Quickstart example fails on Python 3.5

### ISSUE THREAD

**Issue by lopuhin** [catboost/catboost#2] opened 2017-07-18 09:26 UTC
This example https://tech.yandex.com/catboost/doc/dg/concepts/python-quickstart-docpage/ fails with the following error:
```---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-e28159aea7ef> in <module>()
      4 model = CatBoostClassifier(iterations=2, depth=2, learning_rate=1, loss_function='Logloss', verbose=True)
      5 model.fit(train_data, train_label, cat_features=[0,2,5], verbose=True)
----> 6 preds_class = model.predict(test_data)
      7 preds_proba = model.predict_proba(test_data)

~/shub/memex/hh-page-classifier/venv/lib/python3.5/site-packages/catboost/core.py in predict(self, data, weight, prediction_type, ntree_limit, verbose)
    964         prediction : numpy.array
    965         """
--> 966         return self._predict(data, weight, prediction_type, ntree_limit, verbose)
    967
    968     def predict_proba(self, data, weight=None,  ntree_limit=0, verbose=None):

~/shub/memex/hh-page-classifier/venv/lib/python3.5/site-packages/catboost/core.py in _predict(self, data, weight, prediction_type, ntree_limit, verbose)
    435
    436     def _predict(self, data, weight, prediction_type, ntree_limit, verbose):
--> 437         verbose = verbose or self.get_param('verbose')
    438         if verbose is None:
    439             verbose = False

~/shub/memex/hh-page-classifier/venv/lib/python3.5/site-packages/catboost/core.py in get_param(self, key)
    630             The param value of the key, returns None if param do not exist.
    631         """
--> 632         params = self.get_params()
    633         if params is None:
    634             return {}

~/shub/memex/hh-page-classifier/venv/lib/python3.5/site-packages/catboost/core.py in get_params(self, deep)
    644             Dictionary of {param_key: param_value}.
    645         """
--> 646         return self._get_params()
    647
    648     def set_params(self, **params):

_catboost.pyx in _catboost._CatBoostBase._get_params (/Users/rnefyodov/.ya/build/build_root/726f38643039646b323639696e6f6e64/catboost/python-package/catboost/_catboost.pyx.cpp:15539)()

_catboost.pyx in _catboost._CatBoost._get_params (/Users/rnefyodov/.ya/build/build_root/726f38643039646b323639696e6f6e64/catboost/python-package/catboost/_catboost.pyx.cpp:12194)()

_catboost.pyx in _catboost._CatBoost._get_params (/Users/rnefyodov/.ya/build/build_root/726f38643039646b323639696e6f6e64/catboost/python-package/catboost/_catboost.pyx.cpp:12049)()

/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    310     if not isinstance(s, str):
    311         raise TypeError('the JSON object must be str, not {!r}'.format(
--> 312                             s.__class__.__name__))
    313     if s.startswith(u'\ufeff'):
    314         raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",

TypeError: the JSON object must be str, not 'bytes'
```

Python 3.5.1 on OS X, ``catboost-0.1.1.2-py3-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl``

**Comment by ma3axaka** [comment] 2017-07-18 11:20
Same thing:
```
anaconda3-2.4.1
catboost: 0.1.1.2
```

**Comment by the31k** [comment] 2017-07-18 22:00
Seems to be fixed by 8fde831.

**Comment by tyz910** [comment] 2017-07-19 05:36
I can confirm that it's working for me.

**Comment by d3trax** [comment] 2017-07-19 18:14
For me it works on osx but fails on ubuntu 16.04
Error same as above: "TypeError: the JSON object must be str, not 'bytes'"
Python 3.5.2

**Comment by the31k** [comment] 2017-07-19 18:16
@d3trax could you please provide the backtrace? Is it exactly the same as above? Are you using updated catboost version?

**Comment by Donskov7** [comment] 2017-07-19 18:18
Which version of CatBoost do you use?

**Comment by d3trax** [comment] 2017-07-20 06:16
Thanks for fast support, version was catboost 0.1.1.2 after upgrade to catboost 0.1.1.5 it works now.

**Closed** 2017-07-20 08:27 UTC
