### ISSUE TITLE
catboost 0.26 GPU R code throws an error.

### ISSUE THREAD

**Issue by issactoast** [catboost/catboost#1761] opened 2021-07-02 14:52 UTC
### System Info.

* catboost version: 0.26
* Operating System: Windows10
* CPU: Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz   3.70 GHz
* GPU: GeForce RTX 2080 SUPER with driver version 465.42

I was trying to run the GPU test R code on the website on my system but 0.26 version throw an error and crashed! I switched to 0.25.1 version (as the website recommends) it works!

```{r}
library(catboost)

countries = as.factor(c('RUS','USA','SUI')) 
years = c(1900,1896,1896)
phone_codes = c(7,1,41)
domains = as.factor(c('ru','us','ch'))

dataset = data.frame(countries, years, phone_codes, domains)

label_values = c(0,1,1)

fit_params <- list(iterations = 100,
                   loss_function = 'Logloss',
                   ignored_features = c(4,9),
                   border_count = 32,
                   depth = 5,
                   learning_rate = 0.03,
                   l2_leaf_reg = 3.5,
                   task_type = 'GPU')

pool = catboost.load_pool(dataset, 
                          label = label_values, 
                          cat_features = c(0,3))

model <- catboost.train(pool, params = fit_params)

```

**Comment by kizill** [comment] 2021-07-05 21:29
Closing as a duplicate of #1735

**Closed by kizill** 2021-07-05 21:29 UTC
