### ISSUE TITLE
multiclass classification in R is causing error

### ISSUE THREAD

**Issue by idavydov** [catboost/catboost#1072] opened 2019-11-13 17:29 UTC
Problem:
When running multiclass classification the following error happens:
```
Error in catboost.get_feature_importance(model, learn_pool): catboost/private/libs/target/data_providers.cpp:435: Non-Multiclassification compatible metric (RMSE) specified for a multidimensional model
```

``` r
library(catboost)

dataset <- matrix(c(
  1900, 7,
  1896, 1,
  1896, 41,
  1777, 2,
  1778, 3
),
nrow = 5,
ncol = 2,
byrow = TRUE
)
label_values <- as.integer(c(0, 1, 1, 2, 2))


fit_params <- list(
  iterations = 100,
  loss_function = "MultiClass",
  metric_period = 20
)

pool <- catboost.load_pool(dataset, label = label_values)

model <- catboost.train(pool, params = fit_params)
#> 0:   learn: 1.0932271    total: 48.7ms   remaining: 4.82s
#> 20:  learn: 0.9859953    total: 53.7ms   remaining: 202ms
#> 40:  learn: 0.8769223    total: 58.5ms   remaining: 84.2ms
#> 60:  learn: 0.7923053    total: 63.2ms   remaining: 40.4ms
#> 80:  learn: 0.7139899    total: 68.2ms   remaining: 16ms
#> 99:  learn: 0.6419358    total: 72.9ms   remaining: 0us
#> Error in catboost.get_feature_importance(model, learn_pool): catboost/private/libs/target/data_providers.cpp:435: Non-Multiclassification compatible metric (RMSE) specified for a multidimensional model
```

<sup>Created on 2019-11-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

catboost version: 0.18.1
Operating System: GNU/Linux x86_64
CPU: Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz

**Comment by annaveronika** [comment] 2019-11-14 08:40
Thank you for the report, we'll look into this!

**Comment by AdrianAntico** [comment] 2019-12-14 08:33
Any update on this? I just noticed this error myself and found this issue as a result. 

```
>     model <- catboost::catboost.train(learn_pool = TrainPool,
+                                       test_pool  = TestPool,
+                                       params     = base_params)  
0:	learn: 1.0663557	test: 1.0656813	best: 1.0656813 (0)	total: 9.91ms	remaining: 486ms
10:	learn: 0.8274498	test: 0.8262478	best: 0.8262478 (10)	total: 97ms	remaining: 344ms
20:	learn: 0.6710445	test: 0.6716983	best: 0.6716983 (20)	total: 188ms	remaining: 260ms
30:	learn: 0.5605617	test: 0.5632216	best: 0.5632216 (30)	total: 276ms	remaining: 169ms
40:	learn: 0.4774568	test: 0.4773240	best: 0.4773240 (40)	total: 368ms	remaining: 80.8ms
49:	learn: 0.4223605	test: 0.4219438	best: 0.4219438 (49)	total: 444ms	remaining: 0us
bestTest = 0.4219437796
bestIteration = 49
Error in catboost.get_feature_importance(model, learn_pool) : 
  c:/goagent/pipelines/buildmaster/catboost.gittt/catboost/private/libs/target/data_providers.cpp:399: Non-Multiclassification and Non-Multiregression compatible metric (RMSE) specified for a multidimensional model
```

**Comment by annaveronika** [comment] 2019-12-17 09:45
We have not yet looked on the issue, we'll update the issue, when we have news. Sorry for the delay!

**Comment by PrecisionAI** [comment] 2019-12-20 20:59
I'm getting this error too. This makes catboost useless for my problem. I wish to note that catboost.cv works OK. Is there a way to get catboost.cv to train a model? The error occurs at the end of traing. Can snapshots be used to recover a model?

**Comment by PrecisionAI** [comment] 2019-12-20 21:26
v0.17.5 doesn't fix the problem. Running the example above produces

Error in catboost.train(pool, params = fit_params) : 
  c:/goagent/pipelines/buildmaster/catboost.gittt/catboost/private/libs/target/data_providers.cpp:628: Multi classification loss/metrics require label data

**Comment by AdrianAntico** [comment] 2019-12-24 19:05
@PrecisionAI I can run it on 17.5 - My best guess is that you installed 17.5 and forgot to restart R before testing again.

**Comment by ebillig** [comment] 2020-01-10 18:31
I am also having this error with multiclass classification in v0.20.2 in R.

I tried v0.17.5 as suggested above and also got the same second error: 
Error in catboost.train(learn_pool = train_pool, test_pool = test_pool,  : 
  c:/goagent/pipelines/buildmaster/catboost.git/catboost/private/libs/target/data_providers.cpp:590: Multi classification loss/metrics require label data

**Comment by annaveronika** [comment] 2020-01-14 10:19
We still have not looked into this. If someone would debug the issue, it would be helpful. Otherwise please wait for the fix.

**Comment by PrecisionAI** [comment] 2020-01-14 11:02
I've given up on catboost. Another problem versions 18, 19, and 20 have in R is that they run out of steam. Catboost starts up using 100% of the CPU (8 threads) then gradually winds down till it is only using one thread worth of CPU. It takes a couple of day at that rate to run my current job. It should only take a few hours. Another problem is that it can be run on the GPU but the accuracy of the model produced is less than the equivalent CPU model. So I can't make a case for using catboost.

**Comment by annaveronika** [comment] 2020-01-14 11:12
The reason for GPU having a lower quality for multiclassification with categorical features is that GPU multiclass doesn't support categorical feature combinations yet. Do you have categorical features?

I'm not sure why could only one thread be used, this should not happen. If you would be able to provide the dataset, we would be able to debug this.

**Comment by PrecisionAI** [comment] 2020-01-14 11:42
I do have categorical features.

I'll send you the R code and data (51MB). How do I get it to you?

**Comment by annaveronika** [comment] 2020-01-14 12:22
Please send it to annaveronika@yandex-team.ru

**Comment by AdrianAntico** [comment] 2020-01-14 17:31
@annaveronika @PrecisionAI @erica-rose 
Looks like it was version 17.3 (not 17.5) that was working. I'm currently on a work computer so I'll check my personal later which I thought I had 17.5 working.

```
devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.17.3/catboost-R-Windows-0.17.3.tgz', INSTALL_opts = c("--no-multiarch"))

library(catboost)

dataset <- matrix(c(
  1900, 7,
  1896, 1,
  1896, 41,
  1777, 2,
  1778, 3
),
nrow = 5,
ncol = 2,
byrow = TRUE
)
label_values <- as.integer(c(0, 1, 1, 2, 2))


fit_params <- list(
  iterations = 100,
  loss_function = "MultiClass",
  metric_period = 20
)

pool <- catboost.load_pool(dataset, label = label_values)
model <- catboost.train(pool, params = fit_params)


0:	learn: 1.0932271	total: 19.8ms	remaining: 1.96s 20:	learn: 0.9859953	total: 316ms	remaining: 1.19s 40:	learn: 0.8769223	total: 616ms	remaining: 886ms 60:	learn: 0.7923053	total: 1.14s	remaining: 730ms 80:	learn: 0.7139899	total: 1.52s	remaining: 357ms 99:	learn: 0.6419358	total: 1.87s	remaining: 0us
--
 
> | >
>

```

**Comment by agracian** [comment] 2020-01-20 16:28
FYI Get the same error in R on v20.2. :-(

Error in catboost.get_feature_importance(model, learn_pool) : catboost/private/libs/target/data_providers.cpp:374: Non-Multiclassification and Non-Multiregression compatible metric (RMSE) specified for a multidimensional model

**Comment by annaveronika** [comment] 2020-01-23 11:44
we are working on the fix right now

**Comment by grag90** [comment] 2020-02-12 11:00
Bug was fixed in current release 0.21.

**Closed** 2020-02-12 11:06 UTC
Labels: R, bug, in progress

**Comment by AdrianAntico** [comment] 2020-02-12 16:58
@grag90  @kizill  Thank you!

**Comment by idavydov** [comment] 2020-02-14 10:02
great, thanks! I can confirm that it works now.
