### ISSUE TITLE
Request to upload source code into PYPI

### ISSUE THREAD

**Issue by deadline1314** [catboost/catboost#1914] opened 2021-11-11 19:30 UTC
Problem: Hello,
Our team want to use Catboost package into our service. However, there is a company wide requirement that when using 3rd party package, it needs some standard audit process. And the package import from PYPI needs source code instead of wheel file.

Is that possible that you can upload source code into PYPI when there is a new feature release? Thanks!

catboost version: v1.0.3+
Operating System: LINUX
CPU: Intel
GPU: NA

**Comment by andrey-khropov** [comment] 2021-11-12 13:35
This issue is a duplicate of #830.

**Closed by andrey-khropov** 2021-11-12 13:35 UTC
