### ISSUE TITLE
CatBoostClassifier calibration with CalibratedClassifierCV

### ISSUE THREAD

**Issue by Luma12** [catboost/catboost#1225] opened 2020-03-20 16:22 UTC
Problem: Calibration of a CatboostClassifier built on categorical data
catboost version:0.21
Operating System: Windows 10
CPU:32

I'm trying to use CalibratedClassifierCV on my Catboost Classifier here defined:
```

X=feature_matrix
y=target_variable

cate_indexes=np.where(X.dtypes =='object')[0]

#definition of classifier: passing indexes of categorical variables
booster_clf = CatBoostClassifier(cat_features=cate_indexes)


model_isotonic = CalibratedClassifierCV(booster_clf, cv=5, method='isotonic')
model_isotonic.fit(X, y)
```
I develop the model on a database including both numerical and categorical variables, so I declare in the Classifier definition, the cat_features input.

However, I keep on having this error when calling the fit function:
```
ValueError: could not convert string to float: 'USA'
```
Is it Catboost with categorical indexes supported in CalibratedClassifierCV?

**Comment by annaveronika** [comment] 2020-03-20 16:29
sklearn CalibratedClassifierCV doesn't support strings, it's an issue in sklearn rather in catboost.
To overcome the problem you can enumerate all the string values and use integer values instead of strings. You can still use cat_features in catboost for these columns, because for catboost it's allowed to use both, integers and strings for categorical features.

**Comment by Luma12** [comment] 2020-03-20 16:35
Do you mean using a LabelEncoder of categorical variables only for calibration?

**Comment by annaveronika** [comment] 2020-03-21 09:58
I mean you can substitute strings with integers in a way that every string is represented with a unique integer number, everything else stays the same. After that sklearn will not throw an error, because there will be no strings in the dataset.

**Comment by annaveronika** [comment] 2020-04-28 16:17
Closing the issue, since there is no problem in catboost, the problem is that strings are not supported in sklearn CalibratedClassifierCV. The solution is explained above.

**Closed by annaveronika** 2020-04-28 16:17 UTC
Labels: sklearn_compatibility, python

**Comment by gunnerVivek** [comment] 2020-06-16 17:51
@annaveronika  Converted strings to integer as you suggested. But still got error, CatBoostError.
Please look at below code.

    # convert from string to integers
    for col in categorical_data.columns: 

        le = LabelEncoder().fit(categorical_data.loc[train_index, col])
        categorical_data.loc[:, col] = le.transform(categorical_data.loc[:, col])

Calibrating the model produces Error:

        GBDT_calibarted = CalibratedClassifierCV(base_estimator=model, cv=3)
        GBDT_calibarted = GBDT_calibarted.fit(cat_data.loc[train_index, features_selected], y[train_index])

Error is:

**CatBoostError**: 'data' is numpy array of floating point numerical type, it means no categorical features, but 'cat_features' parameter specifies nonzero number of categorical features

**Comment by rjafarau** [comment] 2021-06-01 13:23
@annaveronika

**Comment by sumanjumaths** [comment] 2021-06-15 19:56
Is there any update here?

**Comment by zonnalobo** [comment] 2021-09-16 14:01
> @annaveronika Converted strings to integer as you suggested. But still got error, CatBoostError.
> Please look at below code.
> 
> ```
> # convert from string to integers
> for col in categorical_data.columns: 
> 
>     le = LabelEncoder().fit(categorical_data.loc[train_index, col])
>     categorical_data.loc[:, col] = le.transform(categorical_data.loc[:, col])
> ```
> 
> Calibrating the model produces Error:
> 
> ```
>     GBDT_calibarted = CalibratedClassifierCV(base_estimator=model, cv=3)
>     GBDT_calibarted = GBDT_calibarted.fit(cat_data.loc[train_index, features_selected], y[train_index])
> ```
> 
> Error is:
> 
> **CatBoostError**: 'data' is numpy array of floating point numerical type, it means no categorical features, but 'cat_features' parameter specifies nonzero number of categorical features

This issue should be still in open status due to this sample case is still not solved.

**Comment by venergiac-bh** [comment] 2023-06-12 07:41
this one works form me, I wrapper able to use all the parameters of Ctaboost

`    #split
    X_train, X_test, y_train, y_test, weight_train, weight_test = train_test_split( X, y, sample_weight, test_size=test_size, random_state=17)
    X_train, X_eval, y_train, y_eval, weight_train, weight_test = train_test_split( X_train, y_train, weight_train, test_size=0.1, random_state=17)
    
    class CatBoostClassifierWrapper:
        
        def __init__(self, iterations, task_type="GPU", devices='0:1'):
            self.model = CatBoostClassifier(iterations=iterations, 
                               task_type=task_type, 
                               devices=devices)
    
            
        def fit(self,X,y):
            return self.model.fit(X_train, y_train, 
              eval_set=(X_eval, y_eval),
              early_stopping_rounds=100,
              sample_weight = weight_train,
              verbose=False)

        def predict(self,X):
            return self.model.predict(X)
        
        def predict_proba(self,X):
            return self.model.predict_proba(X)
    
        def score(self,X,y):
            return self.model.score(X,y)
    
        def get_params(self, deep):
            return self.model.get_params(deep)
        
        @property
        def classes_(self):
            return model.classes_
    
    model = CalibratedClassifierCV(CatBoostClassifierWrapper(iterations), cv=3)
    
    model.fit(X_train, y_train)`
