### ISSUE TITLE
Error with CatBoost Spark - CatBoostWorkers.176 foreachPartition at Workers.scala:322

### ISSUE THREAD

**Issue by sidharth-iitkgp** [catboost/catboost#2012] opened 2022-02-22 10:22 UTC
Problem:

```
`Job aborted due to stage failure: Task 0 in stage 437.0 failed 4 times, most recent failure: Lost task 0.3 in stage 437.0 (TID 279, lgpbd6624b.gso.aexp.com, executor 5): ExecutorLostFailure (executor 5 exited caused by one of the running tasks) Reason: Container marked as failed: container_e296_1644509996356_1076071_01_000102 on host: lgpbd6624b.gso.aexp.com. Exit status: 134. Diagnostics: Exception from container-launch.
Container id: container_e296_1644509996356_1076071_01_000102
Exit code: 134
Exception message: /bin/bash: line 1: 143259 Aborted                 (core dumped) /usr/java/jdk1.8.0_311-amd64/bin/java -server -Xmx10240m '-XX:MaxDirectMemorySize=512m' '-XX:+UseConcMarkSweepGC' '-XX:+CMSParallelRemarkEnabled' '-XX:+UseCMSInitiatingOccupancyOnly' '-XX:CMSInitiatingOccupancyFraction=30' '-XX:+ScavengeBeforeFullGC' '-XX:+CMSScavengeBeforeRemark' -Djava.io.tmpdir=/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/tmp '-Dspark.rpc.numRetries=5' '-Dspark.rpc.message.maxSize=1024' '-Dspark.authenticate=true' '-Dspark.network.timeout=240s' '-Dspark.driver.port=46031' '-Dspark.history.ui.port=18080' '-Dspark.port.maxRetries=80' -Dspark.yarn.app.container.log.dir=/opt/mapr/hadoop/hadoop-2.7.0/logs/userlogs/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102 -XX:OnOutOfMemoryError='kill %p' org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url spark://CoarseGrainedScheduler@lgpbd2430.gso.aexp.com:46031 --executor-id 5 --hostname lgpbd6624b.gso.aexp.com --cores 2 --app-id application_1644509996356_1076071 --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/__app__.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/cloak-spark-2.3-read.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/hive-contrib-2.3.6-mapr-2110-r3.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/ignis.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/xgboost4j-0.90.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/xgboost4j-spark-0.90.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/catboost-spark_2.3_2.11-1.0.4.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/sigopt-spark_2.11-2.0.0.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/catboost-common-1.0.4.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/catboost-prediction-1.0.4.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/catboost-spark-macros_2.11-1.0.4.jar > /opt/mapr/hadoop/hadoop-2.7.0/logs/userlogs/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/stdout 2> /opt/mapr/hadoop/hadoop-2.7.0/logs/userlogs/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/stderr

Stack trace: ExitCodeException exitCode=134: /bin/bash: line 1: 143259 Aborted                 (core dumped) /usr/java/jdk1.8.0_311-amd64/bin/java -server -Xmx10240m '-XX:MaxDirectMemorySize=512m' '-XX:+UseConcMarkSweepGC' '-XX:+CMSParallelRemarkEnabled' '-XX:+UseCMSInitiatingOccupancyOnly' '-XX:CMSInitiatingOccupancyFraction=30' '-XX:+ScavengeBeforeFullGC' '-XX:+CMSScavengeBeforeRemark' -Djava.io.tmpdir=/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/tmp '-Dspark.rpc.numRetries=5' '-Dspark.rpc.message.maxSize=1024' '-Dspark.authenticate=true' '-Dspark.network.timeout=240s' '-Dspark.driver.port=46031' '-Dspark.history.ui.port=18080' '-Dspark.port.maxRetries=80' -Dspark.yarn.app.container.log.dir=/opt/mapr/hadoop/hadoop-2.7.0/logs/userlogs/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102 -XX:OnOutOfMemoryError='kill %p' org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url spark://CoarseGrainedScheduler@lgpbd2430.gso.aexp.com:46031 --executor-id 5 --hostname lgpbd6624b.gso.aexp.com --cores 2 --app-id application_1644509996356_1076071 --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/__app__.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/cloak-spark-2.3-read.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/hive-contrib-2.3.6-mapr-2110-r3.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/ignis.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/xgboost4j-0.90.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/xgboost4j-spark-0.90.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/catboost-spark_2.3_2.11-1.0.4.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/sigopt-spark_2.11-2.0.0.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/catboost-common-1.0.4.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/catboost-prediction-1.0.4.jar --user-class-path file:/tmp/hadoop-mapr/nm-local-dir/usercache/sshar654/appcache/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/catboost-spark-macros_2.11-1.0.4.jar > /opt/mapr/hadoop/hadoop-2.7.0/logs/userlogs/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/stdout 2> /opt/mapr/hadoop/hadoop-2.7.0/logs/userlogs/application_1644509996356_1076071/container_e296_1644509996356_1076071_01_000102/stderr

	at org.apache.hadoop.util.Shell.runCommand(Shell.java:572)
	at org.apache.hadoop.util.Shell.run(Shell.java:466)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:768)
	at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:355)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:369)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Shell output: main : command provided 1
main : user is sshar654
main : requested yarn user is sshar654
Writing to cgroup task files...


Container exited with a non-zero exit code 134. Last 4096 bytes of stderr :
uncaught exception:
    address -> 0x3a801130410
    what() -> "(Bad file descriptor) util/network/socket.h:76: setsockopt() failed for reuse addr"
    type -> TSystemError


Driver stacktrace:`
```

![image](https://user-images.githubusercontent.com/41946423/155111179-1cf9e692-f5c4-4bf7-b2b5-b07fded7a6be.png)

catboost version: catboost-spark_2.3_2.11-1.0.4
Operating System: Spark version 2.3.1 and Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_311)
CPU:
GPU:
Train data: 4 rows and 3 features
Val data: 3 rows and 3 features
Other details:
spark.driver.memory | 6g
spark.dynamicAllocation.enabled | true
spark.dynamicAllocation.initialExecutors | 2
spark.dynamicAllocation.maxExecutors | 11038
spark.dynamicAllocation.minExecutors | 2
spark.executor.cores | 2
spark.task.cpus | 2
spark.executor.memory | 10g

</body>
</html>

</body>
</html>

</body>
</html>

**Comment by sidharth-iitkgp** [comment] 2022-02-22 10:28
Is this same as [https://github.com/catboost/catboost/issues/1765](url) ?
If yes, any update on this? @andrey-khropov

**Comment by pan5431333** [comment] 2022-02-27 16:56
same issue.

**Comment by andrey-khropov** [comment] 2023-11-23 23:41
Duplicate of #1765

**Closed by andrey-khropov** 2023-11-23 23:41 UTC
