### ISSUE TITLE
Wheel package for python 3.8

### ISSUE THREAD

**Issue by TheBits** [catboost/catboost#1096] opened 2019-11-27 15:32 UTC
Problem: There is no the wheel package build for python 3.8. https://pypi.org/project/catboost/0.19.1/#files
The latest `py3` wheel version is 0.1.1.2. https://pypi.org/project/catboost/0.1.1.2/#files
`pip install catboost` automatically installed it.
catboost version: 0.19.1
Operating System: Arch Linux

**Comment by andrey-khropov** [comment] 2019-11-27 17:49
This issue is a duplicate of #1055

**Closed by andrey-khropov** 2019-11-27 17:49 UTC
Labels: duplicate
