### ISSUE TITLE
Sparse matrix

### ISSUE THREAD

**Issue by DBusAI** [catboost/catboost#4] opened 2017-07-18 11:27 UTC
Is catboost support sparse matrix representation?

**Comment by iezepov** [comment] 2017-07-18 11:31
Duplicate of https://github.com/catboost/catboost/issues/1

**Closed** 2017-07-18 11:31 UTC

**Comment by akogay** [comment] 2017-07-18 12:38
where can i see the answer?

**Comment by s-mx** [comment] 2017-07-19 07:19
@akogay there is a link on duplicate consisting the answer
https://github.com/catboost/catboost/issues/4#issuecomment-316036385
