### ISSUE TITLE
Catboost. Fine Training and Test Output but Poor predictions. WHY?

### ISSUE THREAD

**Issue by BigBrotherTR** [catboost/catboost#1656] opened 2021-04-16 11:43 UTC
Problem: I am training a 250.000 rows of data (time-series) for handling a price prediction depends on over 100+ independent variables. Learning and test outputs seems so good (i.e +/- 20). But when I use model to predict an output from the last row of my data. Output is irrelevant (i.e. error 40.000) 

I couldn't find out how to handle this issue.  

catboost version: 0.25.1
Operating System: Colaboratory
CPU: Colaboratory
# GPU: Colaboratory

**Comment by kizill** [comment] 2021-09-27 19:40
Closing as we can't reproduce this bug.

**Closed by kizill** 2021-09-27 19:40 UTC
Labels: need info, quality
