### ISSUE TITLE
is there a spark wrapper/interface of catboost

### ISSUE THREAD

**Issue by StanWang798** [catboost/catboost#424] opened 2018-07-26 08:53 UTC
I'm currently using spark as my main data science platform and have xgboost and lightgbm worked out. Does catboost has any spark interface?

**Comment by annaveronika** [comment] 2018-07-26 21:53
Is duplicate of #153

**Closed by annaveronika** 2018-07-26 21:53 UTC
Labels: duplicate, in progress

**Comment by ashishanand7** [comment] 2019-08-26 12:40
Do let us know the status on Spark support.
Thanks for all the hardwork to your team. Catboost is awesome.

**Comment by ryukinix** [comment] 2020-02-13 21:53
Any news on that?

**Comment by annaveronika** [comment] 2020-02-14 11:44
We will write the updates when we have them in issue #153
