### ISSUE TITLE
Usage C-API in Golang (Cgo) and get error result for prediction type `Class`

### ISSUE THREAD

**Issue by mirecl** [catboost/catboost#2718] opened 2024-08-09 07:18 UTC
**Problem:** Usage C-API + https://github.com/catboost/catboost/releases/download/v1.2.5/libcatboostmodel-darwin-universal2-1.2.5.dylib in Golang (Cgo) for inference Binary classification with prediction type _Class_ - get error ```...catboost.git/catboost/libs/model/eval_processing.h:202: unsupported prediction type```
```C
if (ApproxDimension == 1) {
      auto blockView = GetResultBlockView(blockId, 1);
      switch (PredictionType) {
          case EPredictionType::Probability:
              CalcSigmoid(blockView, blockView);
              break;
          case EPredictionType::Exponent:
              FastExpInplace(blockView.data(), blockView.ysize());
              break;
          case EPredictionType::Class: // <- Class supported!!!
              for (auto &val : blockView) {
                  val = val > BinclassRawValueBorder;
              }
              break;
          default:
              CB_ENSURE(false, "unsupported prediction type");
 }
```
For example train and predict model in Python:
```Python
from catboost import CatBoostClassifier
# Initialize data
cat_features = [0, 1]
train_data = [["a", "b", 1, 4, 5, 6], ["a", "b", 4, 5, 6, 7], ["c", "d", 30, 40, 50, 60]]
train_labels = [1, 1, -1]
eval_data = [["a", "b", 2, 4, 6, 8], ["a", "d", 1, 4, 50, 60]]

# Initialize CatBoostClassifier
model = CatBoostClassifier(iterations=2, learning_rate=1, depth=2)
# Fit model
model.fit(train_data, train_labels, cat_features)
# Get predicted classes
preds_class = model.predict(eval_data)
# Save model
model.save_model("classifier.cb", pool=train_data)
```
Prediction type set: https://github.com/catboost/catboost/blob/master/catboost/libs/model_interface/c_api.h#L128
Prediction type in Golang:
```Golang
type PredictionType uint32

// https://github.com/catboost/catboost/blob/master/catboost/libs/model/enums.h
const (
	RawFormulaVal PredictionType = iota
	Exponent
	RMSEWithUncertainty
	Probability
	Class
	MultiProbability
)
```
Question:
+ Supported prediction type _Class_ now in C-API❓
+ Example usage prediction type _Class_  in C-API❓

**Catboost version:** 1.2.5
**Operating System:** Mac OS 13.6.4
**CPU:** ✅
**GPU:** 🚫

**Comment by andrey-khropov** [comment] 2024-08-12 11:14
This is a duplicate of #2643. Fix is in the master branch and will be included in the next release.

**Closed by andrey-khropov** 2024-08-12 11:14 UTC
Labels: duplicate

**Comment by andrey-khropov** [comment] 2024-08-12 21:56
> @andrey-khropov, In what version catboost is this bug expected to be fixed?

Next version, most likely it will be 1.2.6. Expected to be released very soon.
