### ISSUE TITLE
not full CPU utilization

### ISSUE THREAD

**Issue by algomaschine** [catboost/catboost#2150] opened 2022-08-20 11:05 UTC
Problem: CPU load is very small
catboost version: latest
Operating System: windows server
CPU: 32 cores
GPU: no

Guys, need an advise. I'm running the generation for 2 models, every dataset takes around 10Gb, but together it takes over 100Gb of RAM. What worries me - CPUs are not utilized efficiently, it stays around 10, 30, 50, some spikes, but not like I'd expect it - to be around 90% load full-time. Can you advise what can I do to load the CPUs more and get models generated faster? Now it says it will take over a day. I'm using defaults for the models. Thanks in advance!

	from catboost import CatBoostClassifier
	model = CatBoostClassifier(
	    task_type='CPU',
	    allow_writing_files=False,
	)
	model.fit(
	    X_train, y_train,
	    cat_features=cat_features,
	    eval_set=(X_validation, y_validation),
	    verbose=True,
	    plot=True
	)

![image](https://user-images.githubusercontent.com/20881228/185743052-9aab092c-ed1f-40aa-9a51-591bf1d4d18b.png)

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2022-08-22 09:14
hi @algomaschine 
how many samples, numeric/categorical features, and categories are there in the training dataset?
i would like to reproduce the issue on a synthetic dataset

**Comment by algomaschine** [comment] 2022-08-22 12:40
@Evgueni-Petrov-aka-espetrov 
Thanks for helping out. So most categorical features have around 10 values. Those:
"TOP_Departure", "Downtrend_Starting", "Downtrend_Neutral", "Downtrend_ApproachingBottom",     "BOTTOM_Arrival","Uptrend_Starting",  "Uptrend_Neutral",   "Uptrend_ApproachingTop",      "BOTTOM_Departure", "TOP_Arrival" (the phases of cycle).

Then the target column has 3 values: [up, dn, None]
All other columns are numeric.

cat features len: 1,306
numeric features len: 4,543
rows total: 221,863

I can actually share my dataset. Would you mind?

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2022-08-22 14:29
@algomaschine yes, of course, please do 😍

**Comment by algomaschine** [comment] 2022-08-23 08:30
Great, here's the data https://filetransfer.io/data-package/b920vRWq#link

Then I run the code below like this
python .\catboost_from_tutorial.py .\crypto_cycle5_long_7days.csv front_3
(trying to forecast column front_3)

`
import pandas as pd
import os
import numpy as np
np.set_printoptions(precision=4)
import catboost
from catboost import *
from catboost import datasets
import sys
from datetime import datetime, timedelta, date
from calendar import monthrange
import fnmatch
from multiprocessing import Pool

def week_of_month(date_value):
    week = date_value.dt.isocalendar()[1] - date_value.replace(day=1).dt.isocalendar()[1] + 1
    return date_value.dt.isocalendar()[1] if week < 0 else week


def read_filez(report):
	df = pd.read_csv(report)
	return(df)


if __name__ == '__main__':


	cycle5 = sys.argv[1]
	crypto_train_df =  pd.read_csv(cycle5)
	target = sys.argv[2]
	cat_features = []

	#####  commment this out for tests without dates
	cat_features.append('weekday')
	cat_features.append('weekofyear')
	cat_features.append('month')
	cat_features.append('day')
	df_norm = crypto_train_df
	df_norm['weekday']=""
	df_norm['weekofyear']=0
	df_norm['month']=0
	df_norm['day']=0
	df_norm['Date'] = pd.to_datetime(df_norm['Date'])
	df_norm['weekday'] = df_norm['Date'].dt.day_name()
	df_norm['weekofyear'] = df_norm['Date'].dt.isocalendar().week
	df_norm['month'] = df_norm['Date'].dt.month
	df_norm['day'] = df_norm['Date'].dt.day
	df_normcrypto_train_df = df_norm
	crypto_train_df['weekday'] = crypto_train_df['weekday'].astype('str')
	crypto_train_df['weekofyear'] = crypto_train_df['weekofyear'].astype('int')
	crypto_train_df['month'] = crypto_train_df['month'].astype('int')
	crypto_train_df['day'] = crypto_train_df['day'].astype('int')


	_tar = 'target_' + target
	crypto_train_df.insert(0,_tar,crypto_train_df[target]) # I make it the first column
	remove_cols = ['mk_3', 'mk_5', 'mk_8', 'mk_10', 'mk_13', 'mk_15', 'mk_21', 'next_day', 'next_day_simple', 'Date'] # https://github.com/catboost/catboost/issues/706   dates not supported in CatBoost
	for c in crypto_train_df.columns:
		if c=='Date' or ("target" not in c and "front" in c):
			crypto_train_df = crypto_train_df.drop(columns=[c])
	#crypto_train_df.to_csv("backup.csv")
	#print(crypto_train_df)

	for col in crypto_train_df.columns:
	    if str(crypto_train_df[col].dtype) == 'object' and target not in col:
	        cat_features.append(col)

	y = crypto_train_df[_tar]
	X = crypto_train_df.drop(_tar, axis=1)


	from sklearn.model_selection import train_test_split
	X_train, X_validation, y_train, y_validation = train_test_split(X,y, train_size = 0.8, random_state = 1234)  

	from catboost import CatBoostClassifier
	model = CatBoostClassifier(

	    task_type='CPU',


	)
	model.fit(
	    X_train, y_train,
	    cat_features=cat_features,
	    eval_set=(X_validation, y_validation),
	    verbose=False,

	)

	print('finished for', target)`

**Comment by algomaschine** [comment] 2022-08-23 10:09
So the error I get in the run (took around 2 days) is somewhat around 0.68 or 0.56, pretty high error

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2022-09-27 04:59
hi @algomaschine !
unfortunately, i do not have a big amd windows server
under linux + intel e5-2660 v2 (2 sockets, 16 cores in total), running your reproducer results in cpu load between 75 and 100%, and requires 80-90Gb of RAM
```
user@ python3.6 catboost_from_tutorial.py crypto_cycle5_long_7days.csv front_1
...
996:    learn: 0.5575971        test: 0.5925376 best: 0.5925361 (994)   total: 3h 44m 55s       remaining: 40.6s
997:    learn: 0.5575446        test: 0.5925275 best: 0.5925275 (997)   total: 3h 45m 9s        remaining: 27.1s
998:    learn: 0.5575234        test: 0.5925266 best: 0.5925266 (998)   total: 3h 45m 22s       remaining: 13.5s
999:    learn: 0.5574999        test: 0.5925190 best: 0.5925190 (999)   total: 3h 45m 36s       remaining: 0us

bestTest = 0.5925190332
bestIteration = 999

model.fit... done
finished for front_1
```
in catboost, boosting implementation is the same for linux/windows and intel/amd
could you please run training in "safe mode" to free more RAM for catboost?
i would also look at "hard fault/sec" in the memory tab in the resource monitor during training -- it should be zero most of time
this utility is present in windows by default
you did `pip install catboost` to install catboost, right?

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2022-09-27 05:04
could you please also check that catboost.__version__ is 1.0.6 or 1.1?

**Comment by algomaschine** [comment] 2022-09-29 18:38
I now try it on GPU, another code and see 'out of memory error'.
It's Windows 11, 64x, 35GB
8MB data file
8 GPU cards NVIDIA GeForce RTX [3070](url)

C:\Users\aabez\Documents\catboost benchmarks\catboost_regression_gpu.py:41: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  my_data.insert(0,'target',my_data['BTCUSDT_1day_ahead'])
C:\Users\aabez\AppData\Local\Programs\Python\Python310\lib\site-packages\catboost\core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
Application terminated with error: PyInit__catboost+1797196 (0x7FFA16DEF6DC)
??+0 (0x7FFA1689781E)
PyInit__catboost+9625403 (0x7FFA175669CB)
PyInit__catboost+9636801 (0x7FFA17569651)
PyInit__catboost+9618684 (0x7FFA17564F8C)
PyInit__catboost+9620221 (0x7FFA1756558D)
??+0 (0x7FFA16A96449)
PyInit__catboost+13154260 (0x7FFA178C4264)
BaseThreadInitThunk+16 (0x7FFA879B54E0)
RtlUserThreadStart+43 (0x7FFA880E485B)

(class TCatBoostException) C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/cuda/cuda_lib/cuda_base.h:183: CUDA error 2: out of memory

**Comment by algomaschine** [comment] 2022-09-29 18:40
the code is simple
`

if __name__ == '__main__':


	import numpy as np
	import pandas as pd
	from numpy import genfromtxt
	from sklearn.model_selection import train_test_split

	import pandas as pd
	import os
	np.set_printoptions(precision=4)
	import sklearn
	from catboost import *
	from catboost import datasets


	from sklearn.model_selection import GridSearchCV
	from catboost import CatBoostRegressor

	import time


	my_data = pd.read_csv('BTCUSDT_until_aug_crosses_prev_cols.csv', sep='\t', header='infer')
	for c in my_data.columns:
		if "USDT" not in c or pd.isnull(my_data[c]).sum() > 0:
			my_data = my_data.drop(columns=[c])
		else:

			my_data[c] = my_data[c].astype(float)


	my_data.insert(0,'target',my_data['BTCUSDT_1day_ahead'])
	remove_cols = ['BTCUSDT_1day_ahead']
	my_data = my_data.drop(columns=remove_cols)
	n = len(my_data.columns)

	my_data.columns = range(0, n)

	train, test = train_test_split(my_data, test_size=0.2) # shuffle=False

	X_train = train.iloc[:,1:]
	y_train = train[0]
	X_test = test.iloc[:,1:]
	y_test = test[0]

	start = time.time()

	model_CBR = CatBoostRegressor(task_type='GPU', allow_writing_files=False)

	parameters = {'depth'         : [6],
                  'learning_rate' : [0.01],
                  'iterations'    : [100]
                 }

	grid = GridSearchCV(estimator=model_CBR, param_grid = parameters, cv = 2, n_jobs=None)
	grid.fit(X_train, y_train)

	end = time.time()

	print(" Results from Grid Search " )
	print("\n The best estimator across ALL searched params:\n", grid.best_estimator_)
	print("\n The best score across ALL searched params:\n", grid.best_score_)
	print("\n The best parameters across ALL searched params:\n", grid.best_params_)

	print('CPU training time for CatBoost (in Seconds):', (end - start))`

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2022-09-30 06:06
catboost + gridsearchcv with the settings above on the adult dataset works fine for me
windows 10
intel core i7-7800x 6 cores
nvidia geforce gtx 1050 ti (4gb ram)
could you please check that there is enough gpu ram on all gpu's?
or, since the dataset is only 8M, it may make sense to select just one of them
say, run python like this `CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=4 python ...`
or, you may specify it like this https://catboost.ai/en/docs/features/training-on-gpu

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2022-10-05 04:52
@algomaschine please let us know if we may close this issue

**Comment by Evgueni-Petrov-aka-espetrov** [comment] 2022-10-05 05:32
this is how catboost runs on a smaller cpu with 1/8 of your dataset
![image](https://user-images.githubusercontent.com/7053671/193988262-37e62918-4ef8-4ea3-9185-2111d8d9a9b1.png)

**Closed** 2022-10-06 08:36 UTC
Labels: Windows
