### ISSUE TITLE
Flatbuffers model verification failed

### ISSUE THREAD

**Issue by pearsongjc** [catboost/catboost#2790] opened 2024-12-28 05:52 UTC
Problem:The server used for training CatBoost is 64-bit, while the model is being verified using 32-bit, which causes the model reading failure for models exceeding 2GB. How can I perform the verification using 64-bit?
catboost version:1.2.7
Operating System:centos7.9
CPU:128 GB of memory
GPU:Two 24 GB GPUs.

**Comment by andrey-khropov** [comment] 2024-12-28 15:36
> How can I perform the verification using 64-bit?
 
 It is not currently possible unless you modify CatBoost's code. See https://github.com/catboost/catboost/issues/2274#issuecomment-1403640003.

**Comment by andrey-khropov** [comment] 2024-12-28 15:36
Duplicate of #2274.

**Closed by andrey-khropov** 2024-12-28 15:36 UTC
