### ISSUE TITLE
JSON dump for trees

### ISSUE THREAD

**Issue by kirmorozov** [catboost/catboost#129] opened 2017-10-10 12:34 UTC
To use models within search engines and other rated systems(ex: Elasticsearch, Solr)
It is good to have export capabilities to export in compatible format.
http://elasticsearch-learning-to-rank.readthedocs.io/en/latest/training-models.html#xgboost-example

References from xgboost
https://github.com/dmlc/xgboost/pull/1726
https://github.com/dmlc/xgboost/issues/1722

I hereby agree to the terms of the CLA available at: [link|https://yandex.ru/legal/cla/?lang=en].

**Comment by annaveronika** [comment] 2017-10-11 11:25
duplicate of https://github.com/catboost/catboost/issues/23
We are planning to support json dump for trees.

**Closed by annaveronika** 2017-10-11 11:25 UTC
Labels: duplicate
